package com.ruoyi.web.controller.shop;

import java.util.*;
import javax.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
import com.alibaba.fastjson2.*;
import com.ruoyi.common.annotation.Anonymous;
import com.ruoyi.common.core.domain.AjaxResult;
import static com.ruoyi.web.controller.shop.ShopService.*;

@Anonymous @RestController @RequestMapping("/shop/app")
public class ShopAppController {
 @Autowired ShopService s;
 @Autowired ShopWorkflow workflow;
 @Autowired ShopAccounts accounts;
 @Autowired ShopWechat wechat;
 @Autowired ShopDistribution distribution;
 @Autowired ShopPartner partner;
 @Autowired ShopOrderProgress orderProgress;
 @Value("${shop.legacy-phone-login:false}") boolean legacyPhone;
 private Map<String,Object> member(HttpServletRequest r){return s.member(r.getHeader("X-Shop-Token"));}
 @GetMapping("/bootstrap") public AjaxResult bootstrap(HttpServletRequest request,@RequestParam(defaultValue="C") String channel){boolean enterprise=false;long buyerId=0,retailId=0;String h=request.getHeader("X-Shop-Token");if(h!=null&&h.length()>7){try{Map<String,Object> buyer=s.member(h);retailId=number(buyer.get("id"));enterprise=Boolean.TRUE.equals(buyer.get("enterprise_access"));buyerId=number(buyer.containsKey("company_pricing_member")?buyer.get("company_pricing_member"):buyer.get("id"));}catch(IllegalArgumentException ignored){}}List<Map<String,Object>> products=s.catalogProducts(retailId,0);Map<String,Object> out=new HashMap<>();out.put("selfPurchaseProfile",partner.catalogPrices(retailId,products));out.put("products",products);out.put("media",s.publishedMedia(channel));out.put("rules",s.rules());out.put("series",s.productSeries());out.put("catalogGroups",partner.settings().getJSONArray("catalogGroups"));out.put("demo",s.isDemo());out.put("wechatPayReady",s.wechatPaymentReady());out.put("wechatLoginReady",wechat.ready());out.put("wechatOnly",wechat.only());return AjaxResult.success(out);}
 @PostMapping("/auth/phone") public AjaxResult phone(@RequestBody JSONObject b){check(s.isDemo()&&legacyPhone,"请使用独立账号注册登录");String phone=b.getString("phone");check(phone!=null&&phone.matches("1[3-9][0-9]{9}"),"请输入正确手机号");check("123456".equals(b.getString("code")),"验证码错误");return AjaxResult.success(s.login("demo-phone:"+phone,"demo",phone,referral(b.get("referrer"))));}
 @PostMapping("/auth/wechat") public AjaxResult wechatLogin(HttpServletRequest r,@RequestBody JSONObject b){accounts.rate(r.getRemoteAddr(),"wechat-login");if(b.getBooleanValue("bindExisting"))accounts.rate(r.getRemoteAddr(),str(b.get("username")));return AjaxResult.success(wechat.login(b));}
 @PostMapping("/account/wechat") public AjaxResult bindWechat(HttpServletRequest r,@RequestBody JSONObject b){long uid=number(member(r).get("id"));accounts.rate(r.getRemoteAddr(),"wechat-bind");wechat.bind(uid,b);return AjaxResult.success();}
 @PostMapping("/auth/register") public AjaxResult register(HttpServletRequest r,@RequestBody JSONObject b){check(!wechat.only(),"请使用微信一键登录");accounts.rate(r.getRemoteAddr(),"register");return AjaxResult.success(accounts.register(b));}
 @PostMapping("/auth/login") public AjaxResult login(HttpServletRequest r,@RequestBody JSONObject b){check(!wechat.only(),"请使用微信一键登录；原账号首次使用请绑定微信");accounts.rate(r.getRemoteAddr(),str(b.get("username")));return AjaxResult.success(accounts.login(b));}
 @PostMapping("/auth/recover") public AjaxResult recover(HttpServletRequest r,@RequestBody JSONObject b){accounts.rate(r.getRemoteAddr(),"recover");accounts.recover(b);return AjaxResult.success();}
 @PostMapping("/account/recovery") public AjaxResult recovery(HttpServletRequest r,@RequestBody JSONObject b){accounts.rate(r.getRemoteAddr(),"recovery-create");return AjaxResult.success(accounts.recovery(number(member(r).get("id")),b));}
 @GetMapping("/account/profile") public AjaxResult profile(HttpServletRequest r){long uid=number(member(r).get("id"));Map<String,Object> profile=accounts.profile(uid);profile.put("hasWechat",wechat.bound(uid));return AjaxResult.success(profile);}
 @PostMapping("/account/profile") @Transactional public AjaxResult saveProfile(HttpServletRequest r,@RequestBody JSONObject b){long uid=number(member(r).get("id"));String name=str(b.get("nickname")).trim(),avatar=str(b.get("avatar")),phone=str(b.get("contactPhone"));check(name.length()>=1&&name.length()<=40,"昵称请填写1至40字");check(phone.isEmpty()||phone.matches("1[3-9][0-9]{9}"),"请填写正确的联系手机号");check(avatar.isEmpty()||s.jdbc().queryForObject("select count(*) from shop_public_file where path=? and member_id=?",Long.class,avatar,uid)>0,"请选择自己上传的头像");s.jdbc().update("update shop_member set nickname=?,avatar=?,contact_phone=? where id=?",name,avatar,phone,uid);s.event("account",uid,"更新个人资料（联系电话未经短信核验）",str(uid));return AjaxResult.success();}
 @PostMapping("/account/password") public AjaxResult password(HttpServletRequest r,@RequestBody JSONObject b){accounts.password(number(member(r).get("id")),b);return AjaxResult.success();}

 @GetMapping("/me") public AjaxResult me(HttpServletRequest r){Map<String,Object> m=member(r);m.put("available",s.available(number(m.get("id"))));return AjaxResult.success(m);}
 @PostMapping("/logout") public AjaxResult logout(HttpServletRequest r){member(r);s.jdbc().update("delete from shop_session where token_hash=?",s.hash(r.getHeader("X-Shop-Token").substring(7)));return AjaxResult.success();}
 @GetMapping("/addresses") public AjaxResult addresses(HttpServletRequest r){return AjaxResult.success(s.jdbc().queryForList("select * from shop_address where member_id=? order by is_default desc,id desc",member(r).get("id")));}
 @PostMapping("/addresses") @Transactional public AjaxResult saveAddress(HttpServletRequest r,@RequestBody JSONObject b){long uid=number(member(r).get("id"));boolean structured=!str(b.get("province")).isEmpty()||!str(b.get("city")).isEmpty()||!str(b.get("district")).isEmpty()||!str(b.get("detail")).isEmpty();if(structured){for(String k:Arrays.asList("province","city","district","detail"))check(!str(b.get(k)).trim().isEmpty()&&str(b.get(k)).length()<=("detail".equals(k)?200:40),"请填写省、市、区县及详细地址");b.put("address",str(b.get("province"))+str(b.get("city"))+str(b.get("district"))+str(b.get("detail")));}check(str(b.get("address")).length()<=300&&str(b.get("name")).length()<=40,"收货姓名或地址过长");check(str(b.get("name")).length()>0&&str(b.get("phone")).matches("1[3-9][0-9]{9}")&&str(b.get("address")).length()>=5,"请填写完整地址");s.one("select id from shop_member where id=? for update",uid);if(b.getLongValue("id")==0){String key=str(b.get("requestKey"));if(!key.isEmpty()){check(key.matches("[a-zA-Z0-9_-]{8,80}"),"地址请求标识不正确");if(s.jdbc().update("insert ignore into shop_address_request(member_id,request_key) values(?,?)",uid,key)==0)return AjaxResult.success();}else if(!s.jdbc().queryForList("select id from shop_address where member_id=? and name=? and phone=? and address=? for update",uid,b.get("name"),b.get("phone"),b.get("address")).isEmpty())return AjaxResult.success();}if(b.getBooleanValue("is_default"))s.jdbc().update("update shop_address set is_default=0 where member_id=?",uid);if(b.getLongValue("id")>0){check(s.jdbc().update("update shop_address set name=?,phone=?,address=?,is_default=? where id=? and member_id=?",b.get("name"),b.get("phone"),b.get("address"),b.getBooleanValue("is_default"),b.getLongValue("id"),uid)==1,"地址不存在");}else s.jdbc().update("insert into shop_address(member_id,name,phone,address,is_default) values(?,?,?,?,?)",uid,b.get("name"),b.get("phone"),b.get("address"),b.getBooleanValue("is_default"));long addressId=b.getLongValue("id")>0?b.getLongValue("id"):s.jdbc().queryForObject("select last_insert_id()",Long.class);s.jdbc().update("update shop_address set province=?,city=?,district=?,detail=? where id=? and member_id=?",str(b.get("province")),str(b.get("city")),str(b.get("district")),str(b.get("detail")),addressId,uid);return AjaxResult.success();}
 @DeleteMapping("/addresses/{id}") public AjaxResult deleteAddress(HttpServletRequest r,@PathVariable long id){s.jdbc().update("delete from shop_address where id=? and member_id=?",id,member(r).get("id"));return AjaxResult.success();}
 @PostMapping("/applications/{kind}") @Transactional public AjaxResult apply(HttpServletRequest r,@PathVariable String kind,@RequestBody JSONObject b){long uid=number(member(r).get("id"));check("enterprise".equals(kind)||"distributor".equals(kind),"申请类型不正确");check("distributor".equals(kind),"申请入口已统一，请提交分销商申请");Map<String,Object> m=s.one("select * from shop_member where id=? for update",uid);check(!Arrays.asList("approved","pending").contains(str(m.get(kind+"_state"))),"当前申请已提交或已通过");check(b.getBooleanValue("agreed"),"请阅读并同意申请协议");String name=str(b.get("name")).trim(),phone=str(b.get("phone")).trim();check(!name.isEmpty(),"请输入真实姓名");check(name.length()>=2&&name.length()<=60,"姓名请填写2至60个字");check(!phone.isEmpty(),"请输入联系手机号");check(phone.matches("1[3-9][0-9]{9}"),"请输入正确的11位手机号");b.put("name",name);b.put("phone",phone);if("enterprise".equals(kind)){String type=str(b.getOrDefault("companyType","美容门店"));check(Arrays.asList("美容门店","美发门店","经销商","其他企业").contains(type),"请选择企业类型");b.put("companyType",type);check(str(b.get("company")).trim().length()>=2,"请填写完整企业名称");check(str(b.get("creditCode")).matches("[A-Z0-9]{18}"),"统一社会信用代码应为18位大写字母或数字");check(s.jdbc().queryForObject("select count(*) from shop_private_file where path=? and member_id=?",Long.class,str(b.get("license")),uid)>0,"请上传本人企业营业执照");}if("distributor".equals(kind)){JSONObject settings=s.distributionApplicationSettings();String file=str(b.get("license"));check(!settings.getBooleanValue("requireApplicationMaterial")||!file.isEmpty(),"请上传商家要求的"+settings.getOrDefault("applicationMaterialLabel","资格核验资料"));if(!file.isEmpty())check(s.jdbc().queryForObject("select count(*) from shop_private_file where path=? and member_id=?",Long.class,file,uid)>0,"请上传本人核验资料，不可引用他人的文件");long inviter=number(b.get("inviterId"));if(inviter>0){long current=number(m.get("referrer_id"));if(current==0)distribution.relation(uid,inviter,false,"确认分销申请邀请来源",str(uid));else check(current==inviter,"已有推广来源，不能通过邀请链接更换");}b.put("materialRequired",settings.getBooleanValue("requireApplicationMaterial"));b.put("materialLabel",settings.getOrDefault("applicationMaterialLabel","资格核验资料"));}b.put("agreementVersion",s.hash(str(s.rules().get("agreementText"))));b.put("verificationMethod","人工核验");s.jdbc().update("update shop_member set "+kind+"_state='pending',"+kind+"_data=?,"+kind+"_note='' where id=?",b.toJSONString(),uid);s.event(kind,uid,"提交审核",str(uid));return AjaxResult.success();}
 @PostMapping("/quote") public AjaxResult quote(HttpServletRequest r,@RequestBody JSONObject b){return AjaxResult.success(s.quote(member(r),b,false));}
 @PostMapping("/orders") public AjaxResult create(HttpServletRequest r,@RequestBody JSONObject b){return AjaxResult.success(s.createOrder(member(r),b));}
 @GetMapping("/orders") public AjaxResult orders(HttpServletRequest r,@RequestParam(required=false) String channel){long uid=number(member(r).get("id"));for(Map<String,Object> o:s.jdbc().queryForList("select id from shop_order where member_id=? and status='pending' and expires_at<=now()",uid))s.expireOrder(number(o.get("id")));List<Map<String,Object>> rows=s.orders(uid);workflow.attachItemsWithProgress(rows);if(channel!=null){check(Arrays.asList("B","C").contains(channel),"订单渠道不正确");rows.removeIf(o->!channel.equals(o.get("channel")));}return AjaxResult.success(rows);}
 @PostMapping("/orders/{id}/{action}") public AjaxResult action(HttpServletRequest r,@PathVariable long id,@PathVariable String action){s.orderAction(number(member(r).get("id")),id,action);return AjaxResult.success();}
 @PostMapping("/after-sales") @Transactional public AjaxResult afterSale(HttpServletRequest r,@RequestBody JSONObject b){long uid=number(member(r).get("id"));long id=b.getLongValue("orderId");Map<String,Object> o=s.one("select * from shop_order where id=? and member_id=? for update",id,uid);check(!s.bankStarted(id)&&!s.creditOrder(id)&&!s.wechatPaymentPaid(id),"请使用按商品申请售后入口");check(s.jdbc().queryForObject("select count(*) from shop_case where order_id=?",Long.class,id)==0,"该订单请使用新版商品售后流程");check(Arrays.asList("paid","shipped","completed").contains(str(o.get("status"))),"当前订单不能申请售后");workflow.checkApplicationWindow(o);check(str(b.get("reason")).trim().length()>=2&&str(b.get("reason")).trim().length()<=500,"请填写2至500字原因");List<Map<String,Object>> old=s.jdbc().queryForList("select * from shop_after_sale where order_id=?",id);if(!old.isEmpty()){check("rejected".equals(old.get(0).get("status")),"该订单已有售后申请");s.jdbc().update("update shop_after_sale set status='pending',reason=?,note='' where order_id=?",b.getString("reason"),id);}else s.jdbc().update("insert into shop_after_sale(order_id,member_id,reason,status) values(?,?,?,'pending')",id,uid,b.getString("reason"));return AjaxResult.success();}
 @GetMapping("/after-sales") public AjaxResult afterSales(HttpServletRequest r){return AjaxResult.success(s.jdbc().queryForList("select a.*,o.order_no,o.amount,o.channel from shop_after_sale a join shop_order o on o.id=a.order_id where "+s.companyOrderScope(number(member(r).get("id")))+" order by a.id desc"));}
 @GetMapping("/distribution") public AjaxResult distribution(HttpServletRequest r){long uid=number(member(r).get("id"));Map<String,Object> result=new HashMap<>();result.put("available",s.available(uid));result.put("lineRewards",s.jdbc().queryForList("select * from shop_reward where member_id=?"+s.verifiedPayment("shop_reward.order_id"),uid));result.put("commission",s.jdbc().queryForList("select c.*,o.order_no from shop_commission c join shop_order o on o.id=c.order_id where c.member_id=?"+s.verifiedPayment("o.id")+" order by c.id desc",uid));result.put("ledger",s.jdbc().queryForList("select e.*,o.order_no from shop_commission_event e join shop_order o on o.id=e.order_id where e.member_id=?"+s.verifiedPayment("o.id")+" order by e.id desc",uid));result.put("withdrawals",s.maskWithdrawals(s.jdbc().queryForList("select * from shop_withdrawal where member_id=?"+(s.isOfficialDisplay()?" and payment_mode<>'simulation'":"")+" order by id desc",uid)));result.put("customers",s.jdbc().queryForList("select nickname,created_at from shop_member where referrer_id=?",uid));return AjaxResult.success(result);}
 @PostMapping("/withdrawals") public AjaxResult withdraw(HttpServletRequest r,@RequestBody JSONObject b){s.withdraw(number(member(r).get("id")),b);return AjaxResult.success();}
 @GetMapping("/cases") public AjaxResult cases(HttpServletRequest r){return AjaxResult.success(workflow.cases(number(member(r).get("id"))));}
 @PostMapping("/cases") public AjaxResult newCase(HttpServletRequest r,@RequestBody JSONObject b){workflow.apply(number(member(r).get("id")),b);return AjaxResult.success();}
 @PostMapping("/cases/{id}/return") public AjaxResult returnCase(HttpServletRequest r,@PathVariable long id,@RequestBody JSONObject b){workflow.returnParcel(number(member(r).get("id")),id,b);return AjaxResult.success();}
 @GetMapping("/orders/{id}/shipments") public AjaxResult shipments(HttpServletRequest r,@PathVariable long id){s.companyOrder(number(member(r).get("id")),id,"view",false);return AjaxResult.success(workflow.shipments(id));}
 @GetMapping("/orders/{id}/progress") public AjaxResult progress(HttpServletRequest r,@PathVariable long id){return AjaxResult.success(orderProgress.read(number(member(r).get("id")),id));}

 @PostMapping("/orders/{oid}/shipments/{id}/receive") public AjaxResult receiveParcel(HttpServletRequest r,@PathVariable long oid,@PathVariable long id){workflow.receiveParcel(number(member(r).get("id")),oid,id);return AjaxResult.success();}
 @PostMapping("/cases/{id}/receive") public AjaxResult receiveReplacement(HttpServletRequest r,@PathVariable long id){workflow.receiveReplacement(number(member(r).get("id")),id);return AjaxResult.success();}

}
