package com.ruoyi.web.controller.shop;
import java.util.*;import java.time.LocalDate;import java.time.temporal.ChronoUnit;
import com.alibaba.fastjson2.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.context.annotation.Lazy;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopStatement {
 @Autowired @Lazy ShopService s;@Autowired @Lazy ShopCompany company;
 private Map<String,Object> finance(long uid){Map<String,Object> c=company.historyContext(uid);check(Arrays.asList("owner","finance").contains(str(c.get("role"))),"对账由企业负责人或财务处理");return c;}
 private LocalDate end(String from,String to){LocalDate a=LocalDate.parse(from),b=LocalDate.parse(to);check(!b.isBefore(a)&&ChronoUnit.DAYS.between(a,b)<=366,"请选择一年以内的对账期间");return b.plusDays(1);}
 private long debt(long cid,String before){return s.jdbc().queryForObject("select coalesce(sum(case when kind='purchase' then amount when kind in ('repayment','refund') then -amount else 0 end),0) from shop_credit_event where company_id=? and created_at<?",Long.class,cid,before);}
 @Transactional public JSONObject statement(long uid,String from,String to){Map<String,Object> c=finance(uid);long cid=number(c.get("id"));String until=end(from,to).toString();JSONObject out=new JSONObject();out.put("company",c.get("name"));out.put("from",from);out.put("to",to);out.put("opening",debt(cid,from));out.put("closing",debt(cid,until));
 List<Map<String,Object>> loan=s.jdbc().queryForList("select concat('credit_',e.id) event_key,e.kind,e.amount,e.note,e.created_at occurred_at,o.order_no,e.order_id from shop_credit_event e left join shop_order o on o.id=e.order_id where e.company_id=? and e.kind in ('purchase','repayment','refund') and e.created_at>=? and e.created_at<? order by e.created_at,e.id",cid,from,until);long purchases=0,repayments=0,refunds=0;for(Map<String,Object> e:loan){String kind=str(e.get("kind"));long amount=number(e.get("amount"));if("purchase".equals(kind))purchases+=amount;if("repayment".equals(kind))repayments+=amount;if("refund".equals(kind))refunds+=amount;}out.put("creditPurchases",purchases);out.put("repayments",repayments);out.put("creditRefunds",refunds);check(number(out.get("opening"))+purchases-repayments-refunds==number(out.get("closing")),"账期对账金额不一致，请联系财务核对");
 List<Map<String,Object>> cash=s.jdbc().queryForList("select concat('cash_',f.event_key) event_key,concat(coalesce(p.mode,'simulation'),'_',f.kind) kind,f.amount,'订单收退款记录（按付款渠道分别标记）' note,f.occurred_at,o.order_no,o.id order_id from shop_finance_event f join shop_order o on o.id=f.object_id left join shop_payment p on p.order_id=o.id where o.company_id=? and f.kind in ('payment','refund') and coalesce(p.mode,'simulation')<>'credit' and f.occurred_at>=? and f.occurred_at<? order by f.occurred_at,f.event_key",cid,from,until);
 List<Map<String,Object>> rows=new ArrayList<>();rows.addAll(loan);rows.addAll(cash);rows.addAll(s.jdbc().queryForList("select concat('bank_',f.event_key) event_key,f.kind,f.amount,'银行实际核验记录，与订单记账分开列示' note,f.occurred_at,o.order_no,o.id order_id from shop_finance_event f join shop_order o on o.id=f.object_id where o.company_id=? and f.kind in ('bank_received','bank_outcome','bank_return') and f.occurred_at>=? and f.occurred_at<? order by f.occurred_at,f.event_key",cid,from,until));rows.sort(Comparator.comparing(e->str(e.get("occurred_at"))+str(e.get("event_key"))));check(rows.size()<=10000,"对账明细较多，请缩短查询期间");out.put("rows",rows);String hash=s.hash(out.toJSONString());out.put("hash",hash);out.put("issues",s.jdbc().queryForList("select * from shop_statement_issue where company_id=? and from_date=? and to_date=? order by id",cid,from,to));List<Map<String,Object>> confirmations=s.jdbc().queryForList("select id,snapshot_hash,confirmed_by,created_at from shop_statement_confirmation where company_id=? and from_date=? and to_date=? order by id desc",cid,from,to);out.put("confirmations",confirmations);out.put("confirmed",!confirmations.isEmpty()&&hash.equals(confirmations.get(0).get("snapshot_hash")));return out;}
 @Transactional public void issue(long uid,JSONObject b){Map<String,Object> c=finance(uid);long cid=number(c.get("id"));s.one("select id from shop_company where id=? for update",cid);String from=b.getString("from"),to=b.getString("to"),key=str(b.get("eventKey")),note=str(b.get("note")).trim();JSONObject view=statement(uid,from,to);check(!note.isEmpty()&&note.length()<=300,"请说明300字以内的差异");boolean found=false;for(Object obj:view.getJSONArray("rows")){if(key.equals(((Map<?,?>)obj).get("event_key")))found=true;}check(found,"所选记录不在本企业本期对账单内");s.jdbc().update("insert into shop_statement_issue(company_id,from_date,to_date,event_key,note,operator_id) values(?,?,?,?,?,?) on duplicate key update note=values(note),status='open',resolution=null,operator_id=values(operator_id)",cid,from,to,key,note,uid);s.event("statement",cid,"标记对账差异 "+key,str(uid));}
 @Transactional public void resolve(long uid,long id,JSONObject b){Map<String,Object> c=finance(uid);s.one("select id from shop_company where id=? for update",c.get("id"));String note=str(b.get("note")).trim();check(!note.isEmpty()&&note.length()<=300,"请填写差异处理说明");check(s.jdbc().update("update shop_statement_issue set status='resolved',resolution=?,operator_id=? where id=? and company_id=?",note,uid,id,c.get("id"))==1,"差异不属于当前企业");s.event("statement",number(c.get("id")),"确认差异已处理 "+id,str(uid));}
 @Transactional public void confirm(long uid,JSONObject b){Map<String,Object> c=finance(uid);long cid=number(c.get("id"));s.one("select id from shop_company where id=? for update",cid);JSONObject current=statement(uid,b.getString("from"),b.getString("to"));check(str(b.get("hash")).equals(current.getString("hash")),"对账数据已变化，请刷新并核对后再确认");for(Object obj:current.getJSONArray("issues"))check(!"open".equals(((Map<?,?>)obj).get("status")),"请先处理标记的对账差异");s.jdbc().update("insert ignore into shop_statement_confirmation(company_id,from_date,to_date,snapshot_hash,snapshot_json,confirmed_by) values(?,?,?,?,?,?)",cid,current.get("from"),current.get("to"),current.get("hash"),current.toJSONString(),uid);s.event("statement",cid,"确认期间对账 "+current.get("from")+" 至 "+current.get("to"),str(uid));}
}
