package com.ruoyi.web.controller.shop;
import java.io.*;import javax.servlet.http.HttpServletRequest;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.web.bind.annotation.*;import org.springframework.http.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import org.apache.poi.ss.usermodel.*;import com.alibaba.fastjson2.*;import com.ruoyi.common.annotation.Anonymous;import com.ruoyi.common.core.domain.AjaxResult;import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController @RequestMapping("/shop/app/company/statement") public class ShopStatementController {
 @Autowired ShopService s;@Autowired ShopStatement statement;private long uid(HttpServletRequest r){return number(s.member(r.getHeader("X-Shop-Token")).get("id"));}
 @Anonymous @GetMapping public AjaxResult get(HttpServletRequest r,@RequestParam String from,@RequestParam String to){return AjaxResult.success(statement.statement(uid(r),from,to));}
 @Anonymous @PostMapping("/issues") public AjaxResult issue(HttpServletRequest r,@RequestBody JSONObject b){statement.issue(uid(r),b);return AjaxResult.success();}
 @Anonymous @PostMapping("/issues/{id}/resolve") public AjaxResult resolve(HttpServletRequest r,@PathVariable long id,@RequestBody JSONObject b){statement.resolve(uid(r),id,b);return AjaxResult.success();}
 @Anonymous @PostMapping("/confirm") public AjaxResult confirm(HttpServletRequest r,@RequestBody JSONObject b){statement.confirm(uid(r),b);return AjaxResult.success();}
 @Anonymous @GetMapping("/export") public ResponseEntity<byte[]> export(HttpServletRequest r,@RequestParam String from,@RequestParam String to)throws IOException {JSONObject v=statement.statement(uid(r),from,to);try(XSSFWorkbook workbook=new XSSFWorkbook();ByteArrayOutputStream output=new ByteArrayOutputStream()){Sheet summary=workbook.createSheet("账期应收核对");String[] names={"企业","开始日期","结束日期","期初应收（元）","本期账期采购（元）","核销还款（元）","退款冲应收（元）","期末应收（元）"};String[] keys={"company","from","to","opening","creditPurchases","repayments","creditRefunds","closing"};CellStyle moneyStyle=workbook.createCellStyle();moneyStyle.setDataFormat(workbook.createDataFormat().getFormat("#,##0.00"));for(int i=0;i<keys.length;i++){Row row=summary.createRow(i);row.createCell(0).setCellValue(names[i]);Cell cell=row.createCell(1);if(i>=3){cell.setCellValue(number(v.get(keys[i]))/100.0);cell.setCellStyle(moneyStyle);}else cell.setCellValue(str(v.get(keys[i])));}summary.setColumnWidth(0,28*256);summary.setColumnWidth(1,42*256);Sheet details=workbook.createSheet("逐笔明细");String[] headers={"时间","订单号","类型","金额（元）","说明","差异标记"};Row header=details.createRow(0);for(int i=0;i<headers.length;i++)header.createCell(i).setCellValue(headers[i]);JSONArray rows=v.getJSONArray("rows"),issues=v.getJSONArray("issues");for(int i=0;i<rows.size();i++){JSONObject e=rows.getJSONObject(i);Row row=details.createRow(i+1);row.createCell(0).setCellValue(str(e.get("occurred_at")));row.createCell(1).setCellValue(e.getString("order_no"));row.createCell(2).setCellValue(label(e.getString("kind")));Cell amount=row.createCell(3);amount.setCellValue(e.getLongValue("amount")/100.0);amount.setCellStyle(moneyStyle);row.createCell(4).setCellValue(e.getString("note"));String issue="";for(int k=0;k<issues.size();k++){JSONObject x=issues.getJSONObject(k);if(e.getString("event_key").equals(x.getString("event_key")))issue=("open".equals(x.getString("status"))?"待处理：":"已处理：")+x.getString("note")+" "+str(x.get("resolution"));}row.createCell(5).setCellValue(issue);}for(int i=0;i<6;i++)details.setColumnWidth(i,(i>=4?50:i==3?18:27)*256);details.createFreezePane(0,1);workbook.write(output);return ResponseEntity.ok().cacheControl(CacheControl.noStore()).header("Content-Disposition","attachment; filename=statement-"+from+"-"+to+".xlsx").contentType(MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")).body(output.toByteArray());}}
 public static String label(String kind){switch(kind){case "purchase":return "账期采购";case "repayment":return "核销还款";case "refund":return "退款冲应收";case "bank_transfer_payment":return "对公订单付款";case "bank_transfer_refund":return "对公订单退款";case "bank_received":return "银行实际收款核验";case "bank_outcome":case "bank_return":return "银行实际退款确认";case "simulation_payment":return "非实收订单记录";case "simulation_refund":return "非实收退款记录";default:return kind;}}
}
