package com.ruoyi.web.controller.shop;
import java.io.*;import java.nio.file.*;import java.util.*;import javax.imageio.ImageIO;import javax.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;
import com.alibaba.fastjson2.JSONObject;import com.ruoyi.common.annotation.Anonymous;import com.ruoyi.common.core.domain.AjaxResult;import com.ruoyi.common.utils.SecurityUtils;import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController public class ShopChatController {
 @Autowired ShopService s;@Autowired ShopChat chat;@Value("${shop.private-path:../runtime/private}") String privatePath;
 private long uid(HttpServletRequest r){return number(s.member(r.getHeader("X-Shop-Token")).get("id"));}
 @Anonymous @GetMapping("/shop/app/support") public AjaxResult own(HttpServletRequest r,@RequestParam(defaultValue="0") long before){return AjaxResult.success(chat.ownView(uid(r),before));}
 @Anonymous @PostMapping("/shop/app/support/messages") public AjaxResult send(HttpServletRequest r,@RequestBody JSONObject b){chat.sendMember(uid(r),b);return AjaxResult.success();}
 @Anonymous @PostMapping("/shop/app/support/read") public AjaxResult read(HttpServletRequest r,@RequestBody JSONObject b){chat.memberRead(uid(r),b.getLongValue("lastId"));return AjaxResult.success();}
 @Anonymous @PostMapping("/shop/app/support/images") public AjaxResult image(HttpServletRequest r,@RequestParam("file")MultipartFile file)throws IOException {long uid=uid(r);return saveImage(number(chat.own(uid).get("id")),"member:"+uid,file);}
 @Anonymous @GetMapping("/shop/app/support/images/{id}") public ResponseEntity<byte[]> imageRead(HttpServletRequest r,@PathVariable long id)throws IOException {return imageFile(chat.image(id,uid(r)));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer')") @GetMapping("/shop/admin/support") public AjaxResult admin(){JSONObject r=new JSONObject();r.put("rows",chat.admin());r.put("settings",chat.settings());return AjaxResult.success(r);}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer')") @GetMapping("/shop/admin/support/{id}") public AjaxResult view(@PathVariable long id,@RequestParam(defaultValue="0") long before){return AjaxResult.success(chat.view(id,before));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer')") @PostMapping("/shop/admin/support/{id}/claim") public AjaxResult claim(@PathVariable long id){chat.claim(id,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer')") @PostMapping("/shop/admin/support/{id}/messages") public AjaxResult reply(@PathVariable long id,@RequestBody JSONObject b){chat.sendStaff(id,SecurityUtils.getUsername(),b);return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer')") @PostMapping("/shop/admin/support/{id}/read") public AjaxResult staffRead(@PathVariable long id,@RequestBody JSONObject b){chat.staffRead(id,b.getLongValue("lastId"),SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer')") @PostMapping("/shop/admin/support/{id}/state") public AjaxResult state(@PathVariable long id,@RequestBody JSONObject b){chat.state(id,SecurityUtils.getUsername(),b,false);return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer')") @PostMapping("/shop/admin/support/{id}/images") public AjaxResult staffImage(@PathVariable long id,@RequestParam("file")MultipartFile file)throws IOException {String who=SecurityUtils.getUsername();chat.allowStaffImage(id,who);return saveImage(id,"staff:"+who,file);}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer')") @GetMapping("/shop/admin/support/images/{id}") public ResponseEntity<byte[]> staffImageRead(@PathVariable long id)throws IOException {return imageFile(chat.image(id,null));}
 @PreAuthorize("@ss.hasPermi('shop:manage')") @PostMapping("/shop/admin/support-settings") public AjaxResult settings(@RequestBody JSONObject b){chat.settings(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer')") @GetMapping("/shop/admin/support/{id}/orders/{orderId}") public AjaxResult order(@PathVariable long id,@PathVariable long orderId){check(s.jdbc().queryForObject("select count(*) from shop_chat_message where chat_id=? and order_id=?",Long.class,id,orderId)>0,"该订单未关联此会话");Map<String,Object> o=s.one("select order_no,status,amount,refunded_amount,address_json,carrier,tracking from shop_order where id=?",orderId);o.put("items",s.jdbc().queryForList("select name,spec,quantity,price from shop_order_item where order_id=?",orderId));return AjaxResult.success(o);}
 private AjaxResult saveImage(long id,String who,MultipartFile file)throws IOException {check(file.getSize()>0&&file.getSize()<=5*1024*1024,"图片须小于5MB");java.awt.image.BufferedImage image=ImageIO.read(new ByteArrayInputStream(file.getBytes()));check(image!=null&&image.getWidth()<=8000&&image.getHeight()<=8000,"请上传JPG或PNG图片");Path dir=Paths.get(privatePath).toAbsolutePath().normalize().resolve("chat");Files.createDirectories(dir);String name=UUID.randomUUID().toString()+".png";Path path=dir.resolve(name);boolean recorded=false;try{ImageIO.write(image,"png",path.toFile());JSONObject result=new JSONObject();result.put("id",chat.registerImage(id,name,who));recorded=true;return AjaxResult.success(result);}finally{if(!recorded)Files.deleteIfExists(path);}}
 private ResponseEntity<byte[]> imageFile(Map<String,Object> f)throws IOException {String name=str(f.get("path"));check(name.matches("[a-f0-9-]{36}\\.png"),"图片不存在");Path path=Paths.get(privatePath).toAbsolutePath().normalize().resolve("chat").resolve(name);if(!Files.exists(path))return ResponseEntity.notFound().build();return ResponseEntity.ok().cacheControl(CacheControl.noStore()).contentType(MediaType.IMAGE_PNG).body(Files.readAllBytes(path));}
}
