package com.ruoyi.web.controller.shop;
import javax.servlet.http.HttpServletRequest;import com.alibaba.fastjson2.JSONObject;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.prepost.PreAuthorize;import com.ruoyi.common.annotation.Anonymous;import com.ruoyi.common.core.domain.AjaxResult;import com.ruoyi.common.utils.SecurityUtils;import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController public class ShopDeliveryController {
 @Autowired ShopDelivery d;@Autowired ShopService s;
 @Anonymous @GetMapping("/shop/app/delivery-options") public AjaxResult options(){return AjaxResult.success(d.settings());}
 @Anonymous @GetMapping("/shop/app/orders/{id}/delivery") public AjaxResult own(HttpServletRequest r,@PathVariable long id){return AjaxResult.success(d.info(number(s.member(r.getHeader("X-Shop-Token")).get("id")),id));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse,shop:finance,shop:customer')") @GetMapping("/shop/admin/delivery") public AjaxResult admin(){JSONObject r=new JSONObject();r.put("settings",d.settings());r.put("warehouses",s.jdbc().queryForList("select id,name from shop_warehouse where enabled=1"));r.put("pickups",s.jdbc().queryForList("select o.channel,o.id,o.order_no,o.status,d.pickup_status,d.snapshot_json"+ShopQueryFields.fields("o.member_id")+" from shop_delivery_order d join shop_order o on o.id=d.order_id where d.method='pickup' order by o.id desc"));return AjaxResult.success(r);}
 @PreAuthorize("@ss.hasPermi('shop:manage')") @PostMapping("/shop/admin/delivery/settings") public AjaxResult save(@RequestBody JSONObject b){d.save(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse')") @PostMapping("/shop/admin/delivery/{id}/prepare") public AjaxResult prepare(@PathVariable long id){d.prepare(id,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse')") @PostMapping("/shop/admin/delivery/collect") public AjaxResult collect(@RequestBody JSONObject b){d.collect(str(b.get("orderNo")),str(b.get("code")),SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse,shop:finance,shop:customer')") @GetMapping("/shop/admin/delivery/shipments") public AjaxResult shipments(@RequestParam String orderNo){return AjaxResult.success(s.jdbc().queryForList("select p.*,o.channel"+ShopQueryFields.fields("o.member_id")+" from shop_shipment p join shop_order o on o.id=p.order_id where o.order_no=? order by p.id",orderNo));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse,shop:customer')") @PostMapping("/shop/admin/delivery/shipments/{id}/trace") public AjaxResult trace(@PathVariable long id,@RequestBody JSONObject b){d.trace(id,b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:finance')") @PostMapping("/shop/admin/delivery/shipping-refund") public AjaxResult refund(@RequestBody JSONObject b){long oid=number(s.one("select id from shop_order where order_no=?",str(b.get("orderNo"))).get("id"));d.supplement(oid,b,SecurityUtils.getUsername());return AjaxResult.success();}
}
