package com.ruoyi.web.controller.shop;
import java.util.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import com.alibaba.fastjson2.*;import com.ruoyi.common.core.domain.AjaxResult;import com.ruoyi.common.utils.SecurityUtils;import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController @RequestMapping("/shop/admin/assistance") public class ShopAssistanceController {
@Autowired ShopService s;@Autowired ShopWorkflow workflow;@Autowired ShopCredit credit;
private Map<String,Object> disabled(String no){check(no.length()>0&&no.length()<=80,"请填写完整订单编号");return s.one("select o.*,m.nickname from shop_order o join shop_member m on m.id=o.member_id where o.order_no=? and m.enabled=0",no);}
@PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer,shop:finance')") @GetMapping("/order") public AjaxResult lookup(@RequestParam String orderNo){Map<String,Object> o=disabled(orderNo.trim());o.put("items",workflow.itemsWithProgress(number(o.get("id"))));o.put("shipments",workflow.shipments(number(o.get("id"))));o.put("cases",s.jdbc().queryForList("select * from shop_case where order_id=? order by id desc",o.get("id")));o.put("credit",s.jdbc().queryForList("select * from shop_credit_order where order_id=?",o.get("id")));o.put("assistanceLogs",s.jdbc().queryForList("select created_at,operator_name,action from shop_event where object_type='order' and object_id=? and action like '客服代办%' order by id desc limit 30",o.get("id")));return AjaxResult.success(o);}
@PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer,shop:finance')") @PostMapping("/order") @Transactional public AjaxResult assist(@RequestBody JSONObject b){String who=SecurityUtils.getUsername(),reason=str(b.get("reason")).trim(),key=str(b.get("requestKey")),action=str(b.get("action"));check(reason.length()>=2&&reason.length()<=300,"请填写客户授权与核实依据");check(key.matches("[a-zA-Z0-9_-]{8,80}"),"请重新提交");Map<String,Object> o=disabled(str(b.get("orderNo")).trim());long oid=number(o.get("id")),uid=number(o.get("member_id"));s.one("select id from shop_member where id=? and enabled=0 for update",uid);String hash=s.hash(b.toJSONString());List<Map<String,Object>> prior=s.jdbc().queryForList("select * from shop_assistance_request where actor=? and request_key=?",who,key);if(!prior.isEmpty()){check(hash.equals(prior.get(0).get("payload_hash")),"重复请求内容已变化，请刷新后重试");return AjaxResult.success();}JSONObject data=b.getJSONObject("data");if(data==null)data=new JSONObject();data.put("orderId",oid);data.put("requestKey",key);
if("case".equals(action)){data.put("reason",reason);workflow.apply(uid,data);}else if("cancel".equals(action))s.orderAction(uid,oid,"cancel");else if("receive".equals(action))workflow.receiveParcel(uid,oid,data.getLongValue("parcelId"));else if("return".equals(action)||"replacement".equals(action)){long cid=data.getLongValue("caseId");s.one("select id from shop_case where id=? and order_id=?",cid,oid);if("return".equals(action))workflow.returnParcel(uid,cid,data);else workflow.receiveReplacement(uid,cid);}else if("repay".equals(action))credit.repayAssisted(oid,data,who);else throw new IllegalArgumentException("不支持的代办操作");s.jdbc().update("insert into shop_assistance_request(actor,request_key,payload_hash,order_id) values(?,?,?,?)",who,key,hash,oid);s.event("order",oid,"客服代办 "+action+"，原客户 #"+uid+"，受理依据："+reason,who);return AjaxResult.success();}

@PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:customer,shop:finance')") @PostMapping("/after-sale") @Transactional public AjaxResult extend(@RequestBody JSONObject b){String no=str(b.get("orderNo")).trim(),reason=str(b.get("reason")).trim();long days=integer(b.get("days"),1,30,"开放期限为1至30天");check(reason.length()>=2&&reason.length()<=300,"请填写核实后的受理依据");Map<String,Object> o=s.one("select id,status from shop_order where order_no=? for update",no);check(Arrays.asList("paid","shipping","shipped","completed").contains(o.get("status")),"该订单当前不能开放售后");s.jdbc().update("update shop_order set manual_after_sale_until=date_add(now(),interval ? day) where id=?",days,o.get("id"));s.event("order",number(o.get("id")),"人工重新开放售后"+days+"天："+reason,SecurityUtils.getUsername());return AjaxResult.success();}
@PreAuthorize("@ss.hasPermi('shop:manage')") @GetMapping("/logs") public AjaxResult logs(@RequestParam(defaultValue="business")String kind,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="")String search){check(Arrays.asList("business","login","security").contains(kind)&&page>=1&&page<=100000&&search.length()<=100,"查询条件不正确");String table="business".equals(kind)?"shop_event":"login".equals(kind)?"sys_logininfor":"sys_oper_log",field="business".equals(kind)?"operator_name":"login".equals(kind)?"user_name":"oper_name",id="business".equals(kind)?"id":"login".equals(kind)?"info_id":"oper_id",fields="business".equals(kind)?"created_at time,operator_name actor,object_type category,object_id reference,action description":"login".equals(kind)?"login_time time,user_name actor,'登录' category,status result,msg description":"oper_time time,oper_name actor,title category,status result,request_method method";JSONObject out=new JSONObject();out.put("total",s.jdbc().queryForObject("select count(*) from "+table+" where "+field+" like ?",Long.class,"%"+search+"%"));out.put("rows",s.jdbc().queryForList("select "+fields+" from "+table+" where "+field+" like ? order by "+id+" desc limit 50 offset ?","%"+search+"%",(page-1)*50));return AjaxResult.success(out);}
}