package com.ruoyi.web.controller.shop;
import static com.ruoyi.web.controller.shop.ShopService.*;
import com.alibaba.fastjson2.JSONObject;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.prepost.PreAuthorize;import com.ruoyi.common.core.domain.AjaxResult;import com.ruoyi.common.utils.SecurityUtils;
@RestController public class ShopWarehouseController {
 @Autowired ShopWarehouse w;@Autowired ShopService s;
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse,shop:catalog,shop:finance')") @GetMapping("/shop/admin/warehouses") public AjaxResult list(){JSONObject r=new JSONObject();r.put("warehouses",s.jdbc().queryForList("select * from shop_warehouse order by priority,id"));r.put("stocks",w.stocks());r.put("movements",s.jdbc().queryForList("select m.*,w.name warehouse_name,p.name product_name from shop_warehouse_movement m join shop_warehouse w on w.id=m.warehouse_id join shop_product p on p.id=m.product_id order by m.id desc"));r.put("returns",s.jdbc().queryForList("select r.*,p.name,w.name warehouse_name from shop_warehouse_return r join shop_product p on p.id=r.product_id join shop_warehouse w on w.id=r.warehouse_id order by r.case_id desc"));return AjaxResult.success(r);}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse,shop:finance')") @GetMapping("/shop/admin/warehouses/order") public AjaxResult find(@RequestParam String number){java.util.Map<String,Object> o=s.one("select id,order_no from shop_order where order_no=?",number.trim());o.put("allocations",w.allocations(ShopService.number(o.get("id"))));return AjaxResult.success(o);}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse')") @PostMapping("/shop/admin/warehouses") public AjaxResult save(@RequestBody JSONObject b){w.warehouse(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse')") @PostMapping("/shop/admin/warehouses/transfer") public AjaxResult transfer(@RequestBody JSONObject b){w.transfer(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse')") @PostMapping("/shop/admin/warehouses/adjust") public AjaxResult adjust(@RequestBody JSONObject b){w.adjust(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse,shop:finance')") @GetMapping("/shop/admin/orders/{id}/warehouses") public AjaxResult order(@PathVariable long id){return AjaxResult.success(w.allocations(id));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse')") @PostMapping("/shop/admin/orders/{id}/warehouses") public AjaxResult reassign(@PathVariable long id,@RequestBody JSONObject b){w.reassign(id,b,SecurityUtils.getUsername());return AjaxResult.success();}

 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse')") @PostMapping("/shop/admin/warehouses/batch") public AjaxResult batch(@RequestBody JSONObject b){w.batch(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse')") @PostMapping("/shop/admin/warehouses/warning") public AjaxResult warning(@RequestBody JSONObject b){w.warning(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse')") @PostMapping("/shop/admin/warehouses/damaged") public AjaxResult damaged(@RequestBody JSONObject b){w.damaged(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:warehouse,shop:finance')") @GetMapping("/shop/admin/warehouses/export") public org.springframework.http.ResponseEntity<byte[]> export(@RequestParam String from,@RequestParam String to,@RequestParam(defaultValue="")String channel,@RequestParam(defaultValue="")String search)throws java.io.IOException{check(java.util.Arrays.asList("","C","B").contains(channel),"请选择库存渠道");java.time.LocalDate a=java.time.LocalDate.parse(from),b=java.time.LocalDate.parse(to);check(!b.isBefore(a)&&b.isBefore(a.plusDays(367)),"导出日期范围最多一年");try(org.apache.poi.xssf.usermodel.XSSFWorkbook book=new org.apache.poi.xssf.usermodel.XSSFWorkbook();java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream()){org.apache.poi.ss.usermodel.Sheet sheet=book.createSheet("库存流水");String[] fields={"created_at","warehouse_name","product_name","channel","quantity","reference_key","note","operator_name"},titles={"时间","仓库","商品","渠道","数量","关联单据","动作及依据","操作人"};org.apache.poi.ss.usermodel.Row head=sheet.createRow(0);for(int i=0;i<fields.length;i++){head.createCell(i).setCellValue(titles[i]);sheet.setColumnWidth(i,26*256);}int row=1;for(java.util.Map<String,Object> m:s.jdbc().queryForList("select m.*,w.name warehouse_name,p.name product_name from shop_warehouse_movement m join shop_warehouse w on w.id=m.warehouse_id join shop_product p on p.id=m.product_id where m.created_at>=? and m.created_at<? and (?='' or m.channel=?) and (?='' or locate(?,concat_ws(' ',p.name,w.name,m.note,m.operator_name,m.reference_key))>0) order by m.id",a.toString(),b.plusDays(1).toString(),channel,channel,search.trim(),search.trim())){org.apache.poi.ss.usermodel.Row line=sheet.createRow(row++);for(int i=0;i<fields.length;i++){Object value=m.get(fields[i]);if(value instanceof Number)line.createCell(i).setCellValue(((Number)value).doubleValue());else line.createCell(i).setCellValue(str(value));}}sheet.createFreezePane(0,1);book.write(out);return org.springframework.http.ResponseEntity.ok().header("Content-Disposition","attachment; filename=stock.xlsx").contentType(org.springframework.http.MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")).body(out.toByteArray());}}
}
