package com.ruoyi.web.controller.shop;
import java.util.*;import java.sql.Timestamp;import com.alibaba.fastjson2.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.context.annotation.Lazy;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopReviews {
 @Autowired @Lazy ShopService s;
 public JSONObject settings(){return JSON.parseObject(str(s.one("select content from shop_config where config_key='reviews'").get("content")));}
 @Transactional public void settings(JSONObject b,String who){JSONObject r=new JSONObject();r.put("reviewDays",integer(b.get("reviewDays"),1,365,"主评期限为1至365天"));r.put("followupDays",integer(b.get("followupDays"),1,730,"追评期限为1至730天"));s.jdbc().update("update shop_config set content=? where config_key='reviews'",r.toJSONString());s.event("reviews",0,"调整新收货商品的评价期限",who);}
 public void received(long oid){long days=settings().getLongValue("reviewDays");Map<String,Object> o=s.one("select received_at from shop_order where id=?",oid);List<Map<String,Object>> parcels=s.jdbc().queryForList("select received_at,items_json from shop_shipment where order_id=? and received=1 and received_at is not null",oid);for(Map<String,Object> line:s.jdbc().queryForList("select id from shop_order_item where order_id=? and review_until is null",oid)){Timestamp date=o.get("received_at")==null?null:timestamp(o.get("received_at"));for(Map<String,Object> parcel:parcels){JSONArray items=JSON.parseArray(str(parcel.get("items_json")));for(Object obj:items){JSONObject item=JSON.parseObject(JSON.toJSONString(obj));if(item.getLongValue("id")==number(line.get("id"))){Timestamp at=timestamp(parcel.get("received_at"));if(date==null||at.before(date))date=at;}}}if(date!=null)s.jdbc().update("update shop_order_item set review_until=date_add(?,interval ? day) where id=? and review_until is null",date,days,line.get("id"));}}
 public Map<String,Object> mine(long uid){Map<String,Object> r=new HashMap<>();r.put("eligible",s.jdbc().queryForList("select i.id,i.name,i.spec,i.image,i.review_until,o.order_no from shop_order_item i join shop_order o on o.id=i.order_id where o.member_id=? and i.review_until>=now() and not exists(select 1 from shop_review r where r.order_item_id=i.id) order by i.id desc",uid));r.put("reviews",s.jdbc().queryForList("select r.*,i.name,i.spec from shop_review r join shop_order_item i on i.id=r.order_item_id where r.member_id=? order by r.id desc",uid));return r;}
 public Map<String,Object> product(long pid,int page){check(page>=1&&page<=10000,"页码不正确");String visible=" where r.product_id=? and r.visible=1"+s.verifiedPayment("r.order_id");Map<String,Object> r=new HashMap<>();r.put("total",s.jdbc().queryForObject("select count(*) from shop_review r"+visible,Long.class,pid));r.put("rows",s.jdbc().queryForList("select r.id,r.stars,r.body,r.followup,r.followup_at,r.reply,r.created_at,r.images_json,r.anonymous,case when r.anonymous=1 then '匿名买家' else m.nickname end nickname,i.spec from shop_review r join shop_member m on m.id=r.member_id join shop_order_item i on i.id=r.order_item_id"+visible+" order by r.id desc limit 20 offset ?",pid,(page-1)*20));return r;}
 private JSONArray images(long uid,JSONObject b){JSONArray images=b.getJSONArray("images");if(images==null)images=new JSONArray();check(images.size()<=6,"评价最多附6张图片");Set<String> seen=new HashSet<>();for(Object path:images)check(seen.add(str(path))&&s.jdbc().queryForObject("select count(*) from shop_public_file where path=? and member_id=?",Long.class,str(path),uid)>0,"评价图片应为自己上传且不重复的图片");return images;}
 private String body(Object v){String text=str(v).trim();check(text.length()>=2&&text.length()<=1500,"评价请填写2至1500字");return text;}
 @Transactional public void post(long uid,JSONObject b){long id=integer(b.get("itemId"),1,Long.MAX_VALUE,"请选择已收到的商品");Map<String,Object> first=s.one("select order_id from shop_order_item where id=?",id);s.one("select id from shop_order where id=? and member_id=? for update",first.get("order_id"),uid);Map<String,Object> line=s.one("select * from shop_order_item where id=? for update",id);String text=body(b.get("body"));JSONArray photos=images(uid,b);boolean anonymous=b.getBooleanValue("anonymous");long stars=integer(b.get("stars"),1,5,"请给出1至5星评分");List<Map<String,Object>> existing=s.jdbc().queryForList("select * from shop_review where order_item_id=?",id);if(!existing.isEmpty()){Map<String,Object> old=existing.get(0);check(text.equals(old.get("body"))&&number(old.get("stars"))==stars&&anonymous==(number(old.get("anonymous"))==1)&&photos.toJSONString().equals(str(old.get("images_json")).isEmpty()?"[]":str(old.get("images_json"))),"此商品已经评价，原评价不能覆盖修改，可在期限内追评");return;}check(line.get("review_until")!=null&&timestamp(line.get("review_until")).getTime()>=System.currentTimeMillis(),"商品尚未确认收货或已超过评价期限");s.jdbc().update("insert into shop_review(order_item_id,order_id,member_id,product_id,stars,body,followup_until) values(?,?,?,?,?,?,date_add(now(),interval ? day))",id,first.get("order_id"),uid,line.get("product_id"),stars,text,settings().getLongValue("followupDays"));s.jdbc().update("update shop_review set anonymous=?,images_json=? where order_item_id=?",anonymous,photos.toJSONString(),id);s.event("review",id,"买家发布评价",str(uid));}
 @Transactional public void followup(long uid,long id,JSONObject b){Map<String,Object> r=s.one("select * from shop_review where id=? and member_id=? for update",id,uid);String text=body(b.get("body"));if(r.get("followup")!=null){check(text.equals(r.get("followup")),"已发布追评，不能覆盖买家原文");return;}check(timestamp(r.get("followup_until")).getTime()>=System.currentTimeMillis(),"已超过追评期限");s.jdbc().update("update shop_review set followup=?,followup_at=now() where id=?",text,id);s.event("review",id,"买家追加评价",str(uid));}
 public List<Map<String,Object>> admin(){return s.jdbc().queryForList("select (select qo.channel from shop_order qo where qo.id=r.order_id) channel,r.*,m.nickname,i.name,i.spec"+ShopQueryFields.fields("m.id")+" from shop_review r join shop_member m on m.id=r.member_id join shop_order_item i on i.id=r.order_item_id where 1=1"+s.officialOrder("r.order_id")+" order by r.id desc");}
 @Transactional public void moderate(long id,JSONObject b,String who){s.one("select id from shop_review where id=? for update",id);String action=b.getString("action"),note=str(b.get("note")).trim();if("reply".equals(action)){check(note.length()>=2&&note.length()<=1000,"回复请填写2至1000字");s.jdbc().update("update shop_review set reply=? where id=?",note,id);}else{check(Arrays.asList("hide","show").contains(action)&&note.length()>=2&&note.length()<=500,"请填写显示或隐藏依据");s.jdbc().update("update shop_review set visible=?,moderation_note=? where id=?","show".equals(action),note,id);}s.event("review",id,action+"："+note,who);}
}
