package com.ruoyi.web.controller.shop;
import java.util.*;
import javax.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.transaction.annotation.Transactional;
import com.alibaba.fastjson2.JSONObject;
import com.ruoyi.common.core.domain.AjaxResult;
import com.ruoyi.common.core.domain.model.LoginUser;
import com.ruoyi.common.core.redis.RedisCache;
import com.ruoyi.common.constant.CacheConstants;
import com.ruoyi.common.utils.SecurityUtils;
import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController @RequestMapping("/shop/admin/staff") @PreAuthorize("@ss.hasPermi('shop:manage')")
public class ShopStaffController {
 @Autowired ShopService s; @Autowired RedisCache cache;
 private static final Map<String,String> ROLES=new LinkedHashMap<>();static{ROLES.put("catalog","商品运营");ROLES.put("warehouse","仓库发货");ROLES.put("customer","客服认证");ROLES.put("finance","财务售后");ROLES.put("content","内容运营");}
 @PostConstruct public void init(){List<Map<String,Object>> menus=s.jdbc().queryForList("select menu_id from sys_menu where component='shop/index'");if(menus.isEmpty()){s.jdbc().update("insert into sys_menu(menu_name,parent_id,path,component,menu_type,perms,visible,status) values('商城管理',0,'shop','shop/index','C','shop:access','0','0')");menus=s.jdbc().queryForList("select menu_id from sys_menu where component='shop/index'");}long parent=number(menus.get(0).get("menu_id"));s.jdbc().update("update sys_menu set perms='shop:access' where menu_id=? and perms='shop:manage'",parent);
 for(Map.Entry<String,String> role:ROLES.entrySet()){String key="shop_"+role.getKey(),permission="shop:"+role.getKey();if(s.jdbc().queryForObject("select count(*) from sys_role where role_key=?",Long.class,key)>0)continue;s.jdbc().update("insert into sys_role(role_name,role_key,role_sort,status,create_by,create_time) values(?,?,10,'0','shop',now())",role.getValue(),key);long rid=number(s.one("select role_id from sys_role where role_key=?",key).get("role_id"));List<Map<String,Object>> p=s.jdbc().queryForList("select menu_id from sys_menu where perms=?",permission);if(p.isEmpty()){s.jdbc().update("insert into sys_menu(menu_name,parent_id,menu_type,perms,visible,status) values(?,?,'F',?,'0','0')",role.getValue(),parent,permission);p=s.jdbc().queryForList("select menu_id from sys_menu where perms=?",permission);}s.jdbc().update("insert ignore into sys_role_menu values(?,?)",rid,parent);s.jdbc().update("insert ignore into sys_role_menu values(?,?)",rid,p.get(0).get("menu_id"));}
 }
 @GetMapping public AjaxResult list(){return AjaxResult.success(s.jdbc().queryForList("select u.user_id id,u.user_name username,u.nick_name name,u.status,r.role_key from sys_user u join sys_user_role ur on ur.user_id=u.user_id join sys_role r on r.role_id=ur.role_id where r.role_key in ('shop_catalog','shop_warehouse','shop_customer','shop_finance','shop_content') and u.del_flag='0' order by u.user_id"));}
 @PostMapping @Transactional public AjaxResult save(@RequestBody JSONObject b){String role=str(b.get("role"));check(ROLES.containsKey(role),"请选择岗位");long rid=number(s.one("select role_id from sys_role where role_key=? and status='0'","shop_"+role).get("role_id"));long id=b.getLongValue("id");String pwd=str(b.get("password"));if(id==0||!pwd.isEmpty())check(pwd.length()>=12&&pwd.length()<=20&&pwd.getBytes(java.nio.charset.StandardCharsets.UTF_8).length<=72,"员工密码需12至20位");String name=str(b.get("name")).trim();check(name.length()>=2&&name.length()<=30,"请填写2至30字员工姓名");if(id==0){String username=str(b.get("username")).trim();check(username.matches("[a-zA-Z0-9_]{3,20}"),"账号需3至20位字母数字或下划线");check(s.jdbc().queryForObject("select count(*) from sys_user where user_name=?",Long.class,username)==0,"账号已存在");s.jdbc().update("insert into sys_user(user_name,nick_name,password,status,create_by,create_time) values(?,?,?,'0',?,now())",username,name,SecurityUtils.encryptPassword(pwd),SecurityUtils.getUsername());id=number(s.one("select user_id from sys_user where user_name=?",username).get("user_id"));}else{check(id!=1&&id!=SecurityUtils.getUserId(),"不能修改管理员或本人");s.one("select user_id from sys_user where user_id=? for update",id);List<Map<String,Object>> old=s.jdbc().queryForList("select r.role_key from sys_role r join sys_user_role ur on ur.role_id=r.role_id where ur.user_id=?",id);check(old.size()==1&&ROLES.containsKey(str(old.get(0).get("role_key")).replaceFirst("^shop_","")),"仅可修改商城员工账号");s.jdbc().update("update sys_user set nick_name=?,status=? where user_id=?",name,b.getBooleanValue("disabled")?"1":"0",id);if(!pwd.isEmpty())s.jdbc().update("update sys_user set password=?,pwd_update_date=now() where user_id=?",SecurityUtils.encryptPassword(pwd),id);s.jdbc().update("delete from sys_user_role where user_id=?",id);}
 s.jdbc().update("insert into sys_user_role values(?,?)",id,rid);for(String key:cache.keys(CacheConstants.LOGIN_TOKEN_KEY+"*")){LoginUser login=cache.getCacheObject(key);if(login!=null&&Objects.equals(login.getUserId(),id))cache.deleteObject(key);}s.event("staff",id,"更新员工岗位或账号并撤销会话",SecurityUtils.getUsername());return AjaxResult.success();}
}
