package com.ruoyi.web.controller.shop;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import com.alibaba.fastjson2.JSONObject;
import com.ruoyi.common.utils.SecurityUtils;
import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopAccounts {
 @Autowired ShopService s;
 private final Map<String,long[]> attempts=new ConcurrentHashMap<>();
 public synchronized void rate(String ip,String name){long now=System.currentTimeMillis();attempts.entrySet().removeIf(e->now-e.getValue()[0]>600000);String key=ip+":"+name.toLowerCase(Locale.ROOT);long[] count=attempts.computeIfAbsent(key,k->new long[]{now,0});check(++count[1]<=30,"操作过于频繁，请稍后再试");check(attempts.size()<10000,"请求繁忙，请稍后重试");}
 private String username(JSONObject b){String name=str(b.get("username")).trim().toLowerCase(Locale.ROOT);check(name.matches("[a-z0-9_]{3,40}"),"账号为3至40位字母、数字或下划线");return name;}
 private String passwordValue(JSONObject b){String p=str(b.get("password"));check(p.length()>=8&&p.length()<=64&&p.getBytes(java.nio.charset.StandardCharsets.UTF_8).length<=72,"密码需8至64位，不能超过72字节");return p;}
 @Transactional public Map<String,Object> register(JSONObject b){String name=username(b),password=passwordValue(b);check(b.getBooleanValue("agreed"),"请阅读并同意协议");check(s.jdbc().queryForObject("select count(*) from shop_credentials where username=?",Long.class,name)==0,"账号已注册，请登录");Map<String,Object> auth=s.login("account:"+name,"account",null,referral(b.get("referrer")));long uid=number(((Map<?,?>)auth.get("member")).get("id"));s.jdbc().update("insert into shop_credentials values(?,?,?,now())",name,uid,SecurityUtils.encryptPassword(password));s.jdbc().update("update shop_member set nickname=?,is_test=? where id=?",name,s.testData,uid);((Map<String,Object>)auth.get("member")).put("nickname",name);return auth;}
 @Transactional public Map<String,Object> login(JSONObject b){String name=username(b),password=passwordValue(b);List<Map<String,Object>> list=s.jdbc().queryForList("select member_id from shop_credentials where username=?",name);check(!list.isEmpty(),"账号或密码错误");long uid=number(list.get(0).get("member_id"));s.one("select id from shop_member where id=? for update",uid);Map<String,Object> current=s.one("select password_hash from shop_credentials where member_id=? for update",uid);check(SecurityUtils.matchesPassword(password,str(current.get("password_hash"))),"账号或密码错误");return s.login("account:"+name,"account",null,null);}
 public Map<String,Object> profile(long uid){List<Map<String,Object>> list=s.jdbc().queryForList("select username from shop_credentials where member_id=?",uid);Map<String,Object> out=new HashMap<>();out.put("hasPassword",!list.isEmpty());out.put("username",list.isEmpty()?"":list.get(0).get("username"));return out;}
 @Transactional public void password(long uid,JSONObject b){s.one("select id from shop_member where id=? for update",uid);String name=username(b),password=passwordValue(b);List<Map<String,Object>> old=s.jdbc().queryForList("select * from shop_credentials where member_id=?",uid);if(!old.isEmpty()){check(name.equals(old.get(0).get("username")),"账号名称不能修改");check(SecurityUtils.matchesPassword(str(b.get("oldPassword")),str(old.get(0).get("password_hash"))),"原密码不正确");s.jdbc().update("update shop_credentials set password_hash=? where member_id=?",SecurityUtils.encryptPassword(password),uid);}else{check(s.jdbc().queryForObject("select count(*) from shop_credentials where username=?",Long.class,name)==0,"该账号名称已被使用");s.bindIdentity(uid,"account:"+name,null);s.jdbc().update("insert into shop_credentials values(?,?,?,now())",name,uid,SecurityUtils.encryptPassword(password));}s.jdbc().update("delete from shop_session where member_id=?",uid);s.event("member",uid,"更新独立登录密码并撤销会话",str(uid));}
 @Transactional public Map<String,Object> recovery(long uid,JSONObject b){s.one("select id from shop_member where id=? for update",uid);Map<String,Object> c=s.one("select password_hash from shop_credentials where member_id=? for update",uid);check(SecurityUtils.matchesPassword(str(b.get("oldPassword")),str(c.get("password_hash"))),"当前密码不正确");byte[] bytes=new byte[24];new java.security.SecureRandom().nextBytes(bytes);String code=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);s.jdbc().update("insert into shop_recovery(member_id,code_hash) values(?,?) on duplicate key update code_hash=values(code_hash),created_at=now()",uid,s.hash(code));s.event("member",uid,"重新生成账号恢复码",str(uid));Map<String,Object> out=new HashMap<>();out.put("recoveryCode",code);return out;}
 @Transactional public void recover(JSONObject b){String name=username(b),password=passwordValue(b);List<Map<String,Object>> users=s.jdbc().queryForList("select member_id from shop_credentials where username=?",name);check(!users.isEmpty(),"账号或恢复码不正确");long uid=number(users.get(0).get("member_id"));Map<String,Object> member=s.one("select enabled from shop_member where id=? for update",uid);check(Boolean.TRUE.equals(member.get("enabled"))||"1".equals(str(member.get("enabled"))),"账号已停用，请联系管理员");List<Map<String,Object>> codes=s.jdbc().queryForList("select code_hash from shop_recovery where member_id=? for update",uid);String code=str(b.get("recoveryCode")).trim();check(code.length()==32&&!codes.isEmpty()&&java.security.MessageDigest.isEqual(s.hash(code).getBytes(java.nio.charset.StandardCharsets.UTF_8),str(codes.get(0).get("code_hash")).getBytes(java.nio.charset.StandardCharsets.UTF_8)),"账号或恢复码不正确");s.jdbc().update("update shop_credentials set password_hash=? where member_id=?",SecurityUtils.encryptPassword(password),uid);s.jdbc().update("delete from shop_recovery where member_id=?",uid);s.jdbc().update("delete from shop_session where member_id=?",uid);s.event("member",uid,"恢复码重置密码并撤销会话",str(uid));}
}
