package com.ruoyi.web.controller.shop;
import java.util.*;import javax.servlet.http.HttpServletRequest;import com.alibaba.fastjson2.JSONObject;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.prepost.PreAuthorize;import com.ruoyi.common.annotation.Anonymous;import com.ruoyi.common.core.domain.AjaxResult;import com.ruoyi.common.utils.SecurityUtils;import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController public class ShopGradeController {
 @Autowired ShopService s;@Autowired ShopGrades g;
 @Anonymous @GetMapping("/shop/app/grades") public AjaxResult own(HttpServletRequest r){return AjaxResult.success(g.summary(number(s.member(r.getHeader("X-Shop-Token")).get("id"))));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:catalog')") @GetMapping("/shop/admin/grades") public AjaxResult admin(){JSONObject r=new JSONObject();r.put("settings",g.settings());r.put("products",s.jdbc().queryForList("select id,name,spec,pack from shop_product order by id"));r.put("members",s.jdbc().queryForList("select m.id,m.nickname,coalesce(g.tier,0) tier"+ShopQueryFields.fields("m.id")+" from shop_member m left join shop_grade g on g.owner_id=m.id and g.scope='C' order by m.id desc"));r.put("companies",s.jdbc().queryForList("select c.id,c.name,coalesce(g.tier,0) tier from shop_company c left join shop_grade g on g.owner_id=c.id and g.scope='B'"));r.put("gradePrices",s.jdbc().queryForList("select * from shop_grade_price"));r.put("companyPrices",s.jdbc().queryForList("select * from shop_company_price"));r.put("quantities",s.jdbc().queryForList("select * from shop_purchase_rule"));return AjaxResult.success(r);}
 @PreAuthorize("@ss.hasPermi('shop:manage')") @PostMapping("/shop/admin/grades") public AjaxResult save(@RequestBody JSONObject b){g.save(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasPermi('shop:manage')") @PostMapping("/shop/admin/grades/assign") public AjaxResult assign(@RequestBody JSONObject b){g.assign(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:catalog')") @PostMapping("/shop/admin/grades/pricing") public AjaxResult pricing(@RequestBody JSONObject b){g.pricing(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasPermi('shop:manage')") @PostMapping("/shop/admin/grades/recalculate") public AjaxResult recalculate(){g.recalculate(SecurityUtils.getUsername());return AjaxResult.success();}
}
