package com.ruoyi.web.controller.shop;
import java.util.*;import com.alibaba.fastjson2.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.context.annotation.Lazy;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopNotices {
 @Autowired @Lazy ShopService s;
 public JSONObject preferences(long uid){List<Map<String,Object>> rows=s.jdbc().queryForList("select content from shop_notice_preference where member_id=?",uid);JSONObject p=rows.isEmpty()?new JSONObject():JSON.parseObject(str(rows.get(0).get("content")));for(String k:Arrays.asList("order","approval","finance","service"))if(!p.containsKey(k))p.put(k,true);if(!p.containsKey("marketing"))p.put("marketing",false);return p;}
 @Transactional public void preferences(long uid,JSONObject b){JSONObject p=new JSONObject();for(String k:Arrays.asList("order","approval","finance","service","marketing"))p.put(k,b.getBooleanValue(k));s.jdbc().update("insert into shop_notice_preference(member_id,content) values(?,?) on duplicate key update content=values(content)",uid,p.toJSONString());}
 public Map<String,Object> list(long uid,int page){check(page>=1&&page<=10000,"页码不正确");Map<String,Object> r=new HashMap<>();r.put("rows",s.jdbc().queryForList("select * from shop_notice where member_id=? order by id desc limit 30 offset ?",uid,(page-1)*30));r.put("unread",s.jdbc().queryForObject("select count(*) from shop_notice where member_id=? and read_at is null",Long.class,uid));r.put("preferences",preferences(uid));return r;}
 public void read(long uid,long id){check(s.jdbc().queryForObject("select count(*) from shop_notice where member_id=? and id=?",Long.class,uid,id)==1,"消息不属于当前账号");s.jdbc().update("update shop_notice set read_at=coalesce(read_at,now()) where member_id=? and id=?",uid,id);}
 public void readAll(long uid){s.jdbc().update("update shop_notice set read_at=coalesce(read_at,now()) where member_id=? and read_at is null",uid);}
 public void add(long uid,String key,String category,String title,String body,String screen,long target){if(!preferences(uid).getBooleanValue(category))return;s.jdbc().update("insert ignore into shop_notice(member_id,event_key,category,title,body,target_screen,target_id) values(?,?,?,?,?,?,?)",uid,key+":"+uid,category,title,body,screen,target);}
 private void orderRecipients(Set<Long> users,long oid){List<Map<String,Object>> rows=s.jdbc().queryForList("select * from shop_order where id=?",oid);if(rows.isEmpty())return;Map<String,Object> o=rows.get(0);if(o.get("company_id")==null){users.add(number(o.get("member_id")));return;}for(Map<String,Object> m:s.jdbc().queryForList("select member_id,role from shop_company_member where company_id=? and enabled=1",o.get("company_id")))if(Arrays.asList("owner","finance").contains(str(m.get("role")))||number(m.get("member_id"))==number(o.get("member_id")))users.add(number(m.get("member_id")));}
 @Transactional public void process(long eventId){Map<String,Object> pending=s.one("select processed_at from shop_notice_outbox where event_id=? for update",eventId);if(pending.get("processed_at")!=null)return;Map<String,Object> e=s.one("select * from shop_event where id=?",eventId);String type=str(e.get("object_type")),action=str(e.get("action")),category="order",title="业务进度更新",body="处理结果已更新，请进入查看详情。",screen="orders";long id=number(e.get("object_id")),target=0;Set<Long> users=new HashSet<>();
 if("order".equals(type)){orderRecipients(users,id);screen="order-detail";target=id;title="订单进度更新";body="订单的付款、履约或售后进度有更新，请查看详情。";}
 else if("enterprise".equals(type)||"distributor".equals(type)){users.add(id);category="approval";title="enterprise".equals(type)?"企业认证进度":"分销申请进度";screen="enterprise".equals(type)?"business":"distribution";body="approved".equals(action)?"申请已通过，请进入查看可使用的权益。":"rejected".equals(action)?"申请未通过，请查看原因并修改资料。":"申请进度已更新，请进入查看。";}
 else if("case".equals(type)||"afterSale".equals(type)){String table="case".equals(type)?"shop_case":"shop_after_sale";List<Map<String,Object>> rows=s.jdbc().queryForList("select order_id,status,note from "+table+" where id=?",id);if(!rows.isEmpty()){Map<String,Object> r=rows.get(0);long oid=number(r.get("order_id"));orderRecipients(users,oid);title="售后处理更新";body="售后状态："+state(str(r.get("status")))+"。"+str(r.get("note"));screen="order-detail";target=oid;}}
 else if("withdrawal".equals(type)){List<Map<String,Object>> rows=s.jdbc().queryForList("select member_id,status,note from shop_withdrawal where id=?",id);if(!rows.isEmpty()){Map<String,Object> r=rows.get(0);users.add(number(r.get("member_id")));category="finance";title="提现处理更新";body="paid".equals(r.get("status"))?"打款处理记录已更新，请查看明细；实际到账以收款账户为准。":"提现处理结果已更新："+str(r.get("note"));screen="withdrawals";}}
 else if("invoice".equals(type)){List<Map<String,Object>> rows=s.jdbc().queryForList("select order_id from shop_invoice where id=?",id);if(!rows.isEmpty())orderRecipients(users,number(rows.get(0).get("order_id")));category="finance";title="发票处理更新";screen="invoices";body="票据处理有更新，请查看文件或需要修改的资料。";}
 else if("procurement".equals(type)){List<Map<String,Object>> drafts=s.jdbc().queryForList("select company_id,member_id,note,order_id from shop_procurement_draft where id=?",id);if(!drafts.isEmpty()){Map<String,Object> d=drafts.get(0);for(Map<String,Object> m:s.jdbc().queryForList("select member_id from shop_company_member where company_id=? and enabled=1 and (role='owner' or member_id=?)",d.get("company_id"),d.get("member_id")))users.add(number(m.get("member_id")));category="approval";title="采购审批进度";screen="company";target=id;body="approved".equals(action)?"采购申请已通过，请确认最新价格后生成订单。":"rejected".equals(action)?"采购申请已退回："+str(d.get("note")):"ordered".equals(action)?"采购申请已生成订单，请进入订单查看付款与履约进度。":"新的采购申请已提交，等待负责人审批。";if("ordered".equals(action)&&d.get("order_id")!=null){screen="order-detail";target=number(d.get("order_id"));orderRecipients(users,target);}}}
 else if(Arrays.asList("company","credit","statement").contains(type)){for(Map<String,Object> m:s.jdbc().queryForList("select member_id from shop_company_member where company_id=? and enabled=1 and role in ('owner','finance')",id))users.add(number(m.get("member_id")));category="finance";title="credit".equals(type)?"企业额度与还款更新":"statement".equals(type)?"企业对账更新":"企业管理更新";screen="credit".equals(type)?"company-credit":"statement".equals(type)?"company-statement":"company";}
 if(body.length()>1500)body=body.substring(0,1500);for(Long uid:users)add(uid,"event_"+eventId,category,title,body,screen,target);s.jdbc().update("update shop_notice_outbox set processed_at=now() where event_id=?",eventId);
 }
 private String state(String v){switch(v){case "pending":return "待审核";case "awaiting_refund":return "等待财务退款";case "refunded":return "退款已处理";case "rejected":return "已退回";case "awaiting_return":return "等待寄回商品";case "returned":return "等待商家验收";case "awaiting_reship":return "等待换货或补发";case "reshipped":return "换补发已寄出";case "completed":return "已完成";default:return "已更新";}}
}
