package com.ruoyi.web.controller.shop;
import java.util.*;import java.sql.Timestamp;import com.alibaba.fastjson2.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.context.annotation.Lazy;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopMarketing {
 @Autowired @Lazy ShopService s;@Autowired ShopGrades grades;@Autowired ShopCompany company;@Autowired ShopWarehouse warehouse;@Autowired @Lazy ShopWorkflow workflow;
 private JSONObject obj(Object x){return JSON.parseObject(JSON.toJSONString(x));}
 private JSONObject config(Map<String,Object> c){return JSON.parseObject(str(c.get("config_json")));}
 private boolean stocked(String kind){return Arrays.asList("flash","group","combo","gift").contains(kind);}
 private void stockLog(long pid,long delta,String key,String note,String who){s.jdbc().update("update shop_product set stock=stock+?,version=version+1 where id=?",delta,pid);s.jdbc().update("insert into shop_stock_log(product_id,delta,balance,request_key,note,operator_name) select id,?,stock,?,?,? from shop_product where id=?",delta,key,note,who,pid);}
 private void movement(long wid,long pid,String channel,long qty,String key,String who){s.jdbc().update("insert into shop_warehouse_movement(warehouse_id,product_id,channel,kind,quantity,reference_key,note,operator_name) values(?,?,?,'campaign',?,?,?,?)",wid,pid,channel,qty,key,"活动预留与订单库存转换",who);}
 public long held(long campaign,long pid){if(campaign<=0)return 0;return s.jdbc().queryForObject("select coalesce(sum(p.held),0) from shop_campaign_pool p join shop_warehouse w on w.id=p.warehouse_id where p.campaign_id=? and p.product_id=? and w.enabled=1",Long.class,campaign,pid);}
 public List<Map<String,Object>> list(boolean admin,String channel){List<Map<String,Object>> rows=s.jdbc().queryForList("select * from shop_campaign "+(admin?"":"where status='active' and ends_at>now() and channel=? ")+"order by id desc limit 200",admin?new Object[]{}:new Object[]{channel});Map<String,Object> tiers=gradeOptions();for(Map<String,Object> c:rows){int minimum=config(c).getIntValue("minimumTier");JSONArray names=(JSONArray)tiers.get(str(c.get("channel")));c.put("minimumTierName",names!=null&&minimum>=0&&minimum<names.size()?names.getString(minimum):"");c.put("pool",s.jdbc().queryForList("select product_id,sum(held) available from shop_campaign_pool where campaign_id=? group by product_id",c.get("id")));if("group".equals(c.get("kind")))c.put("groups",s.jdbc().queryForList("select g.id,g.required_people,g.expires_at,(select count(*) from shop_campaign_order o where o.group_id=g.id and o.state='paid') paid_people from shop_campaign_group g where g.campaign_id=? and g.status='open' and g.expires_at>now() order by g.id desc limit 30",c.get("id")));}return rows;}
 private List<Map<String,Object>> ordinary(String channel){return s.jdbc().queryForList("select * from shop_campaign where status='active' and starts_at<=now() and ends_at>now() and channel=? and kind in ('price','discount','gift') order by id",channel);}
 public Map<String,Object> gradeOptions(){JSONObject settings=grades.settings();Map<String,Object> result=new LinkedHashMap<>();result.put("C",settings.getJSONArray("names"));result.put("B",settings.getJSONArray("purchaseNames"));return result;}
 private void validateMinimumTier(String channel,JSONObject cfg){JSONArray names=(JSONArray)gradeOptions().get(channel);check(names!=null&&!names.isEmpty(),"请先配置当前渠道等级");integer(cfg.getOrDefault("minimumTier",0),0,names.size()-1,"请选择当前渠道有效的最低等级");}
 public boolean eligible(long uid,String channel,JSONObject cfg){
  long owner=uid;String scope="o.member_id=? and o.channel='C'";
  if("B".equals(channel)){Map<String,Object> c=company.context(uid);owner=number(c.get("id"));scope="o.company_id=? and o.channel='B'";}
  if(grades.tier(channel,owner)<cfg.getIntValue("minimumTier"))return false;
  if(!cfg.getBooleanValue("firstOnly"))return true;
  s.one("select id from "+("B".equals(channel)?"shop_company":"shop_member")+" where id=? for update",owner);
  // Pending orders reserve first-order eligibility; only verified historical payments consume it in formal mode.
  String source=s.isDemo()?"":" and o.is_test=0 and exists(select 1 from shop_member buyer where buyer.id=o.member_id and buyer.is_test=0) and not exists(select 1 from shop_payment simulated where simulated.order_id=o.id and simulated.mode='simulation')";
  String paid="o.paid_at is not null"+(s.isDemo()?"":" and exists(select 1 from shop_payment verified where verified.order_id=o.id and verified.mode<>'simulation')");
  return s.jdbc().queryForList("select o.id from shop_order o where "+scope+source+" and (("+paid+") or (o.status='pending' and (o.expires_at is null or o.expires_at>now()))) for update",owner).isEmpty();
 }
 public long price(long uid,long pid,long price,String channel){for(Map<String,Object> c:ordinary(channel)){if(!"price".equals(c.get("kind"))||!eligible(uid,channel,config(c)))continue;for(Object x:config(c).getJSONArray("items")){JSONObject i=obj(x);if(i.getLongValue("productId")==pid)price=Math.min(price,i.getLongValue("price"));}}return price;}
 public long apply(long uid,JSONObject b,List<JSONObject> lines,long subtotal,boolean lock,JSONObject rules){long cid=b.getLongValue("campaignId");if(cid>0){check(!b.getBooleanValue("exchange")&&!b.getBooleanValue("usePoints")&&b.getLongValue("couponId")==0&&!b.getBooleanValue("coupon"),"秒杀、拼团和组合购不叠加优惠券、满减或积分");Map<String,Object> c=s.one("select * from shop_campaign where id=?"+(lock?" for update":""),cid);String kind=str(c.get("kind"));check(!"group".equals(kind)||!"credit".equals(b.getString("paymentMethod")),"拼团请使用普通付款");check(Arrays.asList("flash","group","combo").contains(kind),"该活动不能单独下单");check("active".equals(c.get("status"))&&b.getString("channel").equals(c.get("channel"))&&timestamp(c.get("starts_at")).getTime()<=System.currentTimeMillis()&&timestamp(c.get("ends_at")).getTime()>System.currentTimeMillis(),"活动未开始或已结束");JSONObject cfg=config(c);check(eligible(uid,b.getString("channel"),cfg),"该活动仅限符合首单或等级条件的客户；未付款首单请先处理");JSONArray offers=cfg.getJSONArray("items");check(lines.size()==offers.size(),"请按活动商品清单下单");long bundles="combo".equals(kind)?integer(b.get("bundles"),1,10000,"请填写套装数量"):1,total=0;for(Object x:offers){JSONObject offer=obj(x),line=null;for(JSONObject l:lines)if(l.getLongValue("id")==offer.getLongValue("productId"))line=l;check(line!=null,"活动商品不匹配");long pid=line.getLongValue("id"),qty=line.getLongValue("quantity");if("combo".equals(kind))check(qty==offer.getLongValue("quantity")*bundles,"固定套装商品数量不一致");if("group".equals(kind))check(qty==1,"每位团员限购买一件");check(held(cid,pid)>=qty,"活动预留库存不足");long bought=0;for(Map<String,Object> prior:s.jdbc().queryForList("select items_json from shop_campaign_order where campaign_id=? and member_id=? and state<>'released'",cid,uid))for(Object y:JSON.parseArray(str(prior.get("items_json")))){JSONObject i=obj(y);if(i.getLongValue("id")==pid)bought+=i.getLongValue("quantity");}check(bought+qty<=cfg.getLongValue("limit")*("combo".equals(kind)?offer.getLongValue("quantity"):1),"已达到该活动限购数量，已付款退款不恢复名额");if(!"combo".equals(kind))line.put("unitPrice",offer.getLongValue("price"));total+=line.getLongValue("unitPrice")*qty;}
 long amount="combo".equals(kind)?cfg.getLongValue("bundlePrice")*bundles:total;check(amount<=total,"套装金额高于当前商品总额，请调整活动价");JSONObject snapshot=new JSONObject(c);snapshot.put("selectedGroup",b.getLongValue("groupId"));snapshot.put("bundles",bundles);rules.put("campaign",snapshot);rules.put("campaignDiscount",total-amount);return total;}
 if(!b.getBooleanValue("exchange")){for(JSONObject line:lines)if(!line.getBooleanValue("agreementPrice"))line.put("unitPrice",price(uid,line.getLongValue("id"),line.getLongValue("unitPrice"),b.getString("channel")));subtotal=0;for(JSONObject line:lines)subtotal+=line.getLongValue("unitPrice")*line.getLongValue("quantity");}return subtotal;}
 public long discount(long uid,JSONObject b,List<JSONObject> lines,long subtotal,long legacy,JSONObject rules){if(b.getLongValue("campaignId")>0)return 0;if(b.getBooleanValue("exchange"))return legacy;long best=legacy;for(Map<String,Object> c:ordinary(b.getString("channel"))){if(!"discount".equals(c.get("kind"))||!eligible(uid,b.getString("channel"),config(c)))continue;JSONObject cfg=config(c);long eligible=0;Set<Long> ids=new HashSet<>();for(Object x:cfg.getJSONArray("items"))ids.add(obj(x).getLongValue("productId"));for(JSONObject l:lines)if(ids.isEmpty()||ids.contains(l.getLongValue("id")))eligible+=l.getLongValue("unitPrice")*l.getLongValue("quantity");if(eligible<cfg.getLongValue("threshold"))continue;long amount=Math.max(cfg.getLongValue("reduction"),ShopCommerce.portion(eligible,10000-cfg.getLongValue("payRate"),10000));long chosen=Math.min(eligible,amount);if(chosen>best){best=chosen;rules.put("promotionProducts",new JSONArray(ids));}}return best;}
 public void gift(long uid,JSONObject b,Map<String,Object> q,boolean lock){if(b.getLongValue("campaignId")>0||b.getBooleanValue("exchange"))return;for(Map<String,Object> found:ordinary(b.getString("channel"))){if(!"gift".equals(found.get("kind")))continue;Map<String,Object> c=lock?s.one("select * from shop_campaign where id=? for update",found.get("id")):found;JSONObject cfg=config(c);if(!eligible(uid,b.getString("channel"),cfg))continue;if(number(q.get("amount"))<cfg.getLongValue("threshold"))continue;List<JSONObject> lines=(List<JSONObject>)q.get("items");boolean conflict=false;for(Object x:cfg.getJSONArray("items"))for(JSONObject l:lines)if(obj(x).getLongValue("productId")==l.getLongValue("id"))conflict=true;check(!conflict,"赠品与购买商品相同，请分开下单或联系商家调整赠品");JSONArray gifts=new JSONArray();for(Object x:cfg.getJSONArray("items")){JSONObject offer=obj(x);long pid=offer.getLongValue("productId"),qty=offer.getLongValue("quantity");Map<String,Object> p=s.one("select * from shop_product where id=?"+(lock?" for update":""),pid);check(Boolean.TRUE.equals(p.get("enabled"))||"1".equals(str(p.get("enabled"))),"赠品已下架，请联系商家处理");check("1".equals(str(p.get("C".equals(b.getString("channel"))?"retail_enabled":"wholesale_enabled")))||Boolean.TRUE.equals(p.get("C".equals(b.getString("channel"))?"retail_enabled":"wholesale_enabled")),"赠品未开放该渠道，请联系商家处理");check(held(number(c.get("id")),pid)>=qty,"赠品库存不足，请联系商家处理，不会静默替换赠品");JSONObject l=new JSONObject();for(String k:Arrays.asList("id","name","spec","image"))l.put(k,p.get(k));l.put("quantity",qty);l.put("unitPrice",0);l.put("netAmount",0);l.put("pointsUsed",0);l.put("gift",true);lines.add(l);gifts.add(l);}((JSONObject)q.get("rules")).put("campaign",new JSONObject(c));((JSONObject)q.get("rules")).put("gifts",gifts);return;}}
 public void reserve(long uid,long oid,Map<String,Object> q){JSONObject rules=(JSONObject)q.get("rules"),c=rules.getJSONObject("campaign");if(c==null)return;long cid=c.getLongValue("id"),gid=0;String kind=c.getString("kind"),channel=c.getString("channel");JSONObject cfg=JSON.parseObject(c.getString("config_json"));JSONArray selected=new JSONArray();for(Object x:(List<?>)q.get("items")){JSONObject line=obj(x);if(!"gift".equals(kind)||line.getBooleanValue("gift"))selected.add(line);}
 if("group".equals(kind)){gid=c.getLongValue("selectedGroup");if(gid==0){Timestamp until=new Timestamp(Math.min(System.currentTimeMillis()+cfg.getLongValue("hours")*3600000L,timestamp(c.get("ends_at")).getTime()));s.jdbc().update("insert into shop_campaign_group(campaign_id,required_people,expires_at) values(?,?,?)",cid,cfg.getIntValue("people"),until);gid=s.jdbc().queryForObject("select last_insert_id()",Long.class);}Map<String,Object> g=s.one("select * from shop_campaign_group where id=? and campaign_id=? for update",gid,cid);check("open".equals(g.get("status"))&&timestamp(g.get("expires_at")).getTime()>System.currentTimeMillis(),"该团已结束，请选择其他团");check(s.jdbc().queryForObject("select count(*) from shop_campaign_order where group_id=? and state in ('reserved','paid')",Long.class,gid)<number(g.get("required_people")),"该团名额已满");check(s.jdbc().queryForObject("select count(*) from shop_campaign_order where group_id=? and member_id=? and state in ('reserved','paid')",Long.class,gid,uid)==0,"您已参加该团");}
 for(Object x:selected){JSONObject line=obj(x);long pid=line.getLongValue("id"),remaining=line.getLongValue("quantity");for(Map<String,Object> pool:s.jdbc().queryForList("select * from shop_campaign_pool where campaign_id=? and product_id=? order by warehouse_id for update",cid,pid)){long n=Math.min(remaining,number(pool.get("held")));if(n==0)continue;long wid=number(pool.get("warehouse_id"));s.jdbc().update("update shop_campaign_pool set held=held-? where campaign_id=? and product_id=? and warehouse_id=?",n,cid,pid,wid);s.jdbc().update("update shop_warehouse_stock set campaign_reserved=campaign_reserved-?,available=available+? where warehouse_id=? and product_id=? and channel=?",n,n,wid,pid,channel);movement(wid,pid,channel,-n,"campaign_order_"+oid,"系统");remaining-=n;if(remaining==0)break;}check(remaining==0,"活动库存不足");stockLog(pid,line.getLongValue("quantity"),"campaign_order_"+oid,"活动预留转订单占用","系统");}
 s.jdbc().update("insert into shop_campaign_order(order_id,campaign_id,member_id,group_id,kind,snapshot_json,items_json) values(?,?,?,?,?,?,?)",oid,cid,uid,gid==0?null:gid,kind,c.toJSONString(),selected.toJSONString());}
 public void paid(long oid){paid(oid,false);}
 public void paid(long oid,boolean verifiedWechat){List<Map<String,Object>> rows=s.jdbc().queryForList("select * from shop_campaign_order where order_id=?",oid);if(rows.isEmpty())return;Map<String,Object> c=rows.get(0);s.one("select id from shop_campaign where id=? for update",c.get("campaign_id"));if(c.get("group_id")!=null){Map<String,Object> g=s.one("select * from shop_campaign_group where id=? for update",c.get("group_id"));if(verifiedWechat&&(!"open".equals(g.get("status"))||timestamp(g.get("expires_at")).getTime()<=System.currentTimeMillis())){s.jdbc().update("update shop_campaign_order set state='paid' where order_id=?",oid);if(!"success".equals(g.get("status")))s.jdbc().update("update shop_campaign_group set status='failed' where id=?",g.get("id"));return;}check("open".equals(g.get("status"))&&timestamp(g.get("expires_at")).getTime()>System.currentTimeMillis(),"该拼团已超时，请等待订单关闭或退款");}s.jdbc().update("update shop_campaign_order set state='paid' where order_id=?",oid);if(c.get("group_id")!=null){long paid=s.jdbc().queryForObject("select count(*) from shop_campaign_order where group_id=? and state='paid'",Long.class,c.get("group_id")),needed=number(s.one("select required_people from shop_campaign_group where id=?",c.get("group_id")).get("required_people"));if(paid>=needed)s.jdbc().update("update shop_campaign_group set status='success' where id=?",c.get("group_id"));}}
 public void refresh(long oid){if(s.jdbc().queryForObject("select count(*) from shop_order where id=? and status='refunded'",Long.class,oid)>0)s.jdbc().update("update shop_campaign_order set state='withdrawn' where order_id=? and state='paid'",oid);}
 public void canShip(long oid){List<Map<String,Object>> groups=s.jdbc().queryForList("select g.status from shop_campaign_order o join shop_campaign_group g on g.id=o.group_id where o.order_id=?",oid);check(groups.isEmpty()||"success".equals(groups.get(0).get("status")),"拼团尚未成功，不能交付商品");}
 public void release(long oid){List<Map<String,Object>> rows=s.jdbc().queryForList("select * from shop_campaign_order where order_id=? and state='reserved'",oid);if(rows.isEmpty())return;Map<String,Object> co=rows.get(0),c=s.one("select * from shop_campaign where id=? for update",co.get("campaign_id"));if("active".equals(c.get("status"))&&timestamp(c.get("ends_at")).getTime()>System.currentTimeMillis()){for(Object x:JSON.parseArray(str(co.get("items_json")))){JSONObject line=obj(x);allocate(number(c.get("id")),line.getLongValue("id"),str(c.get("channel")),line.getLongValue("quantity"),"campaign_cancel_"+oid,"系统");}}s.jdbc().update("update shop_campaign_order set state='released' where order_id=?",oid);}
 private void allocate(long cid,long pid,String channel,long qty,String key,String who){warehouse.ensure(pid);long left=qty;for(Map<String,Object> x:s.jdbc().queryForList("select x.* from shop_warehouse_stock x join shop_warehouse w on w.id=x.warehouse_id where x.product_id=? and x.channel=? and w.enabled=1 order by w.priority,w.id for update",pid,channel)){long n=Math.min(left,number(x.get("available"))),wid=number(x.get("warehouse_id"));if(n==0)continue;s.jdbc().update("update shop_warehouse_stock set available=available-?,campaign_reserved=campaign_reserved+? where warehouse_id=? and product_id=? and channel=?",n,n,wid,pid,channel);s.jdbc().update("insert into shop_campaign_pool(campaign_id,product_id,warehouse_id,channel,held) values(?,?,?,?,?) on duplicate key update held=held+values(held)",cid,pid,wid,channel,n);movement(wid,pid,channel,n,key,who);left-=n;if(left==0)break;}check(left==0,"活动预留超过该渠道可售库存");stockLog(pid,-qty,key,"预留活动专用库存",who);}
 @Transactional public long save(JSONObject b,String who){String name=str(b.get("name")).trim(),kind=str(b.get("kind")),channel=str(b.get("channel"));check(name.length()>0&&name.length()<=80,"请填写活动名称");check(Arrays.asList("price","discount","flash","group","combo","gift").contains(kind)&&Arrays.asList("C","B").contains(channel),"请选择活动类型和渠道");check("C".equals(channel),"新营销活动仅支持C端零售；旧企业采购只保留历史处理，分销拿货不参加营销活动");Timestamp start,end;try{start=Timestamp.valueOf(str(b.get("startsAt")).replace('T',' '));end=Timestamp.valueOf(str(b.get("endsAt")).replace('T',' '));}catch(Exception e){throw new IllegalArgumentException("请填写完整活动起止时间");}check(end.after(start),"结束时间须晚于开始时间");JSONObject cfg=b.getJSONObject("config");check(cfg!=null,"请填写活动设置");validateMinimumTier(channel,cfg);cfg.put("firstOnly",cfg.getBooleanValue("firstOnly"));JSONArray items=cfg.getJSONArray("items");check(items!=null&&items.size()<=50&&("discount".equals(kind)||!items.isEmpty()),"请填写活动商品");if(Arrays.asList("flash","group").contains(kind))check(items.size()==1,"一次秒杀或拼团活动选择一种商品");Set<Long> seen=new HashSet<>();for(Object x:items){JSONObject i=obj(x);long pid=integer(i.get("productId"),1,Long.MAX_VALUE,"请选择商品");check(seen.add(pid),"请合并重复活动商品");s.one("select id from shop_product where id=? and enabled=1 and "+("B".equals(channel)?"wholesale_enabled":"retail_enabled")+"=1",pid);if(stocked(kind)){integer(i.get("stock"),1,1000000,"活动预留数量须为1至1000000件");integer(i.get("quantity"),1,10000,"每份数量应为正整数");}if(Arrays.asList("flash","group","price").contains(kind))integer(i.get("price"),1,100000000,"活动价至少1分");}
 if(stocked(kind))integer(cfg.get("limit"),1,10000,"每人限购数量为1至10000");if("group".equals(kind)){integer(cfg.get("people"),2,100,"成团人数为2至100");integer(cfg.get("hours"),1,168,"成团时限为1至168小时");}if("combo".equals(kind))integer(cfg.get("bundlePrice"),1,100000000,"请填写套装售价");if(Arrays.asList("gift","discount").contains(kind))integer(cfg.get("threshold"),0,100000000,"门槛为非负整数分");if("discount".equals(kind)){integer(cfg.get("reduction"),0,100000000,"满减金额不正确");integer(cfg.get("payRate"),1,10000,"折扣应大于0且不超过原价");}
 long id=b.getLongValue("id");if(id>0){Map<String,Object> old=s.one("select status from shop_campaign where id=? for update",id);check("draft".equals(old.get("status")),"已发布活动保留原规则，请创建新活动");s.jdbc().update("update shop_campaign set name=?,kind=?,channel=?,starts_at=?,ends_at=?,config_json=? where id=?",name,kind,channel,start,end,cfg.toJSONString(),id);}else{s.jdbc().update("insert into shop_campaign(name,kind,channel,starts_at,ends_at,config_json) values(?,?,?,?,?,?)",name,kind,channel,start,end,cfg.toJSONString());id=s.jdbc().queryForObject("select last_insert_id()",Long.class);}s.event("campaign",id,"保存活动草稿",who);return id;}
 @Transactional public void publish(long id,String who){Map<String,Object> first=s.one("select * from shop_campaign where id=?",id);check("C".equals(first.get("channel")),"旧企业采购活动不能新发布，历史活动仍可查询或结束");List<Long> ids=new ArrayList<>();for(Object x:config(first).getJSONArray("items"))ids.add(obj(x).getLongValue("productId"));Collections.sort(ids);for(long pid:ids)s.one("select id from shop_product where id=? and enabled=1 and "+("B".equals(first.get("channel"))?"wholesale_enabled":"retail_enabled")+"=1 for update",pid);Map<String,Object> c=s.one("select * from shop_campaign where id=? for update",id);if("active".equals(c.get("status")))return;check("draft".equals(c.get("status"))&&timestamp(c.get("ends_at")).getTime()>System.currentTimeMillis(),"只能发布未过期草稿");validateMinimumTier(str(c.get("channel")),config(c));if("flash".equals(c.get("kind")))for(Map<String,Object> other:s.jdbc().queryForList("select * from shop_campaign where kind='flash' and status='active' and channel=? and starts_at<? and ends_at>?",c.get("channel"),c.get("ends_at"),c.get("starts_at")))for(Object x:config(other).getJSONArray("items"))check(!ids.contains(obj(x).getLongValue("productId")),"同商品同渠道不能发布时间重叠的秒杀");if(stocked(str(c.get("kind"))))for(Object x:config(c).getJSONArray("items")){JSONObject i=obj(x);allocate(id,i.getLongValue("productId"),str(c.get("channel")),i.getLongValue("stock"),"campaign_publish_"+id,who);}s.jdbc().update("update shop_campaign set status='active' where id=?",id);s.event("campaign",id,"发布活动",who);}
 @Transactional public void close(long id,String who){List<Map<String,Object>> pools=s.jdbc().queryForList("select * from shop_campaign_pool where campaign_id=? order by product_id,warehouse_id",id);for(Map<String,Object> p:pools)s.one("select id from shop_product where id=? for update",p.get("product_id"));Map<String,Object> c=s.one("select * from shop_campaign where id=? for update",id);if(!"active".equals(c.get("status")))return;for(Map<String,Object> p:s.jdbc().queryForList("select * from shop_campaign_pool where campaign_id=? for update",id)){long n=number(p.get("held"));if(n==0)continue;s.jdbc().update("update shop_warehouse_stock set campaign_reserved=campaign_reserved-?,available=available+? where warehouse_id=? and product_id=? and channel=?",n,n,p.get("warehouse_id"),p.get("product_id"),p.get("channel"));s.jdbc().update("update shop_campaign_pool set held=0 where campaign_id=? and product_id=? and warehouse_id=?",id,p.get("product_id"),p.get("warehouse_id"));stockLog(number(p.get("product_id")),n,"campaign_close_"+id+"_"+p.get("warehouse_id"),"结束活动归还未售库存",who);}s.jdbc().update("update shop_campaign set status='closed' where id=?",id);s.event("campaign",id,"结束活动，未售库存归还渠道，已下订单保留规则",who);}
 public Map<String,Object> info(long uid,long oid){Map<String,Object> order=s.companyOrder(uid,oid,"view",false);List<Map<String,Object>> rows=s.jdbc().queryForList("select * from shop_campaign_order where order_id=?",oid);if(rows.isEmpty())return new HashMap<>();Map<String,Object> r=rows.get(0);if(r.get("group_id")!=null){Map<String,Object> g=s.one("select * from shop_campaign_group where id=?",r.get("group_id"));g.put("paidPeople",s.jdbc().queryForObject("select count(*) from shop_campaign_order where group_id=? and state='paid'",Long.class,r.get("group_id")));r.put("group",g);}if("gift".equals(r.get("kind"))){JSONObject cfg=JSON.parseObject(str(JSON.parseObject(str(r.get("snapshot_json"))).get("config_json")));r.put("giftReturnRequired",number(order.get("amount"))-number(order.get("shipping_amount"))-number(order.get("refunded_amount"))+number(order.get("refunded_shipping_amount"))<cfg.getLongValue("threshold"));}return r;}
 @Transactional public void failGroup(long gid){Map<String,Object> g=s.one("select * from shop_campaign_group where id=? for update",gid);if(!"open".equals(g.get("status"))||timestamp(g.get("expires_at")).getTime()>System.currentTimeMillis())return;s.jdbc().update("update shop_campaign_group set status='failed' where id=?",gid);}
 @Transactional public void refundFailed(long oid){Map<String,Object> co=s.one("select c.*,g.status group_status from shop_campaign_order c join shop_campaign_group g on g.id=c.group_id where c.order_id=?",oid);if(!"failed".equals(co.get("group_status")))return;Map<String,Object> o=s.one("select * from shop_order where id=?",oid);if("pending".equals(o.get("status"))){s.orderAction(number(o.get("member_id")),oid,"cancel");return;}if(!"paid".equals(o.get("status")))return;if(s.jdbc().queryForObject("select count(*) from shop_case where order_id=? and status not in ('refunded','completed','rejected')",Long.class,oid)>0)return;JSONArray items=new JSONArray();for(Map<String,Object> i:s.jdbc().queryForList("select * from shop_order_item where order_id=?",oid)){long refunded=workflow.refundedQty(oid,number(i.get("id"))),qty=number(i.get("quantity"))-refunded;if(qty>0){JSONObject x=new JSONObject();x.put("id",i.get("id"));x.put("quantity",qty);items.add(x);}}if(items.isEmpty())return;JSONObject b=new JSONObject();b.put("orderId",oid);b.put("type","refund");b.put("reason","拼团超时未成功，自动退回原支付款项");b.put("reasonCode","merchant");b.put("refundShipping",true);b.put("items",items);workflow.apply(number(o.get("member_id")),b);long cid=number(s.one("select id from shop_case where order_id=? order by id desc limit 1",oid).get("id"));JSONObject handle=new JSONObject();handle.put("action","approve");handle.put("note","拼团失败自动退款");workflow.handle(cid,handle,"系统");}
}
