package com.ruoyi.web.controller.shop;
import java.util.*;import com.alibaba.fastjson2.JSONObject;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.context.annotation.Lazy;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.ruoyi.common.utils.SecurityUtils;import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopAccountAppeal {
 @Autowired @Lazy ShopService s;
 @Transactional public Map<String,Object> submit(JSONObject b){String name=str(b.get("username")).trim().toLowerCase(Locale.ROOT),contact=str(b.get("contact")).trim(),evidence=str(b.get("evidence")).trim(),password=str(b.get("password"));check(name.matches("[a-z0-9_]{3,40}"),"请填写原登录账号");check(contact.length()>=5&&contact.length()<=200,"请填写可联系您的方式，5至200字");check(evidence.length()>=20&&evidence.length()<=2000,"请填写至少20字的账号归属线索，如原订单、使用时间、企业授权，不要提交密码或完整证件号");check(password.length()>=8&&password.length()<=64&&password.getBytes(java.nio.charset.StandardCharsets.UTF_8).length<=72,"新密码需8至64位且不超过72字节");List<Map<String,Object>> users=s.jdbc().queryForList("select member_id,password_hash from shop_credentials where username=?",name);if(!users.isEmpty())s.one("select id from shop_member where id=? for update",users.get(0).get("member_id"));check(s.jdbc().queryForObject("select count(*) from shop_account_appeal where username=? and created_at>date_sub(now(),interval 1 day)",Long.class,name)<3,"该账号今天的申诉次数较多，请稍后再试");byte[] bytes=new byte[32];new java.security.SecureRandom().nextBytes(bytes);String key=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);s.jdbc().update("insert into shop_account_appeal(username,member_id,contact,evidence,access_hash,new_password_hash,original_password_hash) values(?,?,?,?,?,?,?)",name,users.isEmpty()?null:users.get(0).get("member_id"),contact,evidence,s.hash(key),SecurityUtils.encryptPassword(password),users.isEmpty()?null:users.get(0).get("password_hash"));Map<String,Object> r=new HashMap<>();r.put("key",key);r.put("status","pending");return r;}
 public Map<String,Object> status(String key){check(str(key).matches("[A-Za-z0-9_-]{43}"),"请使用本次申诉保存的查询凭证");return s.one("select id,status,note,created_at,updated_at from shop_account_appeal where access_hash=?",s.hash(key));}
 @Transactional public void supplement(String key,JSONObject b){Map<String,Object> row=status(key);Map<String,Object> a=s.one("select * from shop_account_appeal where id=? for update",row.get("id"));check(Arrays.asList("pending","more").contains(str(a.get("status"))),"申诉已处理，不能再补充");String evidence=str(b.get("evidence")).trim();check(evidence.length()>=20&&evidence.length()<=2000,"请填写20至2000字补充依据");s.jdbc().update("update shop_account_appeal set evidence=?,status='pending' where id=?",evidence,a.get("id"));}
 public List<Map<String,Object>> admin(){return s.jdbc().queryForList("select a.id,a.username,a.member_id,a.contact,a.evidence,a.status,a.note,a.reviewer,a.created_at,a.updated_at"+ShopQueryFields.fields("a.member_id")+" from shop_account_appeal a order by a.id desc");}
 @Transactional public void review(long id,JSONObject b,String who,boolean manager){Map<String,Object> preliminary=s.one("select member_id from shop_account_appeal where id=?",id);if(preliminary.get("member_id")!=null)s.one("select id from shop_member where id=? for update",preliminary.get("member_id"));Map<String,Object> a=s.one("select * from shop_account_appeal where id=? for update",id);String action=str(b.get("action")),note=str(b.get("note")).trim();check(Arrays.asList("approve","reject","more").contains(action),"请选择补充资料、驳回或核实通过");if("approved".equals(a.get("status"))&&"approve".equals(action))return;check(Arrays.asList("pending","more").contains(str(a.get("status"))),"该申诉已处理");check(note.length()>=10&&note.length()<=1500,"请填写至少10字核验依据或补充要求");if("approve".equals(action)){check(manager,"只有管理员可批准账号重置");check(b.getBooleanValue("verified"),"请先核实账号归属，不能仅凭姓名或未验证电话重置");check(a.get("member_id")!=null,"无法关联原账号，请补充核验线索");long uid=number(a.get("member_id"));Map<String,Object> member=s.one("select enabled from shop_member where id=?",uid);check(Boolean.TRUE.equals(member.get("enabled"))||"1".equals(str(member.get("enabled"))),"账号已停用，不能通过找回流程绕过停用");Map<String,Object> credentials=s.one("select password_hash from shop_credentials where member_id=? for update",uid);check(Objects.equals(credentials.get("password_hash"),a.get("original_password_hash")),"申诉后密码已变化，请重新核实并提交申诉");s.jdbc().update("update shop_credentials set password_hash=? where member_id=?",a.get("new_password_hash"),uid);s.jdbc().update("delete from shop_session where member_id=?",uid);s.jdbc().update("delete from shop_recovery where member_id=?",uid);s.event("member",uid,"人工核验账号归属后重置密码，撤销旧会话和恢复码；申诉"+id,who);}
 s.jdbc().update("update shop_account_appeal set status=?,note=?,reviewer=?,new_password_hash=case when ? in ('approved','rejected') then '' else new_password_hash end,original_password_hash=case when ? in ('approved','rejected') then null else original_password_hash end where id=?","approve".equals(action)?"approved":"reject".equals(action)?"rejected":"more",note,who,"approve".equals(action)?"approved":"reject".equals(action)?"rejected":"more","approve".equals(action)?"approved":"reject".equals(action)?"rejected":"more",id);s.event("appeal",id,action,who);}
}
