package com.ruoyi.web.controller.shop;
import java.util.*;import java.io.*;import java.nio.file.*;import java.awt.*;import java.awt.image.BufferedImage;import javax.imageio.ImageIO;import javax.servlet.http.HttpServletRequest;import org.springframework.beans.factory.annotation.*;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.http.*;import com.alibaba.fastjson2.*;import com.ruoyi.common.annotation.Anonymous;import com.ruoyi.common.core.domain.AjaxResult;import com.ruoyi.common.utils.SecurityUtils;import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController public class ShopPromoController {
 @Autowired ShopService s;@Autowired ShopWechat wechat;@Value("${shop.asset-path:../runtime/assets}")String assets;@Value("${ruoyi.profile}")String uploads;
 private long member(HttpServletRequest r){Map<String,Object> m=s.member(r.getHeader("X-Shop-Token"));check("approved".equals(m.get("distributor_state")),"请先通过分销审核再使用推广素材");return number(m.get("id"));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:content,shop:catalog')") @GetMapping("/shop/admin/promo-materials") public AjaxResult admin(){return AjaxResult.success(s.jdbc().queryForList("select * from shop_promo_material order by sort_order,id"));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:content,shop:catalog')") @PostMapping("/shop/admin/promo-materials") @Transactional public AjaxResult save(@RequestBody JSONObject b){String title=str(b.get("title")).trim(),category=str(b.get("category")).trim(),image=str(b.get("image")),copy=str(b.get("copyText")),channel=str(b.get("channel")),target=str(b.get("target"));check(title.length()>0&&title.length()<=80&&category.length()>0&&category.length()<=40&&copy.length()<=2000,"请填写素材名称、分类和文案");check(image.startsWith("/")&&!image.startsWith("//")&&image.matches("(?i).+\\.(png|jpg|jpeg|webp)$"),"请上传推广图片");check(Arrays.asList("C","B").contains(channel)&&Arrays.asList("product","recruit").contains(target),"请选择推广渠道和落地页面");long product=b.getLongValue("productId"),sort=integer(b.getOrDefault("sort",0),0,100000,"排序不正确");if("product".equals(target))s.one("select id from shop_product where id=?",product);long id=b.getLongValue("id");if(id>0)s.jdbc().update("update shop_promo_material set title=?,category=?,image=?,copy_text=?,channel=?,target=?,product_id=?,enabled=?,sort_order=? where id=?",title,category,image,copy,channel,target,product,b.getBooleanValue("enabled"),sort,id);else{s.jdbc().update("insert into shop_promo_material(title,category,image,copy_text,channel,target,product_id,enabled,sort_order) values(?,?,?,?,?,?,?,?,?)",title,category,image,copy,channel,target,product,b.getBooleanValue("enabled"),sort);id=s.jdbc().queryForObject("select last_insert_id()",Long.class);}s.event("promo",id,"保存推广素材与开放状态",SecurityUtils.getUsername());return AjaxResult.success();}
 private String link(long uid,Map<String,Object> row){String base=str(s.rules().getOrDefault("shareBaseUrl","https://meir.okam.top"));return base+"/#/pages/"+("recruit".equals(row.get("target"))?"distributor-apply":"product")+"/index?referrer="+uid+("recruit".equals(row.get("target"))?"":"&id="+row.get("product_id")+"&channel="+row.get("channel"));}
 @Anonymous @GetMapping("/shop/app/promo-materials") public AjaxResult list(HttpServletRequest r){long uid=member(r);java.util.List<Map<String,Object>> rows=s.jdbc().queryForList("select a.*,p.name product_name,p.spec,p.price,p.wholesale from shop_promo_material a left join shop_product p on p.id=a.product_id where a.enabled=1 and (a.target='recruit' or (p.enabled=1 and if(a.channel='C',p.retail_enabled,p.wholesale_enabled)=1)) order by a.sort_order,a.id");long tier=s.jdbc().queryForObject("select coalesce(max(tier),0) from shop_distribution_profile where member_id=?",Long.class,uid);for(Map<String,Object> row:rows){personalize(uid,row);row.put("link",link(uid,row));row.put("invitationCode",uid);long estimate=0;if("product".equals(row.get("target"))){java.util.List<Map<String,Object>> rules=s.jdbc().queryForList("select kind,value from shop_distribution_rule where enabled=1 and depth=1 and channel=? and product_id in (0,?) and tier in (-1,?) order by (product_id<>0) desc,(tier<>-1) desc limit 1",row.get("channel"),row.get("product_id"),tier);if(!rules.isEmpty()){Map<String,Object> rule=rules.get(0);long price=number(row.get("B".equals(row.get("channel"))?"wholesale":"price"));estimate=Math.min(price,"fixed".equals(rule.get("kind"))?number(rule.get("value")):ShopCommerce.portion(price,number(rule.get("value")),10000));}}row.put("estimatedCommission",estimate);}return AjaxResult.success(rows);}

 private JSONObject draft(long uid,long id){java.util.List<Map<String,Object>> rows=s.jdbc().queryForList("select content from shop_config where config_key=?","promo_draft_"+uid+"_"+id);return rows.isEmpty()?new JSONObject():JSON.parseObject(str(rows.get(0).get("content")));}
 private void personalize(long uid,Map<String,Object> row){JSONObject value=draft(uid,number(row.get("id")));row.put("originalTitle",row.get("title"));row.put("originalCopy",row.get("copy_text"));row.put("draftRevision",value.getIntValue("revision"));if(value.containsKey("title"))row.put("title",value.getString("title"));if(value.containsKey("copyText"))row.put("copy_text",value.getString("copyText"));}
 @Anonymous @PostMapping("/shop/app/promo-materials/{id}/draft") @Transactional public AjaxResult saveDraft(HttpServletRequest r,@PathVariable long id,@RequestBody JSONObject body){
  long uid=member(r);s.one("select id from shop_promo_material where id=? and enabled=1",id);String title=str(body.get("title")).trim(),copy=str(body.get("copyText")).trim();check(!title.isEmpty()&&title.length()<=80&&copy.length()<=2000,"标题需1至80字，文案最多2000字");String key="promo_draft_"+uid+"_"+id;
  s.jdbc().update("insert ignore into shop_config(config_key,content) values(?,?)",key,"{}");JSONObject old=JSON.parseObject(s.jdbc().queryForObject("select content from shop_config where config_key=? for update",String.class,key));check(old.getIntValue("revision")==body.getIntValue("revision"),"文案已在其他设备更新，请重新打开素材后编辑");
  JSONObject value=new JSONObject();value.put("title",title);value.put("copyText",copy);value.put("revision",old.getIntValue("revision")+1);s.jdbc().update("update shop_config set content=? where config_key=?",value.toJSONString(),key);return AjaxResult.success(value);
 }
 private void text(Graphics2D g,String text,int x,int y,int width,int lineHeight,int lines){String current="";int row=0;for(char ch:text.toCharArray()){if(g.getFontMetrics().stringWidth(current+ch)>width||ch=='\n'){g.drawString(current,x,y+row*lineHeight);current="";row++;if(row>=lines)return;if(ch=='\n')continue;}current+=ch;}if(row<lines)g.drawString(current,x,y+row*lineHeight);}
 @Anonymous @GetMapping("/shop/app/promo-materials/{id}/poster") public ResponseEntity<byte[]> poster(HttpServletRequest r,@PathVariable long id)throws IOException{long uid=member(r);Map<String,Object> row=s.one("select * from shop_promo_material where id=? and enabled=1",id);if("product".equals(row.get("target")))check(s.jdbc().queryForObject("select count(*) from shop_product where id=? and enabled=1 and if(?='C',retail_enabled,wholesale_enabled)=1",Long.class,row.get("product_id"),row.get("channel"))>0,"该推广商品已停止销售");personalize(uid,row);String uri=str(row.get("image"));Path root,path;if(uri.startsWith("/shop-assets/")){root=Paths.get(assets).toAbsolutePath().normalize();path=root.resolve(uri.substring(13)).normalize();}else{check(uri.startsWith("/profile/"),"请为该素材上传可生成海报的图片");root=Paths.get(uploads).toAbsolutePath().normalize();path=root.resolve(uri.substring(9)).normalize();}check(path.startsWith(root)&&Files.isRegularFile(path),"素材图片不存在，请联系商家更新");BufferedImage source=ImageIO.read(path.toFile());check(source!=null,"该图片暂不能生成海报，请使用原图下载");BufferedImage canvas=new BufferedImage(720,1200,BufferedImage.TYPE_INT_RGB);Graphics2D g=canvas.createGraphics();try{g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g.setColor(Color.WHITE);g.fillRect(0,0,720,1200);g.setColor(new Color(49,92,68));g.fillRect(0,0,720,110);g.setColor(Color.WHITE);g.setFont(new Font("Microsoft YaHei",Font.BOLD,30));text(g,str(s.rules().getOrDefault("shopName","美容商城")),36,67,650,36,1);double ratio=Math.min(648.0/source.getWidth(),560.0/source.getHeight());int w=(int)(source.getWidth()*ratio),h=(int)(source.getHeight()*ratio);g.drawImage(source,(720-w)/2,130+(560-h)/2,w,h,null);g.setColor(new Color(35,55,42));g.setFont(new Font("Microsoft YaHei",Font.BOLD,28));text(g,str(row.get("title")),36,740,648,38,2);g.setFont(new Font("Microsoft YaHei",Font.PLAIN,22));text(g,str(row.get("copy_text")),36,835,648,32,3);g.setFont(new Font("Microsoft YaHei",Font.BOLD,28));if(wechat.ready()){BufferedImage code=wechat.promotionCode(uid,number(row.get("product_id")),str(row.get("channel")),"recruit".equals(row.get("target")));g.drawImage(code,458,954,230,230,null);g.setFont(new Font("Microsoft YaHei",Font.BOLD,24));g.drawString("微信扫码查看",36,995);g.setFont(new Font("Microsoft YaHei",Font.PLAIN,20));g.drawString("邀请码："+uid,36,1035);}else{g.drawString("推广邀请码："+uid,36,990);}g.setFont(new Font("Microsoft YaHei",Font.PLAIN,17));text(g,"商品价格与权益以结算时为准",36,1090,400,26,2);}finally{g.dispose();}ByteArrayOutputStream out=new ByteArrayOutputStream();ImageIO.write(canvas,"png",out);return ResponseEntity.ok().cacheControl(CacheControl.noStore()).contentType(MediaType.IMAGE_PNG).body(out.toByteArray());}
}
