package com.ruoyi.web.controller.shop;
import java.util.*;import javax.servlet.http.HttpServletRequest;import com.alibaba.fastjson2.JSONObject;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import com.ruoyi.common.annotation.Anonymous;import com.ruoyi.common.core.domain.AjaxResult;import com.ruoyi.common.utils.SecurityUtils;import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController public class ShopExchangeController {
 @Autowired ShopService s;
 @Anonymous @GetMapping("/shop/app/point-exchange") public AjaxResult offers(HttpServletRequest r){s.member(r.getHeader("X-Shop-Token"));return AjaxResult.success(s.jdbc().queryForList("select p.id,p.name,p.spec,p.image,coalesce((select sum(x.available) from shop_warehouse_stock x join shop_warehouse w on w.id=x.warehouse_id where x.product_id=p.id and x.channel='C' and w.enabled=1),0) stock,e.points_cost from shop_point_exchange e join shop_product p on p.id=e.product_id where e.enabled=1 and p.enabled=1 and (e.starts_at is null or e.starts_at<=now()) and (e.ends_at is null or e.ends_at>now()) order by p.id"));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:catalog')") @GetMapping("/shop/admin/point-exchange") public AjaxResult list(){return AjaxResult.success(s.jdbc().queryForList("select p.id,p.name,p.spec,p.stock,e.points_cost,coalesce(e.enabled,0) exchange_enabled,e.starts_at,e.ends_at from shop_product p left join shop_point_exchange e on e.product_id=p.id order by p.id"));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:catalog')") @PostMapping("/shop/admin/point-exchange/{id}") @Transactional public AjaxResult save(@PathVariable long id,@RequestBody JSONObject b){Map<String,Object> p=s.one("select stock from shop_product where id=? for update",id);long points=integer(b.get("points"),1,100000000,"兑换积分为1至1亿的整数");check(!b.getBooleanValue("enabled")||number(p.get("stock"))>0,"商品没有库存，不能开放兑换");java.sql.Timestamp start=date(b.get("start")),end=date(b.get("end"));check(start==null||end==null||end.after(start),"结束时间须晚于开始时间");s.jdbc().update("insert into shop_point_exchange values(?,?,?,?,?) on duplicate key update points_cost=values(points_cost),enabled=values(enabled),starts_at=values(starts_at),ends_at=values(ends_at)",id,points,b.getBooleanValue("enabled"),start,end);s.event("product",id,"设置积分兑换，既有订单不变",SecurityUtils.getUsername());return AjaxResult.success();}
 private java.sql.Timestamp date(Object value){String text=str(value);if(text.isEmpty())return null;try{return java.sql.Timestamp.valueOf(text.replace('T',' '));}catch(Exception e){throw new IllegalArgumentException("日期格式不正确");}}
}
