package com.ruoyi.web.controller.shop;
import java.util.*;import javax.servlet.http.HttpServletRequest;import com.alibaba.fastjson2.JSONObject;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.prepost.PreAuthorize;import com.ruoyi.common.annotation.Anonymous;import com.ruoyi.common.core.domain.AjaxResult;import com.ruoyi.common.utils.SecurityUtils;import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController public class ShopDistributionController {
 @Autowired ShopDistribution d;@Autowired ShopService s;
 @Anonymous @GetMapping("/shop/app/distribution-application-settings") public AjaxResult applicationSettings(){JSONObject all=d.settings(),out=new JSONObject();out.put("required",all.getBooleanValue("requireApplicationMaterial"));out.put("label",all.getOrDefault("applicationMaterialLabel","资格核验资料"));return AjaxResult.success(out);}
 private long uid(HttpServletRequest r){return number(s.member(r.getHeader("X-Shop-Token")).get("id"));}
 @Anonymous @GetMapping("/shop/app/distribution-detail") public AjaxResult own(HttpServletRequest r){long owner=uid(r);Map<String,Object> result=d.summary(owner);for(Map<String,Object> member:(List<Map<String,Object>>)result.get("team")){List<Map<String,Object>> notes=s.jdbc().queryForList("select content from shop_config where config_key=?","team_note_"+owner+"_"+member.get("id"));member.put("note",notes.isEmpty()?"":com.alibaba.fastjson2.JSON.parseObject(str(notes.get(0).get("content"))).getString("note"));}return AjaxResult.success(result);}
 @Anonymous @PostMapping("/shop/app/distribution-team/{id}/note") public AjaxResult teamNote(HttpServletRequest r,@PathVariable long id,@RequestBody JSONObject body){long owner=uid(r);check("approved".equals(s.one("select distributor_state from shop_member where id=?",owner).get("distributor_state")),"分销审核通过后可管理团队备注");check(s.jdbc().queryForObject("select count(*) from shop_member m left join shop_member parent on parent.id=m.referrer_id where m.id=? and (m.referrer_id=? or parent.referrer_id=?)",Long.class,id,owner,owner)>0,"只能编辑自己团队成员的备注");String note=str(body.get("note")).trim();check(note.length()<=200,"备注最多200字");JSONObject content=new JSONObject();content.put("note",note);s.jdbc().update("insert into shop_config(config_key,content) values(?,?) on duplicate key update content=values(content)","team_note_"+owner+"_"+id,content.toJSONString());return AjaxResult.success();}
 @Anonymous @PostMapping("/shop/app/referral") public AjaxResult bind(HttpServletRequest r,@RequestBody JSONObject b){long id=uid(r);d.relation(id,b.getLongValue("referrer"),false,"用户主动确认",str(id));return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:finance')") @GetMapping("/shop/admin/distribution-settings") public AjaxResult settings(){JSONObject r=new JSONObject();r.put("settings",d.settings());r.put("rules",d.rules());r.put("members",s.jdbc().queryForList("select m.id,m.nickname,m.referrer_id,m.distributor_state,coalesce(p.tier,0) tier,coalesce(p.frozen,0) frozen,p.reason"+ShopQueryFields.fields("m.id")+" from shop_member m left join shop_distribution_profile p on p.member_id=m.id where m.is_test=0 order by m.id desc"));r.put("companies",s.jdbc().queryForList("select c.id,c.name,r.referrer_id"+ShopQueryFields.fields("c.owner_id")+" from shop_company c left join shop_company_referral r on r.company_id=c.id"));r.put("products",s.jdbc().queryForList("select id,name,spec from shop_product where archived=0 order by id"));r.put("rewards",s.jdbc().queryForList("select r.*,o.order_no,o.channel,m.nickname,i.name"+ShopQueryFields.fields("m.id")+" from shop_reward r join shop_order o on o.id=r.order_id join shop_member m on m.id=r.member_id join shop_order_item i on i.id=r.item_id where 1=1"+s.verifiedPayment("o.id")+" order by r.id desc"));return AjaxResult.success(r);}
 @PreAuthorize("@ss.hasPermi('shop:manage')") @PostMapping("/shop/admin/distribution-settings") public AjaxResult save(@RequestBody JSONObject b){d.save(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasPermi('shop:manage')") @PostMapping("/shop/admin/distribution-rules") public AjaxResult rule(@RequestBody JSONObject b){d.rule(b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasPermi('shop:manage')") @PostMapping("/shop/admin/distribution-members/{id}") public AjaxResult profile(@PathVariable long id,@RequestBody JSONObject b){d.profile(id,b,SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasPermi('shop:manage')") @PostMapping("/shop/admin/distribution-relations") public AjaxResult relation(@RequestBody JSONObject b){if(b.getBooleanValue("company"))d.companyRelation(b.getLongValue("id"),b.getLongValue("referrer"),str(b.get("reason")),SecurityUtils.getUsername());else d.relation(b.getLongValue("id"),b.getLongValue("referrer"),true,str(b.get("reason")),SecurityUtils.getUsername());return AjaxResult.success();}
}
