package com.ruoyi.web.controller.shop;
import java.io.*;import java.nio.file.*;import java.util.*;import javax.servlet.http.HttpServletRequest;import javax.imageio.ImageIO;
import org.springframework.beans.factory.annotation.*;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.multipart.MultipartFile;import org.springframework.http.*;
import com.alibaba.fastjson2.JSONObject;import com.ruoyi.common.annotation.Anonymous;import com.ruoyi.common.core.domain.AjaxResult;import com.ruoyi.common.utils.SecurityUtils;import static com.ruoyi.web.controller.shop.ShopService.*;
@RestController public class ShopInvoiceController {
 @Autowired ShopService s;@Autowired ShopInvoice invoice;@Value("${shop.private-path:../runtime/private}") String privatePath;
 private long uid(HttpServletRequest r){return number(s.member(r.getHeader("X-Shop-Token")).get("id"));}
 @Anonymous @GetMapping("/shop/app/invoices") public AjaxResult list(HttpServletRequest r){return AjaxResult.success(invoice.list(uid(r)));}
 @Anonymous @PostMapping("/shop/app/invoices") public AjaxResult apply(HttpServletRequest r,@RequestBody JSONObject b){return AjaxResult.success(invoice.apply(uid(r),b));}
 @Anonymous @GetMapping("/shop/app/invoices/files/{id}") public ResponseEntity<byte[]> download(HttpServletRequest r,@PathVariable long id)throws IOException {return read(invoice.file(uid(r),id));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:finance')") @GetMapping("/shop/admin/invoices") public AjaxResult admin(){return AjaxResult.success(invoice.admin());}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:finance')") @PostMapping("/shop/admin/invoices/{id}/reject") public AjaxResult reject(@PathVariable long id,@RequestBody JSONObject b){invoice.reject(id,b.getString("note"),SecurityUtils.getUsername());return AjaxResult.success();}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:finance')") @GetMapping("/shop/admin/invoices/files/{id}") public ResponseEntity<byte[]> adminDownload(@PathVariable long id)throws IOException {return read(invoice.adminFile(id));}
 @PreAuthorize("@ss.hasAnyPermi('shop:manage,shop:finance')") @PostMapping("/shop/admin/invoices/{id}/file") public AjaxResult upload(@PathVariable long id,@RequestParam("file")MultipartFile file,@RequestParam("metadata")String metadata)throws IOException {
  check(file.getSize()>0&&file.getSize()<=10*1024*1024,"票据文件须小于10MB");byte[] bytes=file.getBytes();String original=str(file.getOriginalFilename());check(original.length()>0&&original.length()<=200,"文件名过长");String lower=original.toLowerCase(Locale.ROOT),extension;
  if(lower.endsWith(".pdf")){check(bytes.length>=8&&new String(bytes,0,5,java.nio.charset.StandardCharsets.US_ASCII).equals("%PDF-"),"请上传PDF文件");extension=".pdf";}else{java.awt.image.BufferedImage image=ImageIO.read(new ByteArrayInputStream(bytes));check(image!=null&&image.getWidth()<=8000&&image.getHeight()<=8000,"请上传PDF、JPG或PNG票据文件");if(lower.endsWith(".png"))extension=".png";else{check(lower.endsWith(".jpg")||lower.endsWith(".jpeg"),"请上传PDF、JPG或PNG票据文件");extension=".jpg";}}
  Path dir=Paths.get(privatePath).toAbsolutePath().normalize().resolve("invoices");Files.createDirectories(dir);String filename=UUID.randomUUID().toString()+extension;Path path=dir.resolve(filename);boolean attached=false;try{Files.write(path,bytes,StandardOpenOption.CREATE_NEW);invoice.attach(id,filename,original,JSONObject.parseObject(metadata),SecurityUtils.getUsername());attached=true;}finally{if(!attached)Files.deleteIfExists(path);}return AjaxResult.success();
 }
 private ResponseEntity<byte[]> read(Map<String,Object> f)throws IOException {String name=str(f.get("path"));check(name.matches("[a-f0-9-]{36}\\.(pdf|png|jpg)"),"文件不存在");Path path=Paths.get(privatePath).toAbsolutePath().normalize().resolve("invoices").resolve(name);if(!Files.exists(path))return ResponseEntity.notFound().build();String type=name.endsWith(".pdf")?"application/pdf":name.endsWith(".png")?"image/png":"image/jpeg";return ResponseEntity.ok().cacheControl(CacheControl.noStore()).header("Content-Disposition","attachment; filename="+name).contentType(MediaType.parseMediaType(type)).body(Files.readAllBytes(path));}
}
