package com.ruoyi.web.controller.shop;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import com.alibaba.fastjson2.*;
import static com.ruoyi.web.controller.shop.ShopService.*;

@Service public class ShopWorkflow {
 @Autowired ShopService s;
 private long share(long value,long amount,long total){return java.math.BigInteger.valueOf(value).multiply(java.math.BigInteger.valueOf(amount)).divide(java.math.BigInteger.valueOf(total)).longValueExact();}
 private List<Map<String,Object>> shipmentRows(long id){return s.jdbc().queryForList("select * from shop_shipment where order_id=? order by id",id);}
 public List<Map<String,Object>> shipments(long id){List<Map<String,Object>> rows=shipmentRows(id);Map<Long,Map<Long,Long>> refunded=refundedParcels(id);for(Map<String,Object> parcel:rows)parcel.put("fully_refunded",refundedParcel(parcel,refunded));return rows;}
 private List<Map<String,Object>> lines(long id){return s.jdbc().queryForList("select * from shop_order_item where order_id=? order by id",id);}
 public List<Map<String,Object>> itemsWithProgress(long oid){List<Map<String,Object>> rows=lines(oid);for(Map<String,Object> l:rows){long id=number(l.get("id")),qty=number(l.get("quantity")),sent=shipped(oid,id),refunded=refundedQty(oid,id),unshipped=Math.max(0,qty-sent-unshippedRefunded(oid,id));l.put("shipped_quantity",sent);l.put("refunded_quantity",refunded);l.put("remaining_to_ship",unshipped);l.put("refundable_quantity",qty-refunded);l.put("delivered_refundable_quantity",Math.max(0,qty-refunded-unshipped));}attachRefundCandidates(rows,shipmentRows(oid),s.jdbc().queryForList("select status,items_json from shop_case where order_id=?",oid));return rows;}

 // Load only the caller-authorized order IDs, in bounded batches, instead of querying each line repeatedly.
 @Transactional(readOnly=true) public void attachItemsWithProgress(List<Map<String,Object>> orders){
  for(int offset=0;offset<orders.size();offset+=500){
   List<Map<String,Object>> batch=orders.subList(offset,Math.min(offset+500,orders.size()));
   Map<Long,Map<String,Object>> byId=new HashMap<>();List<Object> ids=new ArrayList<>();
   for(Map<String,Object> order:batch){long id=number(order.get("id"));byId.put(id,order);ids.add(id);order.put("items",new ArrayList<Map<String,Object>>());}
   String marks=String.join(",",Collections.nCopies(ids.size(),"?"));Object[] args=ids.toArray();
   List<Map<String,Object>> caseRows=s.jdbc().queryForList("select order_id,status,amount,items_json from shop_case where order_id in ("+marks+") order by id",args);
   for(Map<String,Object> c:caseRows){
    Map<String,Object> order=byId.get(number(c.get("order_id")));order.put("after_sale_status",c.get("status"));
    if(!Arrays.asList("rejected","refunded","completed").contains(str(c.get("status"))))order.put("active_after_sale_status",c.get("status"));
   }
   Set<Long> withParcels=new HashSet<>();Map<String,long[]> progress=new HashMap<>();
   List<Map<String,Object>> parcelRows=s.jdbc().queryForList("select id,order_id,carrier,tracking,received,items_json from shop_shipment where order_id in ("+marks+") order by id",args);
   for(Map<String,Object> parcel:parcelRows){
    withParcels.add(number(parcel.get("order_id")));
    for(Object obj:JSON.parseArray(str(parcel.get("items_json")))){JSONObject line=JSON.parseObject(JSON.toJSONString(obj));progress.computeIfAbsent(number(parcel.get("order_id"))+":"+line.getLongValue("id"),k->new long[3])[0]+=line.getLongValue("quantity");}
   }
   for(Map<String,Object> item:s.jdbc().queryForList("select order_id,items_json from shop_case where status='refunded' and order_id in ("+marks+")",args))
    for(Object obj:JSON.parseArray(str(item.get("items_json")))){JSONObject line=JSON.parseObject(JSON.toJSONString(obj));long[] p=progress.computeIfAbsent(number(item.get("order_id"))+":"+line.getLongValue("id"),k->new long[3]);p[1]+=line.getLongValue("quantity");p[2]+=line.getLongValue("unshipped");}
   for(Map<String,Object> line:s.jdbc().queryForList("select * from shop_order_item where order_id in ("+marks+") order by id",args)){
    long oid=number(line.get("order_id")),qty=number(line.get("quantity"));Map<String,Object> order=byId.get(oid);long[] p=progress.getOrDefault(oid+":"+number(line.get("id")),new long[3]);long sent=p[0];
    if(!withParcels.contains(oid)&&Arrays.asList("shipped","completed").contains(str(order.get("status")))&&!str(order.get("tracking")).isEmpty())sent=qty;
    long unshipped=Math.max(0,qty-sent-p[2]);line.put("shipped_quantity",sent);line.put("refunded_quantity",p[1]);line.put("remaining_to_ship",unshipped);line.put("refundable_quantity",qty-p[1]);line.put("delivered_refundable_quantity",Math.max(0,qty-p[1]-unshipped));
    ((List<Map<String,Object>>)order.get("items")).add(line);
   }
   for(Map<String,Object> order:batch){long oid=number(order.get("id"));List<Map<String,Object>> orderParcels=new ArrayList<>(),orderCases=new ArrayList<>();for(Map<String,Object> parcel:parcelRows)if(number(parcel.get("order_id"))==oid)orderParcels.add(parcel);for(Map<String,Object> c:caseRows)if(number(c.get("order_id"))==oid)orderCases.add(c);attachRefundCandidates((List<Map<String,Object>>)order.get("items"),orderParcels,orderCases);}
  }
 }
 private long shipped(long oid,long line){long qty=0;List<Map<String,Object>> parcels=shipments(oid);if(parcels.isEmpty()){Map<String,Object> o=s.one("select status,tracking from shop_order where id=?",oid);if(Arrays.asList("shipped","completed").contains(str(o.get("status")))&&!str(o.get("tracking")).isEmpty())return number(s.one("select quantity from shop_order_item where id=?",line).get("quantity"));}for(Map<String,Object> parcel:parcels)for(Object obj:JSON.parseArray(str(parcel.get("items_json")))){JSONObject i=JSON.parseObject(JSON.toJSONString(obj));if(i.getLongValue("id")==line)qty+=i.getLongValue("quantity");}return qty;}
 private long unshippedRefunded(long oid,long line){long qty=0;for(Map<String,Object> c:s.jdbc().queryForList("select items_json from shop_case where order_id=? and status='refunded'",oid))for(Object obj:JSON.parseArray(str(c.get("items_json")))){JSONObject i=JSON.parseObject(JSON.toJSONString(obj));if(i.getLongValue("id")==line)qty+=i.getLongValue("unshipped");}return qty;}
 public long refundedQty(long oid,long line){long qty=0;for(Map<String,Object> c:s.jdbc().queryForList("select items_json from shop_case where order_id=? and status='refunded'",oid))for(Object obj:JSON.parseArray(str(c.get("items_json")))){JSONObject i=JSON.parseObject(JSON.toJSONString(obj));if(i.getLongValue("id")==line)qty+=i.getLongValue("quantity");}return qty;}
 public List<Map<String,Object>> cases(Long uid){return uid==null?s.jdbc().queryForList("select c.*,o.order_no,o.channel,p.mode payment_mode"+ShopQueryFields.fields("o.member_id")+" from shop_case c join shop_order o on o.id=c.order_id left join shop_payment p on p.order_id=o.id where 1=1"+s.officialOrder("o.id")+" order by c.id desc"):s.jdbc().queryForList("select c.*,o.order_no,o.channel,p.mode payment_mode from shop_case c join shop_order o on o.id=c.order_id left join shop_payment p on p.order_id=o.id where "+s.companyOrderScope(uid)+s.officialOrder("o.id")+" order by c.id desc");}
 private boolean active(long oid){return s.jdbc().queryForObject("select count(*) from shop_case where order_id=? and status not in ('refunded','completed','rejected')",Long.class,oid)>0;}
 private boolean received(Map<String,Object> parcel){return Boolean.TRUE.equals(parcel.get("received"))||"1".equals(str(parcel.get("received")));}
 private void attachRefundCandidates(List<Map<String,Object>> items,List<Map<String,Object>> parcels,List<Map<String,Object>> cases){
  for(Map<String,Object> item:items){long id=number(item.get("id")),unknown=0;Map<Long,Long> used=new HashMap<>();
   for(Map<String,Object> c:cases)if("refunded".equals(c.get("status")))for(Object value:JSON.parseArray(str(c.get("items_json")))){JSONObject old=JSON.parseObject(JSON.toJSONString(value));if(old.getLongValue("id")!=id)continue;long linked=0;JSONArray links=old.getJSONArray("shipmentRefunds");if(links!=null)for(Object link:links){JSONObject part=JSON.parseObject(JSON.toJSONString(link));long pid=part.getLongValue("shipmentId"),qty=part.getLongValue("quantity");used.put(pid,used.getOrDefault(pid,0L)+qty);linked+=qty;}unknown+=Math.max(0,old.getLongValue("quantity")-old.getLongValue("unshipped")-linked);}
   JSONArray candidates=new JSONArray();for(Map<String,Object> parcel:parcels)for(Object value:JSON.parseArray(str(parcel.get("items_json")))){JSONObject line=JSON.parseObject(JSON.toJSONString(value));if(line.getLongValue("id")!=id)continue;long parcelId=number(parcel.get("id")),qty=line.getLongValue("quantity"),already=used.getOrDefault(parcelId,0L),left=Math.max(0,qty-already-unknown);if(left<=0)continue;JSONObject part=new JSONObject();part.put("shipmentId",parcelId);part.put("carrier",parcel.get("carrier"));part.put("tracking",parcel.get("tracking"));part.put("quantity",qty);part.put("refunded_quantity",already);part.put("refundable_quantity",left);part.put("received",received(parcel));candidates.add(part);}
   item.put("refund_shipments",candidates);item.put("refund_shipment_selection_error",unknown>0?"历史退款未记录具体包裹，请联系客服核对剩余可退包裹":"");
  }
 }
 private Map<Long,Map<Long,Long>> refundedParcels(long oid){
  Map<Long,Map<Long,Long>> result=new HashMap<>();
  for(Map<String,Object> c:s.jdbc().queryForList("select items_json from shop_case where order_id=? and status='refunded'",oid))for(Object obj:JSON.parseArray(str(c.get("items_json")))){
   JSONObject item=JSON.parseObject(JSON.toJSONString(obj));JSONArray parcels=item.getJSONArray("shipmentRefunds");if(parcels==null)continue;
   for(Object value:parcels){JSONObject part=JSON.parseObject(JSON.toJSONString(value));Map<Long,Long> lines=result.computeIfAbsent(part.getLongValue("shipmentId"),key->new HashMap<>());long itemId=item.getLongValue("id");lines.put(itemId,lines.getOrDefault(itemId,0L)+part.getLongValue("quantity"));}
  }return result;
 }
 private boolean refundedParcel(Map<String,Object> parcel,Map<Long,Map<Long,Long>> refunded){
  Map<Long,Long> covered=refunded.getOrDefault(number(parcel.get("id")),Collections.emptyMap());
  for(Object obj:JSON.parseArray(str(parcel.get("items_json")))){JSONObject item=JSON.parseObject(JSON.toJSONString(obj));if(covered.getOrDefault(item.getLongValue("id"),0L)<item.getLongValue("quantity"))return false;}return true;
 }
 private boolean parcelHasActiveCase(long oid,Map<String,Object> parcel){
  Set<Long> items=new HashSet<>();for(Object obj:JSON.parseArray(str(parcel.get("items_json"))))items.add(JSON.parseObject(JSON.toJSONString(obj)).getLongValue("id"));
  for(Map<String,Object> c:s.jdbc().queryForList("select type,items_json from shop_case where order_id=? and status not in ('refunded','completed','rejected')",oid))for(Object obj:JSON.parseArray(str(c.get("items_json")))){JSONObject line=JSON.parseObject(JSON.toJSONString(obj));if(!items.contains(line.getLongValue("id")))continue;if(Arrays.asList("refund","return").contains(str(c.get("type")))){if(line.getLongValue("quantity")==line.getLongValue("unshipped"))continue;JSONArray links=line.getJSONArray("shipmentRefunds");if(links!=null){for(Object value:links)if(JSON.parseObject(JSON.toJSONString(value)).getLongValue("shipmentId")==number(parcel.get("id")))return true;continue;}}return true;}
  return s.jdbc().queryForObject("select count(*) from shop_after_sale where order_id=? and status='pending'",Long.class,oid)>0;
 }
 // Freeze only a provable parcel attribution. A partial refund across several candidate
 // parcels is ambiguous without a buyer selection; legacy cases retain conservative handling.
 private void snapshotRefundParcels(long oid,JSONArray selected,JSONArray input){
  List<Map<String,Object>> parcels=shipmentRows(oid);Map<Long,Map<Long,Long>> prior=refundedParcels(oid);Map<Long,Long> ambiguous=new HashMap<>();
  for(Map<String,Object> c:s.jdbc().queryForList("select items_json from shop_case where order_id=? and status='refunded'",oid))for(Object obj:JSON.parseArray(str(c.get("items_json")))){
   JSONObject item=JSON.parseObject(JSON.toJSONString(obj));long linked=0;JSONArray links=item.getJSONArray("shipmentRefunds");if(links!=null)for(Object value:links)linked+=JSON.parseObject(JSON.toJSONString(value)).getLongValue("quantity");
   long unassigned=Math.max(0,item.getLongValue("quantity")-item.getLongValue("unshipped")-linked),id=item.getLongValue("id");ambiguous.put(id,ambiguous.getOrDefault(id,0L)+unassigned);
  }
  for(Object obj:selected){JSONObject item=(JSONObject)obj;long id=item.getLongValue("id"),delivered=item.getLongValue("quantity")-item.getLongValue("unshipped");JSONObject requested=null;for(Object value:input){JSONObject line=JSON.parseObject(JSON.toJSONString(value));if(line.getLongValue("id")==id){requested=line;break;}}JSONArray candidates=new JSONArray();long total=0;
   for(Map<String,Object> parcel:parcels)for(Object value:JSON.parseArray(str(parcel.get("items_json")))){JSONObject line=JSON.parseObject(JSON.toJSONString(value));if(line.getLongValue("id")!=id)continue;long qty=Math.max(0,line.getLongValue("quantity")-prior.getOrDefault(number(parcel.get("id")),Collections.emptyMap()).getOrDefault(id,0L));if(qty<=0)continue;JSONObject part=new JSONObject();part.put("shipmentId",parcel.get("id"));part.put("quantity",qty);part.put("carrier",parcel.get("carrier"));part.put("tracking",parcel.get("tracking"));candidates.add(part);total+=qty;}
   if(requested!=null&&requested.containsKey("shipments")){
    JSONArray chosen=requested.getJSONArray("shipments");check(chosen!=null,"请选择需要退款的发货包裹");long assigned=0;Set<Long> seen=new HashSet<>();JSONArray links=new JSONArray();
    for(Object value:chosen){JSONObject part=JSON.parseObject(JSON.toJSONString(value));long parcelId=integer(part.get("shipmentId"),1,Long.MAX_VALUE,"退款包裹不正确"),qty=integer(part.get("quantity"),1,10000,"包裹退款数量必须为正整数");check(seen.add(parcelId),"退款包裹不能重复");JSONObject candidate=null;for(Object available:candidates){JSONObject row=(JSONObject)available;if(row.getLongValue("shipmentId")==parcelId){candidate=row;break;}}check(candidate!=null,"退款包裹不属于该订单商品或已全部退款");check(qty<=Math.max(0,candidate.getLongValue("quantity")-ambiguous.getOrDefault(id,0L)),"包裹退款数量超过剩余可退数量，请刷新后重试");JSONObject link=new JSONObject();link.put("shipmentId",parcelId);link.put("quantity",qty);link.put("carrier",candidate.get("carrier"));link.put("tracking",candidate.get("tracking"));links.add(link);assigned+=qty;
    }check(assigned==delivered,"包裹退款合计必须等于本次已发商品退款数量");if(delivered>0)item.put("shipmentRefunds",links);
   }else if(delivered>0&&ambiguous.getOrDefault(id,0L)==0){if(candidates.size()==1&&delivered<=total){candidates.getJSONObject(0).put("quantity",delivered);item.put("shipmentRefunds",candidates);}else if(delivered==total&&!candidates.isEmpty())item.put("shipmentRefunds",candidates);}
  }
 }
 private void validateRefundParcels(Map<String,Object> c){
  long oid=number(c.get("order_id"));Map<Long,Map<Long,Long>> prior=refundedParcels(oid);
  for(Object obj:JSON.parseArray(str(c.get("items_json")))){JSONObject item=JSON.parseObject(JSON.toJSONString(obj));JSONArray links=item.getJSONArray("shipmentRefunds");if(links==null)continue;long sum=0;Set<Long> seen=new HashSet<>();for(Object value:links){JSONObject part=JSON.parseObject(JSON.toJSONString(value));long parcelId=part.getLongValue("shipmentId"),qty=part.getLongValue("quantity"),sent=0;check(qty>0&&seen.add(parcelId),"售后包裹归属不正确，请核对后处理");Map<String,Object> parcel=s.one("select items_json from shop_shipment where id=? and order_id=?",parcelId,oid);for(Object row:JSON.parseArray(str(parcel.get("items_json")))){JSONObject line=JSON.parseObject(JSON.toJSONString(row));if(line.getLongValue("id")==item.getLongValue("id"))sent+=line.getLongValue("quantity");}check(qty<=sent-prior.getOrDefault(parcelId,Collections.emptyMap()).getOrDefault(item.getLongValue("id"),0L),"售后包裹可退数量已改变，请核对后处理");sum+=qty;}check(sum==item.getLongValue("quantity")-item.getLongValue("unshipped"),"售后包裹退款合计不正确，请核对后处理");}
 }
 @Transactional public void ship(long oid,JSONObject body,String who){
  Map<String,Object> o=s.one("select * from shop_order where id=? for update",oid);
  check(Arrays.asList("paid","shipping").contains(str(o.get("status"))),"当前订单不能发货");check(!active(oid),"请先处理该订单售后");
  check(s.jdbc().queryForObject("select count(*) from shop_after_sale where order_id=? and status='pending'",Long.class,oid)==0,"请先处理旧售后申请");
  String carrier=str(body.get("carrier")).trim(),tracking=str(body.get("tracking")).trim();check(!carrier.isEmpty()&&carrier.length()<=80&&!tracking.isEmpty()&&tracking.length()<=100,"请填写物流公司及运单号");
  check(s.jdbc().queryForObject("select count(*) from shop_shipment where order_id=? and carrier=? and tracking=?",Long.class,oid,carrier,tracking)==0,"此运单已记录，请勿重复发货");
  JSONArray input=body.getJSONArray("items"),picked=new JSONArray();long remaining=0;Set<Long> seen=new HashSet<>();
  List<Map<String,Object>> lines=lines(oid);if(input!=null)for(Object obj:input){JSONObject i=JSON.parseObject(JSON.toJSONString(obj));long id=integer(i.get("id"),1,Long.MAX_VALUE,"订单商品不正确");check(seen.add(id)&&lines.stream().anyMatch(l->number(l.get("id"))==id),"发货商品不属于此订单或重复");integer(i.get("quantity"),0,10000,"发货数量必须是整数");}
  for(Map<String,Object> l:lines){long id=number(l.get("id")),left=Math.max(0,number(l.get("quantity"))-shipped(oid,id)-unshippedRefunded(oid,id)),qty=input==null?left:0;if(input!=null)for(Object obj:input){JSONObject i=JSON.parseObject(JSON.toJSONString(obj));if(i.getLongValue("id")==id)qty=i.getLongValue("quantity");}check(qty<=left,"发货数量超过未发数量");if(qty>0){JSONObject x=new JSONObject();x.put("id",id);x.put("name",l.get("name"));x.put("spec",l.get("spec"));x.put("quantity",qty);picked.add(x);}remaining+=left-qty;}
  check(!picked.isEmpty(),"请选择本次发货数量");s.campaignShip(oid);long wid=s.shipWarehouse(oid,body.getLongValue("warehouseId"),picked,who);s.jdbc().update("insert into shop_shipment(order_id,carrier,tracking,items_json,warehouse_id) values(?,?,?,?,?)",oid,carrier,tracking,picked.toJSONString(),wid);s.jdbc().update("update shop_order set status=?,carrier=?,tracking=? where id=?",remaining>0?"shipping":"shipped",carrier,tracking,oid);s.event("order",oid,"分批发货",who);
 }
 public void checkApplicationWindow(Map<String,Object> o){JSONObject orderRules=JSON.parseObject(str(o.get("rules_json")));JSONObject loyalty=orderRules.getJSONObject("loyalty");long window=loyalty==null?15:loyalty.getLongValue("afterSaleDays");if(o.get("received_at")!=null)check((o.get("manual_after_sale_until")!=null&&timestamp(o.get("manual_after_sale_until")).getTime()>=System.currentTimeMillis())||System.currentTimeMillis()-timestamp(o.get("received_at")).getTime()<=window*86400000L,"已超过直接申请期限，请联系客服协助处理");}
 @Transactional public void apply(long uid,JSONObject b){long actor=uid;long oid=integer(b.get("orderId"),1,Long.MAX_VALUE,"订单不正确");Map<String,Object> o=s.companyOrder(uid,oid,"afterSale",true);uid=number(o.get("member_id"));check(Arrays.asList("paid","shipping","shipped","completed").contains(str(o.get("status"))),"当前订单不能申请售后");checkApplicationWindow(o);check(!active(oid),"该订单已有进行中的售后");check(s.jdbc().queryForObject("select count(*) from shop_after_sale where order_id=? and status='pending'",Long.class,oid)==0,"请先完成已有售后");String type=str(b.get("type"));check(Arrays.asList("refund","return","exchange","resend").contains(type),"请选择售后类型");if(!"refund".equals(type))check(!"paid".equals(o.get("status")),"未发货订单请申请退款");String reasonCode=str(b.getOrDefault("reasonCode","customer"));check(Arrays.asList("customer","merchant").contains(reasonCode),"请选择售后原因类型");JSONArray proofs=b.getJSONArray("proofs");if(proofs==null)proofs=new JSONArray();check(proofs.size()<=3,"最多上传3张售后凭证");for(Object proof:proofs)check(s.jdbc().queryForObject("select count(*) from shop_private_file where path=? and member_id=?",Long.class,str(proof),actor)>0,"请上传本人售后凭证");String reason=str(b.get("reason")).trim();check(reason.length()>=2&&reason.length()<=500,"请填写2至500字原因");JSONArray input=b.getJSONArray("items");check(input!=null&&!input.isEmpty(),"请选择售后商品数量");JSONArray selected=new JSONArray();Set<Long> seen=new HashSet<>();long amount=0,cumulative=0;
  Map<Long,Long> allocated=new HashMap<>();for(Map<String,Object> l:lines(oid)){long value=number(l.get("price"))*number(l.get("quantity"));long next=cumulative+value;long net=share(next,number(o.get("amount")),number(o.get("subtotal")))-share(cumulative,number(o.get("amount")),number(o.get("subtotal")));allocated.put(number(l.get("id")),l.get("net_amount")==null?net:number(l.get("net_amount")));cumulative=next;}
  for(Object obj:input){JSONObject i=JSON.parseObject(JSON.toJSONString(obj));long id=integer(i.get("id"),1,Long.MAX_VALUE,"商品不正确"),qty=integer(i.get("quantity"),1,10000,"售后数量必须为正整数");check(seen.add(id),"请合并重复商品");Map<String,Object> l=s.one("select * from shop_order_item where id=? and order_id=?",id,oid);long used=refundedQty(oid,id),total=number(l.get("quantity"));check(qty+used<=total,"售后数量超过剩余可退数量");long unshipped=Math.max(0,total-shipped(oid,id)-unshippedRefunded(oid,id));if(!"refund".equals(type))check(qty<=total-used-unshipped,"退货、换货或补发数量不能超过已发且未退数量");long release="refund".equals(type)?Math.min(qty,unshipped):0;
   long net=allocated.get(id);amount+=share(used+qty,net,total)-share(used,net,total);JSONObject x=new JSONObject();x.put("id",id);x.put("productId",l.get("product_id"));x.put("quantity",qty);x.put("unshipped",release);x.put("name",l.get("name"));x.put("spec",l.get("spec"));if(Arrays.asList("exchange","resend").contains(type)){for(Map<String,Object> prior:s.jdbc().queryForList("select id,items_json from shop_case where order_id=? and type in ('exchange','resend') and status='completed' order by id desc",oid)){boolean found=false;for(Object old:JSON.parseArray(str(prior.get("items_json"))))if(JSON.parseObject(JSON.toJSONString(old)).getLongValue("id")==id){x.put("parentCaseId",prior.get("id"));found=true;break;}if(found)break;}}selected.add(x);}
  if(Arrays.asList("refund","return").contains(type))snapshotRefundParcels(oid,selected,input);
  long remainingQty=0;for(Map<String,Object> line:lines(oid))remainingQty+=number(line.get("quantity"))-refundedQty(oid,number(line.get("id")));long shippingFee=Arrays.asList("refund","return").contains(type)?s.shippingRefundFee(b,o,selected,remainingQty):0;if(Arrays.asList("exchange","resend").contains(type))amount=0;amount+=shippingFee;s.jdbc().update("insert into shop_case(order_id,member_id,type,status,items_json,amount,reason,shipping_amount) values(?,?,?,'pending',?,?,?,?)",oid,uid,type,selected.toJSONString(),amount,reason,shippingFee);long caseId=s.jdbc().queryForObject("select last_insert_id()",Long.class);s.jdbc().update("update shop_case set reason_code=?,return_shipping_payer=?,proofs_json=? where id=?",reasonCode,reasonCode,proofs.toJSONString(),caseId);s.orderReceived(oid);s.event("order",oid,"提交商品售后",str(actor));
 }
 @Transactional public void returnParcel(long uid,long id,JSONObject b){Map<String,Object> c=s.companyCase(uid,id,"afterSale",true);check("awaiting_return".equals(c.get("status")),"当前无需寄回");check(c.get("return_due_at")==null||timestamp(c.get("return_due_at")).getTime()>=System.currentTimeMillis(),"寄回期限已过，请联系客服申请延长后寄回");String carrier=str(b.get("carrier")).trim(),tracking=str(b.get("tracking")).trim();check(carrier.length()>0&&carrier.length()<=80&&tracking.length()>0&&tracking.length()<=100,"请填写寄回物流公司和运单号");s.jdbc().update("update shop_case set status='returned',return_carrier=?,return_tracking=? where id=?",carrier,tracking,id);}
 @Transactional public void handle(long id,JSONObject b,String who){long oid=number(s.one("select order_id from shop_case where id=?",id).get("order_id"));s.one("select id from shop_member where id=(select member_id from shop_order where id=?) for update",oid);Map<String,Object> o=s.one("select * from shop_order where id=? for update",oid);Map<String,Object> c=s.one("select * from shop_case where id=? for update",id);String action=str(b.get("action")),state=str(c.get("status")),type=str(c.get("type")),note=str(b.get("note")).trim();check(note.length()>0&&note.length()<=500,"请填写处理说明");String next=null;
  if("reject".equals(action)){check("pending".equals(state),"仅待审核申请可以驳回");next="rejected";}
  else if("approve".equals(action)){check("pending".equals(state),"申请已处理");if("refund".equals(type)){if(s.queueBankRefund(c,o))next="awaiting_refund";else{refund(c,o);next="refunded";}}else if("resend".equals(type))next="awaiting_reship";else{String address=str(b.get("returnAddress")).trim();check(address.length()>=5&&address.length()<=500,"请填写完整寄回地址和联系方式");JSONObject saved=JSON.parseObject(str(o.get("rules_json"))).getJSONObject("loyalty");long days=saved==null?7:saved.getLongValue("returnDays");if(days<=0)days=7;s.jdbc().update("update shop_case set return_address=?,return_due_at=date_add(now(),interval ? day) where id=?",address,days,id);next="awaiting_return";}}
  else if("extend".equals(action)){check("awaiting_return".equals(state),"只有待寄回申请可延长寄回期限");long days=integer(b.getOrDefault("days",7),1,365,"延长天数应为1至365");s.jdbc().update("update shop_case set return_due_at=date_add(now(),interval ? day) where id=?",days,id);next="awaiting_return";}
  else if("received".equals(action)){check("returned".equals(state),"请等待用户填写寄回运单");s.returnWarehouse(c,b.getLongValue("warehouseId"),who);next="inspecting";}
  else if("inspect".equals(action)){check("inspecting".equals(state),"请先登记退回商品");s.inspectWarehouse(c,b,who);if("return".equals(type)){if(s.queueBankRefund(c,o))next="awaiting_refund";else{refund(c,o);next="refunded";}}else next="awaiting_reship";}
  else if("reship".equals(action)){check("awaiting_reship".equals(state),"当前不能补发或换货");String carrier=str(b.get("carrier")).trim(),tracking=str(b.get("tracking")).trim();check(!carrier.isEmpty()&&carrier.length()<=80&&!tracking.isEmpty()&&tracking.length()<=100,"请填写换补发运单");s.reshipWarehouse(c,b.getLongValue("warehouseId"),who);s.jdbc().update("update shop_case set replacement_carrier=?,replacement_tracking=? where id=?",carrier,tracking,id);next="reshipped";}
  check(next!=null,"无效售后操作");s.jdbc().update("update shop_case set status=?,note=? where id=?",next,note,id);reconcile(oid);s.event("case",id,action,who);
 }
 @Transactional public void finishBankRefund(long id,String who){Map<String,Object> first=s.one("select order_id from shop_case where id=?",id);long oid=number(first.get("order_id"));Map<String,Object> owner=s.one("select member_id from shop_order where id=?",oid);s.one("select id from shop_member where id=? for update",owner.get("member_id"));Map<String,Object> o=s.one("select * from shop_order where id=? for update",oid);Map<String,Object> c=s.one("select * from shop_case where id=? for update",id);if("refunded".equals(c.get("status")))return;check("awaiting_refund".equals(c.get("status")),"售后未进入待退款");check(s.jdbc().queryForObject("select count(*) from shop_bank_refund where case_id=? and status='confirmed'",Long.class,id)==1,"财务尚未确认退款");refund(c,o);s.jdbc().update("update shop_case set status='refunded' where id=?",id);reconcile(oid);s.event("case",id,"财务核实对公退款完成",who);}
 @Transactional public void finishWechatRefund(long id){Map<String,Object> first=s.one("select order_id from shop_case where id=?",id);long oid=number(first.get("order_id"));Map<String,Object> o=s.lockWechatOrder(oid);Map<String,Object> c=s.one("select * from shop_case where id=? for update",id);if("refunded".equals(c.get("status")))return;check("awaiting_refund".equals(c.get("status"))&&s.wechatRefundConfirmed(id),"微信退款尚未确认");refund(c,o);s.jdbc().update("update shop_case set status='refunded' where id=?",id);reconcile(oid);s.event("case",id,"微信原路退款确认完成","微信支付");}
 private void refund(Map<String,Object> c,Map<String,Object> o){
  validateRefundParcels(c);
  check(s.wechatRefundConfirmed(number(c.get("id")))||s.isDemo()||s.bankStarted(number(o.get("id")))||s.creditOrder(number(o.get("id")))||s.exchangeOrder(number(o.get("id")))||s.walletPayment(number(o.get("id")))||s.rebatePayment(number(o.get("id"))),"该订单暂不支持在线退款，请联系财务核实");long oid=number(o.get("id")),total=number(o.get("refunded_amount"))+number(c.get("amount"));check(total<=number(o.get("amount")),"退款不能超过实付款");
  for(Object obj:JSON.parseArray(str(c.get("items_json")))){JSONObject i=JSON.parseObject(JSON.toJSONString(obj));long release=i.getLongValue("unshipped");if(release>0)s.inventory(i.getLongValue("productId"),release,"case_refund_"+c.get("id"),"未发货售后释放库存","系统");}
  s.recordShippingRefund(c,o);s.jdbc().update("update shop_order set refunded_amount=? where id=?",total,oid);s.returnOrderCoupon(oid);s.finance("refund","case_"+c.get("id"),oid,number(c.get("amount")),0);
  List<Map<String,Object>> commissions=s.jdbc().queryForList("select * from shop_commission where order_id=? for update",oid);String commissionNote=s.jdbc().queryForObject("select count(*) from shop_payment where order_id=? and mode='simulation'",Long.class,oid)>0?"非实收退款扣回佣金":"订单退款扣回佣金";
  for(Map<String,Object> comm:commissions){long original=comm.get("original_amount")==null?number(comm.get("amount")):number(comm.get("original_amount"));long remaining=number(o.get("amount"))==0?0:share(original,number(o.get("amount"))-total,number(o.get("amount")));long delta=remaining-number(comm.get("amount"));s.jdbc().update("update shop_commission set original_amount=?,amount=? where id=?",original,remaining,comm.get("id"));if(delta!=0)s.jdbc().update("insert into shop_commission_event(member_id,order_id,delta,event_key,note) values(?,?,?,?,?)",comm.get("member_id"),oid,delta,"refund_"+c.get("id"),commissionNote);}
 }
 private void reconcile(long oid){
  Map<String,Object> o=s.one("select * from shop_order where id=?",oid);long ordered=0,refunded=0,left=0,sent=0;
  for(Map<String,Object> l:lines(oid)){long id=number(l.get("id")),qty=number(l.get("quantity")),shipped=shipped(oid,id);ordered+=qty;refunded+=refundedQty(oid,id);sent+=shipped;left+=Math.max(0,qty-shipped-unshippedRefunded(oid,id));}
  String state;if(refunded==ordered)state="refunded";else if(left>0)state=sent>0?"shipping":"paid";else{List<Map<String,Object>> parcels=shipments(oid);Map<Long,Map<Long,Long>> covered=refundedParcels(oid);boolean received=parcels.isEmpty()?"completed".equals(o.get("status")):parcels.stream().allMatch(p->received(p)||refundedParcel(p,covered));state=received?"completed":"shipped";}
  s.jdbc().update("update shop_order set status=? where id=?",state,oid);s.orderReceived(oid);if("refunded".equals(state)){s.returnOrderCoupon(oid);s.jdbc().update("update shop_commission set status='reversed' where order_id=?",oid);}
 }
 @Transactional public void autoReceive(long oid,long parcelId){Map<String,Object> o=s.one("select * from shop_order where id=? for update",oid);if(!Arrays.asList("shipping","shipped").contains(o.get("status"))||active(oid))return;JSONObject r=JSON.parseObject(str(o.get("rules_json"))).getJSONObject("loyalty");if(r==null||!r.getBooleanValue("autoReceive"))return;Map<String,Object> p=s.one("select * from shop_shipment where id=? and order_id=? for update",parcelId,oid);long days=r.getLongValue("receiveDays");if(days<=0)days=15;if(received(p)||refundedParcel(p,refundedParcels(oid))||System.currentTimeMillis()-timestamp(p.get("created_at")).getTime()<days*86400000L)return;s.jdbc().update("update shop_shipment set received=1,received_at=now() where id=?",parcelId);reconcile(oid);s.event("order",oid,"按原订单设置自动确认该批次收货","系统");}
 @Transactional public void receiveParcel(long uid,long oid,long parcelId){Map<String,Object> o=s.companyOrder(uid,oid,"receive",true);Map<String,Object> parcel=s.one("select * from shop_shipment where id=? and order_id=? for update",parcelId,oid);if(received(parcel))return;check(Arrays.asList("shipping","shipped").contains(str(o.get("status"))),"当前订单不能确认收货");check(!parcelHasActiveCase(oid,parcel),"该批次商品售后处理中，请先完成售后");check(!refundedParcel(parcel,refundedParcels(oid)),"该批次商品已全部退款，无需确认收货");s.jdbc().update("update shop_shipment set received=1,received_at=coalesce(received_at,now()) where id=?",parcelId);reconcile(oid);s.event("order",oid,"确认批次收货",str(uid));}
 @Transactional public void receiveReplacement(long uid,long id){
  Map<String,Object> first=s.companyCase(uid,id,"afterSale",false);long oid=number(first.get("order_id"));s.one("select id from shop_order where id=? for update",oid);Map<String,Object> c=s.companyCase(uid,id,"afterSale",true);if("completed".equals(c.get("status")))return;check("reshipped".equals(c.get("status")),"换补发商品尚未寄出");s.jdbc().update("update shop_case set status='completed' where id=?",id);
  Map<Long,Long> covered=new HashMap<>();for(Object x:JSON.parseArray(str(c.get("items_json")))){JSONObject item=JSON.parseObject(JSON.toJSONString(x));covered.put(item.getLongValue("id"),item.getLongValue("quantity"));}Map<Long,Map<Long,Long>> refunds=refundedParcels(oid);
  for(Map<String,Object> parcel:shipmentRows(oid)){
   if(received(parcel)||refundedParcel(parcel,refunds))continue;boolean all=true;Map<Long,Long> required=new HashMap<>(),already=refunds.getOrDefault(number(parcel.get("id")),Collections.emptyMap());
   for(Object x:JSON.parseArray(str(parcel.get("items_json")))){JSONObject item=JSON.parseObject(JSON.toJSONString(x));long itemId=item.getLongValue("id"),qty=Math.max(0,item.getLongValue("quantity")-already.getOrDefault(itemId,0L));required.put(itemId,qty);if(covered.getOrDefault(itemId,0L)<qty)all=false;}
   if(all){for(Map.Entry<Long,Long> item:required.entrySet())covered.put(item.getKey(),covered.getOrDefault(item.getKey(),0L)-item.getValue());s.jdbc().update("update shop_shipment set received=1,received_at=coalesce(received_at,now()) where id=?",parcel.get("id"));}
  }reconcile(oid);s.event("case",id,"确认换补发收货",str(uid));
 }
}
