package com.ruoyi.web.controller.shop;
import java.util.*;
import com.alibaba.fastjson2.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import static com.ruoyi.web.controller.shop.ShopService.*;
@Service
public class ShopCredit {
 @Autowired @Lazy ShopService s; @Autowired @Lazy ShopCompany company; @Autowired @Lazy ShopBank bank;
 private Map<String,Object> lock(long cid){s.jdbc().update("insert ignore into shop_credit_account(company_id) values(?)",cid);return s.one("select * from shop_credit_account where company_id=? for update",cid);}
 private long occupied(long cid){return s.jdbc().queryForObject("select coalesce(sum(case when state='reserved' then amount when state='active' then greatest(0,amount-repaid-refunded) else 0 end),0) from shop_credit_order where company_id=?",Long.class,cid);}
 public boolean exists(long oid){return s.jdbc().queryForObject("select count(*) from shop_credit_order where order_id=?",Long.class,oid)>0;}
 @Transactional public Map<String,Object> account(long uid){Map<String,Object> c=company.historyContext(uid);long cid=number(c.get("id"));Map<String,Object> a=lock(cid);a.put("bank",bank.settings());a.put("occupied",occupied(cid));a.put("available",Math.max(0,number(a.get("credit_limit"))-number(a.get("occupied"))));a.put("bills",s.jdbc().queryForList("select cr.*,o.order_no,greatest(0,cr.amount-cr.repaid-cr.refunded) outstanding,cr.due_at<now() overdue from shop_credit_order cr join shop_order o on o.id=cr.order_id where cr.company_id=? order by cr.due_at,cr.order_id",cid));a.put("repayments",s.jdbc().queryForList("select id,order_id,amount,status,confirmed_amount,note,created_at from shop_credit_repayment where company_id=? order by id desc",cid));return a;}
 @Transactional public void configure(long cid,JSONObject b,String who){s.one("select id from shop_company where id=?",cid);check(s.jdbc().queryForObject("select count(*) from shop_company_member m join shop_credentials c on c.member_id=m.member_id where m.company_id=? and c.username=?",Long.class,cid,who)==0,"不能审批本人所在企业的授信，请交给另一名授权财务");lock(cid);long limit=integer(b.get("creditLimit"),0,100000000000L,"额度必须为正确的整数分"),days=integer(b.get("termDays"),1,365,"账期为1至365天");String note=str(b.get("note")).trim();check(!note.isEmpty()&&note.length()<=300,"请填写授信审批或调整依据");s.jdbc().update("update shop_credit_account set credit_limit=?,term_days=?,updated_at=now() where company_id=?",limit,days,cid);s.event("credit",cid,"批准/调整额度为 "+limit+"分，账期 "+days+"天。"+note,who);}
 public List<Map<String,Object>> admin(){return s.jdbc().queryForList("select c.id,c.name,coalesce(a.credit_limit,0) credit_limit,coalesce(a.term_days,30) term_days,coalesce((select sum(case when cr.state='reserved' then cr.amount when cr.state='active' then greatest(0,cr.amount-cr.repaid-cr.refunded) else 0 end) from shop_credit_order cr where cr.company_id=c.id),0) occupied"+ShopQueryFields.fields("c.owner_id")+" from shop_company c left join shop_credit_account a on a.company_id=c.id order by c.id desc");}
 public void quote(long uid,JSONObject b,Map<String,Object> q){if(!"credit".equals(b.getString("paymentMethod")))return;check("B".equals(b.getString("channel")),"账期付款仅用于企业采购");check(!b.getBooleanValue("useBalance")&&!b.getBooleanValue("usePoints"),"账期采购不混用个人余额和积分");Map<String,Object> a=account(uid);check(number(q.get("amount"))<=number(a.get("available")),"企业可用赊购额度不足");check(s.jdbc().queryForObject("select count(*) from shop_credit_order where company_id=? and state='active' and amount>repaid+refunded and due_at<now()",Long.class,a.get("company_id"))==0,"企业有逾期账款，请先还款并等待核销");q.put("creditAvailable",a.get("available"));}
 public void reserve(long uid,long oid,JSONObject b,Map<String,Object> q){if(!"credit".equals(b.getString("paymentMethod")))return;long cid=number(company.context(uid).get("id"));Map<String,Object> a=lock(cid);quote(uid,b,q);s.jdbc().update("insert into shop_credit_order(order_id,company_id,amount,term_days) values(?,?,?,?)",oid,cid,q.get("amount"),a.get("term_days"));event(cid,oid,"reserve_"+oid,"reserve",number(q.get("amount")),"下单预占授信额度");}
 public void paid(long oid){if(!exists(oid))return;Map<String,Object> first=s.one("select company_id from shop_credit_order where order_id=?",oid);lock(number(first.get("company_id")));Map<String,Object> c=s.one("select * from shop_credit_order where order_id=? for update",oid);if("active".equals(c.get("state")))return;check("reserved".equals(c.get("state")),"授信占用状态已变化");check(s.jdbc().queryForObject("select count(*) from shop_credit_order where company_id=? and state='active' and amount>repaid+refunded and due_at<now()",Long.class,c.get("company_id"))==0,"企业有逾期账款，请先核销还款");s.jdbc().update("update shop_credit_order set state='active',due_at=date_add(now(),interval term_days day) where order_id=?",oid);event(number(c.get("company_id")),oid,"active_"+oid,"purchase",number(c.get("amount")),"负责人或财务确认账期采购，开始计算账期");}
 public void release(long oid){if(!exists(oid))return;Map<String,Object> first=s.one("select company_id from shop_credit_order where order_id=?",oid);lock(number(first.get("company_id")));Map<String,Object> c=s.one("select * from shop_credit_order where order_id=? for update",oid);if(!"reserved".equals(c.get("state")))return;s.jdbc().update("update shop_credit_order set state='cancelled' where order_id=?",oid);event(number(c.get("company_id")),oid,"cancel_"+oid,"release",number(c.get("amount")),"订单关闭释放预占额度");}
 public long excess(Map<String,Object> o,Map<String,Object> ca){long oid=number(o.get("id"));if(!exists(oid))return 0;lock(number(s.one("select company_id from shop_credit_order where order_id=?",oid).get("company_id")));Map<String,Object> c=s.one("select * from shop_credit_order where order_id=?",oid);long before=Math.max(0,number(c.get("refunded"))+number(c.get("repaid"))-number(c.get("amount")));long after=Math.max(0,number(o.get("refunded_amount"))+number(ca.get("amount"))+number(c.get("repaid"))-number(c.get("amount")));return after-before;}
 public void refund(long oid){if(!exists(oid))return;Map<String,Object> first=s.one("select company_id from shop_credit_order where order_id=?",oid);long cid=number(first.get("company_id"));lock(cid);Map<String,Object> c=s.one("select * from shop_credit_order where order_id=? for update",oid);long total=number(s.one("select refunded_amount from shop_order where id=?",oid).get("refunded_amount")),delta=total-number(c.get("refunded"));check(delta>=0,"账期退款金额异常");if(delta==0)return;s.jdbc().update("update shop_credit_order set refunded=? where order_id=?",total,oid);event(cid,oid,"refund_"+oid+"_"+total,"refund",Math.min(delta,Math.max(0,number(c.get("amount"))-number(c.get("repaid"))-number(c.get("refunded")))),"售后退款冲减原应收，已还部分由财务退回");}
 private void event(long cid,long oid,String key,String kind,long amount,String note){s.jdbc().update("insert into shop_credit_event(company_id,order_id,event_key,kind,amount,note) values(?,?,?,?,?,?)",cid,oid,key,kind,amount,note);}
 @Transactional public void repay(long uid,JSONObject b){Map<String,Object> c=company.historyContext(uid);check(Arrays.asList("owner","finance").contains(str(c.get("role"))),"还款由企业负责人或财务提交");long cid=number(c.get("id"));lock(cid);List<Map<String,Object>> retries=s.jdbc().queryForList("select * from shop_credit_repayment where submitted_by=? and request_key=?",uid,str(b.get("requestKey")));if(!retries.isEmpty()){Map<String,Object> prior=retries.get(0);boolean originalOldest="oldest".equals(prior.get("allocation_scope"));check(number(prior.get("amount"))==b.getLongValue("amount")&&str(prior.get("proof")).equals(str(b.get("proof")))&&str(prior.get("payer")).equals(str(b.get("payer")).trim())&&(originalOldest?b.getLongValue("orderId")==0:number(prior.get("order_id"))==b.getLongValue("orderId")),"重复请求的还款内容不一致");return;}long oid=b.getLongValue("orderId");boolean oldest=oid==0;if(oldest)oid=number(s.one("select order_id from shop_credit_order where company_id=? and state='active' and amount>repaid+refunded order by due_at,order_id limit 1",cid).get("order_id"));else integer(oid,1,Long.MAX_VALUE,"请选择要还款的账单");s.one("select order_id from shop_credit_order where order_id=? and company_id=? and state='active'",oid,cid);String key=str(b.get("requestKey")),proof=str(b.get("proof")),payer=str(b.get("payer")).trim();long amount=integer(b.get("amount"),1,10000000000L,"还款金额不正确");check(key.matches("[a-zA-Z0-9_-]{8,80}")&&payer.length()>=2&&payer.length()<=100,"请填写转账户名并重新提交");check(s.jdbc().queryForObject("select count(*) from shop_private_file where path=? and member_id=?",Long.class,proof,uid)>0,"请上传还款凭证");List<Map<String,Object>> prior=s.jdbc().queryForList("select * from shop_credit_repayment where submitted_by=? and request_key=?",uid,key);if(!prior.isEmpty()){Map<String,Object> p=prior.get(0);check(number(p.get("amount"))==amount&&number(p.get("order_id"))==oid&&proof.equals(p.get("proof")),"重复请求的还款内容不一致");return;}String account=s.accountAuditIdentity(uid);s.jdbc().update("insert into shop_credit_repayment(company_id,submitted_by,submitted_account,order_id,amount,proof,payer,request_key,allocation_scope) values(?,?,?,?,?,?,?,?,?)",cid,uid,account,oid,amount,proof,payer,key,oldest?"oldest":"specified");}
 @Transactional public void repayAssisted(long oid,JSONObject b,String who){Map<String,Object> o=s.one("select o.* from shop_order o join shop_member m on m.id=o.member_id where o.id=? and m.enabled=0",oid);long cid=number(o.get("company_id")),uid=number(o.get("member_id"));lock(cid);s.one("select order_id from shop_credit_order where order_id=? and company_id=? and state='active'",oid,cid);long amount=integer(b.get("amount"),1,10000000000L,"请填写还款金额");String proof=str(b.get("proof")),payer=str(b.get("payer")).trim(),key=str(b.get("requestKey"));check(payer.length()>=2&&payer.length()<=100&&key.matches("[a-zA-Z0-9_-]{8,80}"),"请填写转账户名");check(s.jdbc().queryForObject("select count(*) from shop_private_file where path=? and member_id=?",Long.class,proof,uid)>0,"请先上传该客户的还款凭证");s.jdbc().update("insert into shop_credit_repayment(company_id,submitted_by,submitted_account,order_id,amount,proof,payer,request_key,allocation_scope) values(?,?,?,?,?,?,?,?,'specified')",cid,uid,who,oid,amount,proof,payer,key);}
 public List<Map<String,Object>> repayments(){return s.jdbc().queryForList("select r.*,c.name company_name,o.order_no"+ShopQueryFields.fields("c.owner_id")+" from shop_credit_repayment r join shop_company c on c.id=r.company_id join shop_order o on o.id=r.order_id order by r.id desc");}
 @Transactional public void verify(long id,JSONObject b,String who){Map<String,Object> first=s.one("select * from shop_credit_repayment where id=?",id);long cid=number(first.get("company_id"));lock(cid);Map<String,Object> r=s.one("select * from shop_credit_repayment where id=? for update",id);check(!who.equals(r.get("submitted_account"))&&!s.accountMatchesReviewer(number(r.get("submitted_by")),who),"不能核销本人提交的还款");String action=b.getString("action"),note=str(b.get("note")).trim();check(Arrays.asList("confirmed","rejected").contains(action)&&!note.isEmpty()&&note.length()<=300,"请选择处理方式并填写核验依据");if(action.equals(r.get("status")))return;check("pending".equals(r.get("status")),"还款凭证已处理");if("rejected".equals(action)){s.jdbc().update("update shop_credit_repayment set status='rejected',note=?,reviewer=? where id=?",note,who,id);return;}check(s.jdbc().queryForObject("select count(*) from shop_case where order_id=? and status not in ('refunded','completed','rejected')",Long.class,r.get("order_id"))==0,"请先处理该账单进行中的售后，再核销还款");long amount=integer(b.get("confirmedAmount"),1,10000000000L,"请填写银行实际到账金额");String ref=str(b.get("bankReference")).trim();check(ref.length()>=4&&ref.length()<=120,"请填写银行流水号");bank.reference(ref,"credit_repayment_"+id,"in");s.jdbc().update("update shop_credit_repayment set status='confirmed',confirmed_amount=?,bank_reference=?,note=?,reviewer=? where id=?",amount,ref,note,who,id);long oid=number(r.get("order_id"));List<Map<String,Object>> bills="oldest".equals(r.get("allocation_scope"))?s.jdbc().queryForList("select * from shop_credit_order where company_id=? and state='active' and amount>repaid+refunded order by due_at,order_id for update",cid):s.jdbc().queryForList("select * from shop_credit_order where order_id=? for update",oid);long remaining=amount;for(Map<String,Object> bill:bills){if(remaining==0)break;long billId=number(bill.get("order_id"));check(s.jdbc().queryForObject("select count(*) from shop_case where order_id=? and status not in ('refunded','completed','rejected')",Long.class,billId)==0,"待还账单有进行中的售后，请先处理后核销");long used=Math.min(remaining,Math.max(0,number(bill.get("amount"))-number(bill.get("repaid"))-number(bill.get("refunded"))));s.jdbc().update("update shop_credit_order set repaid=repaid+? where order_id=?",used,billId);event(cid,billId,"repay_"+id+"_"+billId,"repayment",used,"财务核验还款，释放对应授信额度");remaining-=used;}s.finance("bank_received","credit_received_"+id,oid,amount,0);if(remaining>0)bank.queueExternal(oid,"credit_extra_"+id,remaining,"还款超过剩余应收，待财务退回");s.event("credit",cid,"核销还款 "+id,who);}
}
