package com.ruoyi.web.controller.shop;
import java.util.*;
import com.alibaba.fastjson2.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import static com.ruoyi.web.controller.shop.ShopService.*;
@Service
public class ShopBank {
 @Autowired @Lazy ShopService s; @Autowired @Lazy ShopWorkflow workflow;
 public void reference(String ref,String source,String direction){check(s.jdbc().queryForObject("select (select count(*) from shop_bank_receipt where bank_reference=?)+(select count(*) from shop_credit_repayment where bank_reference=?)+(select count(*) from shop_bank_refund where bank_reference=?)",Long.class,ref,ref,ref)==0,"该银行流水号已登记，不能重复核销");check(s.jdbc().queryForObject("select count(*) from shop_bank_movement where reference_no=?",Long.class,ref)==0,"该银行流水号已登记，不能重复核销");s.jdbc().update("insert into shop_bank_movement(reference_no,direction,source_key) values(?,?,?)",ref,direction,source);}
 public JSONObject settings(){return JSON.parseObject(str(s.one("select content from shop_config where config_key='bank-transfer'").get("content")));}
 @Transactional public void settings(JSONObject b,String who){boolean enabled=b.getBooleanValue("enabled");String company=str(b.get("companyName")).trim(),bank=str(b.get("bankName")).trim(),account=str(b.get("accountNumber")).trim();check(company.length()<=100&&bank.length()<=100&&account.length()<=80,"收款信息过长");if(enabled)check(!company.isEmpty()&&!bank.isEmpty()&&account.matches("[0-9 -]{8,80}"),"启用前请填写真实收款户名、银行和账号");JSONObject r=new JSONObject();r.put("enabled",enabled);r.put("companyName",company);r.put("bankName",bank);r.put("accountNumber",account);r.put("waitHours",integer(b.get("waitHours"),1,168,"核验等待期为1至168小时"));s.jdbc().update("update shop_config set content=? where config_key='bank-transfer'",r.toJSONString());s.event("bank",0,"修改对公收款设置",who);}
 public boolean started(long oid){return s.jdbc().queryForObject("select count(*) from shop_bank_order where order_id=?",Long.class,oid)>0;}
 private Map<String,Object> lock(long oid){Map<String,Object> initial=s.one("select member_id from shop_order where id=?",oid);s.one("select id from shop_member where id=? for update",initial.get("member_id"));return s.one("select * from shop_order where id=? for update",oid);}
 @Transactional public Map<String,Object> info(long uid,long oid){s.companyOrder(uid,oid,"view",false);Map<String,Object> result=new HashMap<>();JSONObject config=settings();if(started(oid)){Object saved=s.one("select settings_json from shop_bank_order where order_id=?",oid).get("settings_json");if(saved!=null)config=JSON.parseObject(str(saved));}result.put("settings",config);result.put("receipts",s.jdbc().queryForList("select id,amount,payer,status,confirmed_amount,note,created_at from shop_bank_receipt where order_id=? order by id desc",oid));result.put("refunds",s.jdbc().queryForList("select id,amount,reason,status,created_at from shop_bank_refund where order_id=? order by id desc",oid));result.put("started",started(oid));return result;}
 @Transactional public void start(long uid,long oid){Map<String,Object> o=lock(oid);s.authorizeOrder(uid,o,"pay");check(!s.campaignOrder(oid),"拼团请使用普通付款");check("B".equals(o.get("channel")),"对公转账仅用于企业采购");check(!s.creditOrder(oid),"账期订单请在企业账单中还款");check("pending".equals(o.get("status")),"订单已不在待付款状态");if(started(oid))return;if(!s.closeWechatPayment(o))return;check(s.rebateUsed(oid)==0&&number(s.one("select wallet_amount from shop_order_funds where order_id=?",oid).get("wallet_amount"))==0,"对公转账不与余额或返利混付，请重新下单并关闭抵扣");check(Boolean.TRUE.equals(s.jdbc().queryForObject("select expires_at>now() from shop_order where id=?",Boolean.class,oid)),"订单已超时");check(number(s.one("select external_amount from shop_order_funds where order_id=?",oid).get("external_amount"))>0,"该订单无需额外转账，请使用余额完成付款");JSONObject config=settings();check(config.getBooleanValue("enabled"),"商家尚未启用对公转账");s.jdbc().update("insert into shop_bank_order(order_id,settings_json) values(?,?)",oid,config.toJSONString());s.jdbc().update("update shop_order set expires_at=date_add(now(),interval ? hour) where id=?",config.getLongValue("waitHours"),oid);s.event("order",oid,"选择对公转账，等待人工核验",str(uid));}
 @Transactional public void submit(long uid,long oid,JSONObject b){Map<String,Object> o=lock(oid);s.authorizeOrder(uid,o,"pay");check(started(oid)&&"pending".equals(o.get("status")),"请先选择对公转账，且订单须为待付款");check(Boolean.TRUE.equals(s.jdbc().queryForObject("select expires_at>now() from shop_order where id=?",Boolean.class,oid)),"核验等待期已结束，请联系财务处理");long amount=integer(b.get("amount"),1,10000000000L,"请填写正确转账金额");String key=str(b.get("requestKey")),proof=str(b.get("proof")),payer=str(b.get("payer")).trim();check(key.matches("[a-zA-Z0-9_-]{8,80}"),"请重新提交凭证");check(payer.length()>=2&&payer.length()<=100,"请填写转账户名");check(s.jdbc().queryForObject("select count(*) from shop_private_file where path=? and member_id=?",Long.class,proof,uid)>0,"请上传本人持有的转账凭证图片");List<Map<String,Object>> prior=s.jdbc().queryForList("select * from shop_bank_receipt where submitted_by=? and request_key=?",uid,key);if(!prior.isEmpty()){Map<String,Object> p=prior.get(0);check(number(p.get("order_id"))==oid&&number(p.get("amount"))==amount&&proof.equals(p.get("proof"))&&payer.equals(p.get("payer")),"重复请求的凭证内容不一致");return;}String account=s.accountAuditIdentity(uid);s.jdbc().update("insert into shop_bank_receipt(order_id,submitted_by,submitted_account,request_key,amount,proof,payer) values(?,?,?,?,?,?,?)",oid,uid,account,key,amount,proof,payer);s.event("order",oid,"提交对公转账凭证，未确认到账",str(uid));}
 public List<Map<String,Object>> receipts(){return s.jdbc().queryForList("select o.channel,r.*,o.order_no,o.status order_status,o.amount order_amount"+ShopQueryFields.fields("o.member_id")+" from shop_bank_receipt r join shop_order o on o.id=r.order_id order by r.id desc");}
 public List<Map<String,Object>> refunds(){return s.jdbc().queryForList("select o.channel,r.*,o.order_no"+ShopQueryFields.fields("o.member_id")+" from shop_bank_refund r join shop_order o on o.id=r.order_id order by r.id desc");}
 @Transactional public void review(long id,JSONObject b,String who){Map<String,Object> initial=s.one("select order_id from shop_bank_receipt where id=?",id);long oid=number(initial.get("order_id"));Map<String,Object> o=lock(oid);Map<String,Object> r=s.one("select * from shop_bank_receipt where id=? for update",id);check(!who.equals(r.get("submitted_account"))&&!s.accountMatchesReviewer(number(r.get("submitted_by")),who),"提交人不能核验本人凭证，请交给另一名财务");String action=b.getString("action"),note=str(b.get("note")).trim();check(Arrays.asList("confirmed","rejected").contains(action),"请选择确认收到款或退回补资料");if(action.equals(r.get("status")))return;check("pending".equals(r.get("status")),"凭证已处理");check(note.length()<=300,"说明最多300字");if("rejected".equals(action)){check(!note.isEmpty(),"请填写退回原因");s.jdbc().update("update shop_bank_receipt set status='rejected',note=?,reviewer=? where id=?",note,who,id);return;}
  long amount=integer(b.get("confirmedAmount"),1,10000000000L,"请填写银行实际到账金额");String reference=str(b.get("bankReference")).trim();check(reference.length()>=4&&reference.length()<=120,"请填写银行流水号");check(!note.isEmpty(),"请填写核验依据；异名或金额不符时说明原因");reference(reference,"receipt_"+id,"in");s.jdbc().update("update shop_bank_receipt set status='confirmed',confirmed_amount=?,bank_reference=?,note=?,reviewer=? where id=?",amount,reference,note,who,id);
  Map<String,Object> transfer=s.one("select * from shop_bank_order where order_id=? for update",oid);long before=number(transfer.get("confirmed"));s.jdbc().update("update shop_bank_order set confirmed=confirmed+? where order_id=?",amount,oid);long target=number(s.one("select external_amount from shop_order_funds where order_id=?",oid).get("external_amount"));
  boolean closed=!"pending".equals(o.get("status"));boolean expired=Boolean.TRUE.equals(s.jdbc().queryForObject("select expires_at<=now() from shop_order where id=?",Boolean.class,oid));
  if(closed||expired){queue(oid,null,"late_"+id,amount,"关闭或付款后收到的款项，待财务退回");if(expired&&"pending".equals(o.get("status")))s.expireOrder(oid);}
  else {long excess=Math.max(0,before+amount-target)-Math.max(0,before-target);if(excess>0)queue(oid,null,"over_"+id,excess,"超过订单所需款项，待财务退回");if(before+amount>=target)s.bankPayment(oid);}
  s.finance("bank_received","bank_received_"+id,oid,amount,0);s.event("order",oid,"核验收到对公款 "+amount+"分",who);
 }
 public void queueExternal(long oid,String key,long amount,String reason){queue(oid,null,key,amount,reason);}
 private void queue(long oid,Long caseId,String key,long amount,String reason){if(amount<=0)return;s.jdbc().update("insert ignore into shop_bank_refund(order_id,case_id,source_key,amount,reason) values(?,?,?,?,?)",oid,caseId,key,amount,reason);}
 public void close(long oid){if(!started(oid))return;long received=number(s.one("select confirmed from shop_bank_order where order_id=?",oid).get("confirmed"));long queued=s.jdbc().queryForObject("select coalesce(sum(amount),0) from shop_bank_refund where order_id=? and case_id is null",Long.class,oid);queue(oid,null,"close_"+oid,Math.max(0,received-queued),"订单关闭，已核验款项待退回");}
 public boolean queueCase(Map<String,Object> c,Map<String,Object> o){long oid=number(o.get("id"));if(s.creditOrder(oid)){long excess=s.creditRefundExcess(o,c);if(excess>0)queue(oid,number(c.get("id")),"case_"+c.get("id"),excess,"账期售后超过剩余应收，已还部分待财务退回");return excess>0;}if(!started(oid))return false;Map<String,Object> f=s.one("select * from shop_order_funds where order_id=?",oid);long total=number(o.get("refunded_amount"))+number(c.get("amount"));long wallet=ShopCommerce.portion(total,number(f.get("wallet_amount")),number(o.get("amount")))-number(f.get("refunded_wallet"));long external=number(c.get("amount"))-wallet;if(external<=0)return false;queue(oid,number(c.get("id")),"case_"+c.get("id"),external,"售后审核通过，等待财务对公退款");return true;}
 @Transactional public void refund(long id,JSONObject b,String who){Map<String,Object> initial=s.one("select order_id from shop_bank_refund where id=?",id);long oid=number(initial.get("order_id"));lock(oid);Map<String,Object> r=s.one("select * from shop_bank_refund where id=? for update",id);if("confirmed".equals(r.get("status")))return;String reference=str(b.get("bankReference")).trim(),note=str(b.get("note")).trim();check(reference.length()>=4&&reference.length()<=120&&!note.isEmpty()&&note.length()<=300,"请填写实际退款流水号和核对说明");reference(reference,"refund_"+id,"out");s.jdbc().update("update shop_bank_refund set status='confirmed',bank_reference=?,note=?,operator_name=? where id=?",reference,note,who,id);if(r.get("case_id")!=null){workflow.finishBankRefund(number(r.get("case_id")),who);s.finance("bank_outcome","bank_outcome_"+id,oid,number(r.get("amount")),0);}else s.finance("bank_return","bank_return_"+id,oid,number(r.get("amount")),0);s.event("order",oid,"财务确认对公退款",who);}
}
