package com.ruoyi.web.controller.shop;
import java.util.*;import java.time.*;import com.alibaba.fastjson2.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.context.annotation.Lazy;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopInvoice {
 @Autowired @Lazy ShopService s;
 @Transactional public List<Map<String,Object>> list(long uid){List<Map<String,Object>> rows=s.jdbc().queryForList("select i.*,o.order_no,o.channel,o.amount-o.refunded_amount available_amount from shop_invoice i join shop_order o on o.id=i.order_id where "+s.companyOrderScope(uid)+s.officialOrder("o.id")+" order by i.id desc");for(Map<String,Object> r:rows)r.put("files",files(number(r.get("id"))));return rows;}
 public List<Map<String,Object>> files(long id){return s.jdbc().queryForList("select id,original_name,invoice_number,amount,file_kind,note,created_at from shop_invoice_file where invoice_id=? order by id",id);}
 @Transactional public Map<String,Object> apply(long uid,JSONObject b){long oid=integer(b.get("orderId"),1,Long.MAX_VALUE,"请选择订单");Map<String,Object> o=s.companyOrder(uid,oid,"invoice",true);check(o.get("paid_at")!=null,"未付款订单不能申请发票");long amount=number(o.get("amount"))-number(o.get("refunded_amount"));check(amount>0,"订单已全额退款，没有可申请金额");String kind=b.getString("titleKind"),title=str(b.get("title")).trim(),tax=str(b.get("taxNumber")).trim(),email=str(b.get("email")).trim();check(Arrays.asList("personal","company").contains(kind),"请选择个人或企业抬头");check(title.length()>=2&&title.length()<=150,"请填写正确的发票抬头");check(!"company".equals(kind)||tax.matches("[A-Z0-9]{15,20}"),"请填写企业税号");check(email.length()<=150&&email.matches("[^\\s@]+@[^\\s@]+\\.[^\\s@]+"),"请填写正确邮箱");if("personal".equals(kind))tax="";List<Map<String,Object>> old=s.jdbc().queryForList("select * from shop_invoice where order_id=? for update",oid);if(!old.isEmpty()){Map<String,Object> i=old.get(0);check(Arrays.asList("requested","rejected").contains(str(i.get("status"))),"已开具的票据请联系财务处理，不能直接改抬头");s.jdbc().update("update shop_invoice set title_kind=?,title=?,tax_number=?,email=?,status='requested',requested_amount=?,note='',updated_at=now() where id=?",kind,title,tax,email,amount,i.get("id"));return s.one("select * from shop_invoice where id=?",i.get("id"));}
 LocalDate due=LocalDate.now();for(int days=0;days<3;){due=due.plusDays(1);if(due.getDayOfWeek()!=DayOfWeek.SATURDAY&&due.getDayOfWeek()!=DayOfWeek.SUNDAY)days++;}s.jdbc().update("insert into shop_invoice(order_id,requested_by,title_kind,title,tax_number,email,requested_amount,due_date) values(?,?,?,?,?,?,?,?)",oid,uid,kind,title,tax,email,amount,due.toString());s.event("order",oid,"申请发票",str(uid));return s.one("select * from shop_invoice where order_id=?",oid);}
 public List<Map<String,Object>> admin(){List<Map<String,Object>> rows=s.jdbc().queryForList("select o.channel,i.*,o.order_no,o.amount-o.refunded_amount available_amount"+ShopQueryFields.fields("o.member_id")+" from shop_invoice i join shop_order o on o.id=i.order_id where 1=1"+s.officialOrder("o.id")+" order by i.id desc");for(Map<String,Object> r:rows)r.put("files",files(number(r.get("id"))));return rows;}
 @Transactional public void reject(long id,String note,String who){check(note!=null&&note.trim().length()>=2&&note.length()<=500,"请说明需要修改的内容");Map<String,Object> i=s.one("select * from shop_invoice where id=? for update",id);check("requested".equals(i.get("status")),"当前申请不能退回修改");s.jdbc().update("update shop_invoice set status='rejected',note=?,updated_at=now() where id=?",note,id);s.event("invoice",id,"退回修改："+note,who);}
 @Transactional public void attach(long id,String path,String filename,JSONObject b,String who){Map<String,Object> first=s.one("select order_id from shop_invoice where id=?",id);Map<String,Object> o=s.one("select * from shop_order where id=? for update",first.get("order_id"));Map<String,Object> i=s.one("select * from shop_invoice where id=? for update",id);String state=str(i.get("status"));check(Arrays.asList("requested","adjustment_required").contains(state),"当前发票不在待处理状态");long available=number(o.get("amount"))-number(o.get("refunded_amount"));check(integer(b.get("expectedAvailable"),0,Long.MAX_VALUE,"请刷新可开金额")==available,"订单退款金额已变化，请重新核对");long amount=integer(b.get("amount"),"adjustment_required".equals(state)?0:1,available,"票据金额不能超过当前可开金额");String no=str(b.get("invoiceNumber")).trim(),note=str(b.get("note")).trim();check(!no.isEmpty()&&no.length()<=100&&note.length()>=2&&note.length()<=500,"请填写票据号码及实际处理说明");String kind="adjustment_required".equals(state)?"adjustment":"original";s.jdbc().update("insert into shop_invoice_file(invoice_id,path,original_name,invoice_number,amount,file_kind,note,operator_name) values(?,?,?,?,?,?,?,?)",id,path,filename,no,amount,kind,note,who);s.jdbc().update("update shop_invoice set status='issued',issued_amount=?,requested_amount=?,note=?,updated_at=now() where id=?",amount,available,note,id);s.event("invoice",id,"上传财务开具的票据文件："+kind,who);}
 public void refund(long oid){List<Map<String,Object>> rows=s.jdbc().queryForList("select * from shop_invoice where order_id=? for update",oid);if(rows.isEmpty())return;Map<String,Object> i=rows.get(0);long remaining=number(s.one("select amount-refunded_amount remaining from shop_order where id=?",oid).get("remaining"));if(remaining==number(i.get("requested_amount")))return;String state=str(i.get("status"));if("issued".equals(state)||"adjustment_required".equals(state))s.jdbc().update("update shop_invoice set status='adjustment_required',requested_amount=?,note='订单发生退款，请财务处理原票据并上传后续文件',updated_at=now() where id=?",remaining,i.get("id"));else s.jdbc().update("update shop_invoice set requested_amount=?,status=?,updated_at=now() where id=?",remaining,remaining==0?"cancelled":state,i.get("id"));}
 public Map<String,Object> file(long uid,long id){Map<String,Object> f=s.one("select f.*,i.order_id from shop_invoice_file f join shop_invoice i on i.id=f.invoice_id where f.id=?",id);s.companyOrder(uid,number(f.get("order_id")),"view",false);return f;}
 public Map<String,Object> adminFile(long id){return s.one("select * from shop_invoice_file where id=?",id);}
}
