package com.ruoyi.web.controller.shop;
import java.util.*;import com.alibaba.fastjson2.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.context.annotation.Lazy;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopPartner {
 @Autowired @Lazy ShopService s;
 public JSONObject settings(){JSONObject config=JSON.parseObject(str(s.one("select content from shop_config where config_key='partner'").get("content")));config.getJSONArray("tiers").getJSONObject(0).put("referenceAmount",0);config.put("entryMode","approved_distributor");return config;}
 @org.springframework.beans.factory.annotation.Value("${shop.test-data:false}") private boolean includeTestOrders;
 private String spend(String extra){return "select o.member_id,sum(greatest(0,o.amount-o.shipping_amount-o.refunded_amount+o.refunded_shipping_amount)) net_spend from shop_order o where o.channel='C' and coalesce(o.business_type,'retail') in ('retail','partner') and o.paid_at is not null and o.status in ('paid','shipping','shipped','completed','refunded') and (? or o.is_test=0) "+(s.isOfficialDisplay()?" and exists(select 1 from shop_payment p where p.order_id=o.id and p.mode<>'simulation') ":"")+" and "+extra+" group by o.member_id";}
 private JSONObject resolve(Map<String,Object> row,JSONObject config){
  long total=number(row.get("net_spend"));JSONArray tiers=config.getJSONArray("tiers");long upgradeAmount=tiers.getJSONObject(1).getLongValue("referenceAmount");
  boolean distributor="approved".equals(row.get("distributor_state"));int auto=distributor?(total>=upgradeAmount?2:1):0;
  String mode=str(row.get("mode"));if(mode.isEmpty())mode="auto";
  int tier="fixed".equals(mode)?(int)number(row.get("override_tier")):auto;
  boolean allowed=distributor&&flag(row.get("account_enabled"))&&Arrays.asList("auto","fixed").contains(mode)&&tier>=1&&tier<=3;
  JSONObject out=new JSONObject();out.put("enabled",allowed);out.put("distributor",distributor);out.put("applicationState",str(row.get("distributor_state")));out.put("tier",allowed?tier:0);out.put("mode",mode);out.put("netSpend",total);out.put("automaticTier",auto);
  out.put("discountRates",Arrays.asList(tiers.getJSONObject(0).getLongValue("rate"),tiers.getJSONObject(1).getLongValue("rate"),tiers.getJSONObject(2).getLongValue("rate")));out.put("thresholds",Arrays.asList(0L,upgradeAmount));out.put("tiers",tiers);
  if(allowed)out.putAll(tiers.getJSONObject(tier-1));
  if(allowed&&"auto".equals(mode)&&tier==1){out.put("nextAmount",upgradeAmount);out.put("remainingAmount",Math.max(0,upgradeAmount-total));}
  return out;
 }
 public JSONObject profile(long uid){Map<String,Object> row=s.one("select m.distributor_state,m.enabled account_enabled,p.mode,p.tier override_tier,coalesce(t.net_spend,0) net_spend from shop_member m left join shop_partner_profile p on p.member_id=m.id left join ("+spend("o.member_id=?")+") t on t.member_id=m.id where m.id=?",includeTestOrders||s.isDemo(),uid,uid);return resolve(row,settings());}
 private boolean flag(Object v){return Boolean.TRUE.equals(v)||"1".equals(str(v));}
 public void validatePayment(Map<String,Object> order){if(!"partner".equals(order.get("business_type")))return;JSONObject current=require(number(order.get("member_id"))),saved=JSON.parseObject(str(order.get("rules_json"))).getJSONObject("partner");check(saved!=null&&current.getIntValue("tier")>=saved.getIntValue("tier"),"拿货权益已变化，请取消此待付款订单并按当前权益重新下单");}
 public JSONObject require(long uid){JSONObject p=profile(uid);check(p.getBooleanValue("enabled"),"请先申请分销商并通过审核；已审核账号请确认拿货权益未停用");return p;}
 private void owner(long uid){check(require(uid).getIntValue("tier")==3,"仅共建合伙人可管理助手账号");}
 public long price(Map<String,Object> product,JSONObject p){check(settings().getJSONArray("excludedProducts").stream().noneMatch(x->number(x)==number(product.get("id"))),"该商品不参加专属拿货，请从零售商城购买");return Math.max(1,ShopCommerce.portion(number(product.get("price")),p.getLongValue("rate"),10000));}
 public JSONObject catalogPrices(long uid,List<Map<String,Object>> products){
  if(uid<=0)return null;
  JSONObject profile=profile(uid);
  if(!profile.getBooleanValue("distributor"))return null;
  if(profile.getBooleanValue("enabled")){
   Set<Long> excluded=new HashSet<>();for(Object id:settings().getJSONArray("excludedProducts"))excluded.add(number(id));
   for(Map<String,Object> product:products)if(flag(product.get("retail_enabled"))&&!excluded.contains(number(product.get("id"))))
    product.put("partnerPrice",Math.max(1,ShopCommerce.portion(number(product.get("standardPrice")),profile.getLongValue("rate"),10000)));
  }
  return profile;
 }
 public Map<String,Object> own(long uid){JSONObject p=profile(uid),out=new JSONObject();out.put("profile",p);out.put("products",new ArrayList<>());out.put("assistant",s.jdbc().queryForList("select a.member_id,c.username,a.expires_at from shop_partner_assistant a left join shop_credentials c on c.member_id=a.member_id where a.owner_id=?",uid));out.put("assisting",s.jdbc().queryForList("select a.owner_id,m.nickname from shop_partner_assistant a join shop_member m on m.id=a.owner_id join shop_partner_profile p on p.member_id=a.owner_id where a.member_id=? and p.enabled=1 and p.tier=3 and m.enabled=1",uid));if(!p.getBooleanValue("enabled"))return out;List<Map<String,Object>> products=s.products();s.catalogStock(products);Set<Long> excluded=new HashSet<>();for(Object id:settings().getJSONArray("excludedProducts"))excluded.add(number(id));products.removeIf(x->!flag(x.get("retail_enabled"))||excluded.contains(number(x.get("id"))));for(Map<String,Object> x:products){x.put("standardPrice",x.get("price"));x.put("price",Math.max(1,ShopCommerce.portion(number(x.get("price")),p.getLongValue("rate"),10000)));x.remove("wholesale");x.remove("pricing_json");}out.put("products",products);return out;}
 @Transactional public void assign(JSONObject b,String who){long uid=integer(b.get("memberId"),1,Long.MAX_VALUE,"请选择客户");Map<String,Object> member=s.one("select id,distributor_state from shop_member where id=? for update",uid);String mode=str(b.getOrDefault("mode",b.getBooleanValue("enabled")?"fixed":"blocked"));check(Arrays.asList("auto","fixed","blocked").contains(mode),"请选择自动升级、指定权益或停用");check("blocked".equals(mode)||"approved".equals(member.get("distributor_state")),"请先由用户申请分销商并审核通过，再设置拿货档位");long tier="fixed".equals(mode)?integer(b.get("tier"),1,3,"请选择拿货档位"):0;boolean enabled=!"blocked".equals(mode);String reason="auto".equals(mode)?"恢复累计净实付自动升级":"blocked".equals(mode)?"后台停用拿货权益":"后台一键设置拿货权益";s.jdbc().update("insert into shop_partner_profile(member_id,tier,enabled,reason,mode) values(?,?,?,?,?) on duplicate key update tier=values(tier),enabled=values(enabled),reason=values(reason),mode=values(mode),updated_at=now()",uid,tier,enabled,reason,mode);if(!"fixed".equals(mode)||tier!=3)s.jdbc().update("delete from shop_partner_assistant where owner_id=?",uid);s.event("partner",uid,reason+"，档位"+tier,who);}
 @Transactional public void save(JSONObject b,String who){JSONArray tiers=b.getJSONArray("tiers"),excluded=b.getJSONArray("excludedProducts"),groups=b.getJSONArray("catalogGroups");check(tiers!=null&&tiers.size()==3,"请保留三个拿货档位");JSONArray clean=new JSONArray();for(int i=0;i<3;i++){JSONObject t=tiers.getJSONObject(i),x=new JSONObject();String name=str(t.get("name")).trim();check(!name.isEmpty()&&name.length()<=30,"档位名称为1至30字");x.put("name",name);x.put("rate",integer(t.get("rate"),1,10000,"折扣须大于0且不超过10折"));x.put("referenceAmount",i==1?integer(t.get("referenceAmount"),1,100000000000L,"升级金额须大于0"):0);clean.add(x);}check(clean.getJSONObject(0).getLongValue("rate")>=clean.getJSONObject(1).getLongValue("rate")&&clean.getJSONObject(1).getLongValue("rate")>=clean.getJSONObject(2).getLongValue("rate"),"更高拿货档位的付款折扣不能高于前一档");check(excluded!=null&&excluded.size()<=10000,"请选择不参与商品");for(Object id:excluded)integer(id,1,Long.MAX_VALUE,"商品编号不正确");if(groups==null)groups=new JSONArray();check(groups.size()<=20,"大分类最多20个");Set<String> children=new HashSet<>(),names=new HashSet<>();JSONArray categories=s.rules().getJSONArray("categories");for(Object obj:groups){JSONObject g=JSON.parseObject(JSON.toJSONString(obj));String name=str(g.get("name")).trim();check(!name.isEmpty()&&name.length()<=30&&names.add(name),"大分类名称不能为空或重复");JSONArray cats=g.getJSONArray("categories");check(cats!=null&&!cats.isEmpty(),"每个大分类至少选择一个子分类");for(Object c:cats)check(categories.contains(c)&&children.add(str(c)),"子分类需来自现有分类，且不能重复归组");}JSONObject out=new JSONObject();out.put("tiers",clean);out.put("excludedProducts",excluded);out.put("catalogGroups",groups);s.jdbc().update("update shop_config set content=? where config_key='partner'",out.toJSONString());s.event("partner",0,"更新专属价格和商品分类，新订单生效",who);}
 @Transactional public Map<String,Object> invite(long uid){s.one("select id from shop_member where id=? for update",uid);owner(uid);check(s.jdbc().queryForObject("select count(*) from shop_partner_assistant where owner_id=? and member_id is not null",Long.class,uid)==0,"已有助手，请先解除后再邀请");String token=UUID.randomUUID().toString().replace("-","");s.jdbc().update("insert into shop_partner_assistant(owner_id,token_hash,expires_at) values(?,?,date_add(now(),interval 7 day)) on duplicate key update token_hash=values(token_hash),expires_at=values(expires_at)",uid,s.hash(token));s.event("partner",uid,"生成助手邀请，7天有效",str(uid));return Collections.singletonMap("token",token);}
 @Transactional public void accept(long uid,String token){check(token.matches("[a-zA-Z0-9]{32}"),"请输入完整助手邀请码");List<Map<String,Object>> found=s.jdbc().queryForList("select owner_id from shop_partner_assistant where token_hash=?",s.hash(token));check(!found.isEmpty(),"邀请无效或已使用");long owner=number(found.get(0).get("owner_id"));s.one("select id from shop_member where id=? for update",owner);owner(owner);check(owner!=uid,"不能接受自己的助手邀请");check(s.jdbc().queryForObject("select count(*) from shop_partner_assistant where member_id=?",Long.class,uid)==0,"此账号已是其他合伙人的助手，请先解除");int n=s.jdbc().update("update shop_partner_assistant set member_id=?,token_hash=null,expires_at=null where owner_id=? and token_hash=? and member_id is null and expires_at>now()",uid,owner,s.hash(token));check(n==1,"邀请已过期、已使用或已撤销");s.event("partner",owner,"助手接受邀请，账号编号"+uid,str(uid));}
 @Transactional public void revoke(long uid){s.one("select id from shop_member where id=? for update",uid);owner(uid);s.jdbc().update("delete from shop_partner_assistant where owner_id=?",uid);s.event("partner",uid,"解除助手及未接受邀请",str(uid));}
 public Map<String,Object> dashboard(long uid){long target=uid;JSONObject p=profile(uid);if(!p.getBooleanValue("enabled")||p.getIntValue("tier")!=3){List<Map<String,Object>> rows=s.jdbc().queryForList("select owner_id from shop_partner_assistant where member_id=?",uid);check(!rows.isEmpty(),"当前账号没有合伙人工作台权限");target=number(rows.get(0).get("owner_id"));owner(target);}JSONObject out=new JSONObject();out.put("ownerId",target);out.put("readOnly",target!=uid);out.put("orders",s.jdbc().queryForList("select order_no,business_type,status,amount,created_at from shop_order where member_id=? order by id desc",target));out.put("rewards",s.jdbc().queryForList("select o.order_no,o.channel,r.depth,r.amount,r.available_amount,r.reason from shop_reward r join shop_order o on o.id=r.order_id where r.member_id=?"+s.verifiedPayment("o.id")+" order by r.id desc",target));return out;}
 public Map<String,Object> admin(){JSONObject out=new JSONObject(),config=settings();out.put("settings",config);List<Map<String,Object>> rows=s.jdbc().queryForList("select m.id,m.nickname,c.username,m.distributor_state,m.enabled account_enabled,p.mode,p.tier override_tier,p.reason,coalesce(t.net_spend,0) net_spend from shop_member m left join shop_credentials c on c.member_id=m.id left join shop_partner_profile p on p.member_id=m.id left join ("+spend("1=1")+") t on t.member_id=m.id where m.is_test=0 order by m.id desc",includeTestOrders||s.isDemo());for(Map<String,Object> row:rows)row.putAll(resolve(row,config));out.put("members",rows);out.put("products",s.jdbc().queryForList("select id,name,spec from shop_product where archived=0 order by id"));out.put("categories",s.rules().get("categories"));return out;}
}
