package com.ruoyi.web.controller.shop;
import java.util.*;import java.nio.file.*;import org.springframework.beans.factory.annotation.*;import org.springframework.context.annotation.Lazy;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopChatRetention {
 @Autowired @Lazy ShopService s;@Autowired ShopChat chat;@Value("${shop.private-path:../runtime/private}") String privatePath;
 @Transactional public void purge(long id){Map<String,Object> c=s.one("select * from shop_chat where id=? for update",id);if(Boolean.TRUE.equals(c.get("protected"))||"1".equals(str(c.get("protected"))))return;
 long disputes=s.jdbc().queryForObject("select (select count(*) from shop_case x where x.status not in ('refunded','completed','rejected') and (x.member_id=? or x.order_id in (select order_id from shop_chat_message where chat_id=? and order_id is not null)))+(select count(*) from shop_after_sale x where x.status='pending' and (x.member_id=? or x.order_id in (select order_id from shop_chat_message where chat_id=? and order_id is not null)))",Long.class,c.get("member_id"),id,c.get("member_id"),id);if(disputes>0)return;
 if("closed".equals(c.get("status"))){long days=chat.settings().getLongValue("retentionDays");s.jdbc().update("insert ignore into shop_chat_file_gc(path) select i.path from shop_chat_image i join shop_chat_message m on m.id=i.message_id where m.chat_id=? and m.created_at<date_sub(now(),interval ? day)",id,days);s.jdbc().update("delete i from shop_chat_image i join shop_chat_message m on m.id=i.message_id where m.chat_id=? and m.created_at<date_sub(now(),interval ? day)",id,days);s.jdbc().update("delete from shop_chat_message where chat_id=? and created_at<date_sub(now(),interval ? day)",id,days);}
 s.jdbc().update("insert ignore into shop_chat_file_gc(path) select path from shop_chat_image where chat_id=? and message_id is null and created_at<date_sub(now(),interval 1 day)",id);s.jdbc().update("delete from shop_chat_image where chat_id=? and message_id is null and created_at<date_sub(now(),interval 1 day)",id);
 }
 public void deleteFile(String name)throws java.io.IOException {check(name.matches("[a-f0-9-]{36}\\.png"),"聊天文件路径不正确");Path dir=Paths.get(privatePath).toAbsolutePath().normalize().resolve("chat"),file=dir.resolve(name).normalize();check(file.startsWith(dir),"聊天文件超出目录");Files.deleteIfExists(file);s.jdbc().update("delete from shop_chat_file_gc where path=?",name);}
}
