package com.ruoyi.web.controller.shop;
import java.util.*;import java.time.*;import com.alibaba.fastjson2.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.context.annotation.Lazy;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import static com.ruoyi.web.controller.shop.ShopService.*;
@Service public class ShopChat {
 @Autowired @Lazy ShopService s;@Autowired ShopNotices notices;
 public JSONObject settings(){return JSON.parseObject(str(s.one("select content from shop_config where config_key='support'").get("content")));}
 public void settings(JSONObject b,String who){long start=integer(b.get("startHour"),0,23,"开始时间为0至23点"),end=integer(b.get("endHour"),1,24,"结束时间为1至24点");check(end>start,"结束时间须晚于开始时间");JSONObject r=new JSONObject();r.put("startHour",start);r.put("endHour",end);r.put("weekdaysOnly",b.getBooleanValue("weekdaysOnly"));r.put("idleDays",integer(b.get("idleDays"),1,90,"无新消息自动结束时间为1至90天"));r.put("retentionDays",integer(b.get("retentionDays"),30,730,"聊天保留时间为30至730天"));String text=str(b.get("offlineText")).trim();check(text.length()>=2&&text.length()<=300,"请填写非工作时间提示");r.put("offlineText",text);s.jdbc().update("update shop_config set content=? where config_key='support'",r.toJSONString());s.event("support",0,"修改客服时间与保留设置",who);}
 @Transactional public Map<String,Object> own(long uid){s.one("select id from shop_member where id=? for update",uid);s.jdbc().update("insert ignore into shop_chat(member_id) values(?)",uid);return s.one("select * from shop_chat where member_id=?",uid);}
 public Map<String,Object> view(long id,long before){Map<String,Object> c=s.one("select c.*,m.nickname from shop_chat c join shop_member m on m.id=c.member_id where c.id=?",id);List<Map<String,Object>> rows=s.jdbc().queryForList("select id,sender,sender_id,body,image_id,order_id,created_at from shop_chat_message where chat_id=?"+(before>0?" and id<"+before:"")+" order by id desc limit 50",id);Collections.reverse(rows);c.put("messages",rows);JSONObject rules=settings();LocalDateTime now=LocalDateTime.now(ZoneId.of("Asia/Shanghai"));boolean weekday=now.getDayOfWeek()!=DayOfWeek.SATURDAY&&now.getDayOfWeek()!=DayOfWeek.SUNDAY;rules.put("working",(!rules.getBooleanValue("weekdaysOnly")||weekday)&&now.getHour()>=rules.getIntValue("startHour")&&now.getHour()<rules.getIntValue("endHour"));c.put("settings",rules);return c;}
 public Map<String,Object> ownView(long uid,long before){Map<String,Object> c=own(uid);return view(number(c.get("id")),before);}
 public List<Map<String,Object>> admin(){return s.jdbc().queryForList("select c.*,m.nickname,(select count(*) from shop_chat_message x where x.chat_id=c.id and x.sender='member' and x.id>c.staff_read_id) unread"+ShopQueryFields.fields("m.id")+" from shop_chat c join shop_member m on m.id=c.member_id order by c.last_message_at desc");}
 @Transactional public void claim(long id,String who){Map<String,Object> c=s.one("select * from shop_chat where id=? for update",id);check(c.get("assigned_to")==null||who.equals(c.get("assigned_to")),"会话已由其他客服接待");s.jdbc().update("update shop_chat set assigned_to=?,status='open' where id=?",who,id);}
 @Transactional public void state(long id,String who,JSONObject b,boolean manager){Map<String,Object> c=s.one("select * from shop_chat where id=? for update",id);check(manager||who.equals(c.get("assigned_to")),"请先领取该会话");String action=b.getString("action");if("close".equals(action))s.jdbc().update("update shop_chat set status='closed' where id=?",id);else if("protect".equals(action))s.jdbc().update("update shop_chat set protected=? where id=?",b.getBooleanValue("protected"),id);else throw new IllegalArgumentException("请选择结束会话或争议保留");s.event("chat",id,action,who);}
 @Transactional public void memberRead(long uid,long id){Map<String,Object> c=s.one("select id from shop_chat where member_id=? for update",uid);check(id>=0&&s.jdbc().queryForObject("select count(*) from shop_chat_message where id=? and chat_id=?",Long.class,id,c.get("id"))>0,"消息不属于当前会话");s.jdbc().update("update shop_chat set member_read_id=greatest(member_read_id,?) where id=?",id,c.get("id"));}
 @Transactional public void staffRead(long id,long last,String who){Map<String,Object> c=s.one("select * from shop_chat where id=? for update",id);check(who.equals(c.get("assigned_to")),"请先领取会话");check(s.jdbc().queryForObject("select count(*) from shop_chat_message where id=? and chat_id=?",Long.class,last,id)>0,"消息不属于当前会话");s.jdbc().update("update shop_chat set staff_read_id=greatest(staff_read_id,?) where id=?",last,id);}
 @Transactional public void sendMember(long uid,JSONObject b){long id=number(own(uid).get("id"));send(id,"member","member:"+uid,b);}
 @Transactional public void sendStaff(long id,String who,JSONObject b){send(id,"staff","staff:"+who,b);}
 private void send(long id,String sender,String senderId,JSONObject b){Map<String,Object> c=s.one("select * from shop_chat where id=? for update",id);if("staff".equals(sender))check(senderId.equals("staff:"+str(c.get("assigned_to")))&&"open".equals(c.get("status")),"请先领取该会话");String body=str(b.get("body")).trim(),key=str(b.get("requestKey"));long image=b.getLongValue("imageId"),order=b.getLongValue("orderId");check(body.length()<=2000&&(!body.isEmpty()||image>0),"请填写消息或选择图片，文字最多2000字");check(key.matches("[a-zA-Z0-9_-]{8,80}"),"请重新发送消息");List<Map<String,Object>> previous=s.jdbc().queryForList("select * from shop_chat_message where chat_id=? and sender_id=? and request_key=?",id,senderId,key);if(!previous.isEmpty()){Map<String,Object> old=previous.get(0);check(body.equals(old.get("body"))&&image==number(old.get("image_id"))&&order==number(old.get("order_id")),"重复发送标识的内容不一致");return;}
 if(image>0){Map<String,Object> file=s.one("select * from shop_chat_image where id=? and chat_id=? for update",image,id);check(senderId.equals(file.get("uploader"))&&file.get("message_id")==null,"图片不属于当前发送者或已被使用");}if(order>0)s.companyOrder(number(c.get("member_id")),order,"view",false);
 s.jdbc().update("insert into shop_chat_message(chat_id,sender,sender_id,body,image_id,order_id,request_key) values(?,?,?,?,?,?,?)",id,sender,senderId,body,image>0?image:null,order>0?order:null,key);long message=number(s.one("select id from shop_chat_message where chat_id=? and sender_id=? and request_key=?",id,senderId,key).get("id"));if(image>0)s.jdbc().update("update shop_chat_image set message_id=? where id=?",message,image);if("member".equals(sender)&&"closed".equals(c.get("status")))s.jdbc().update("update shop_chat set status='open',assigned_to=null where id=?",id);s.jdbc().update("update shop_chat set last_message_at=now() where id=?",id);if("staff".equals(sender))notices.add(number(c.get("member_id")),"chat_"+message,"service","客服回复了您的留言","请进入会话查看回复。","support",0);}
 public Map<String,Object> image(long id,Long uid){Map<String,Object> f=s.one("select i.*,c.member_id from shop_chat_image i join shop_chat c on c.id=i.chat_id where i.id=?",id);if(uid!=null)check(number(f.get("member_id"))==uid,"图片不属于当前会话");return f;}
 public void allowStaffImage(long id,String who){Map<String,Object> c=s.one("select * from shop_chat where id=?",id);check(who.equals(c.get("assigned_to"))&&"open".equals(c.get("status")),"请先领取会话再上传图片");}
 public long registerImage(long id,String name,String uploader){s.jdbc().update("insert into shop_chat_image(chat_id,path,uploader) values(?,?,?)",id,name,uploader);return number(s.one("select id from shop_chat_image where path=?",name).get("id"));}
}
