CREATE TABLE IF NOT EXISTS shop_wechat_payment (
 order_id BIGINT PRIMARY KEY,
 out_trade_no VARCHAR(32) NOT NULL UNIQUE,
 payer_openid VARCHAR(128) NOT NULL,
 amount BIGINT NOT NULL,
 state VARCHAR(24) NOT NULL DEFAULT 'CREATING',
 prepay_id VARCHAR(128) NULL,
 transaction_id VARCHAR(64) NULL UNIQUE,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shop_wechat_refund (
 case_id BIGINT PRIMARY KEY,
 order_id BIGINT NOT NULL,
 out_refund_no VARCHAR(64) NOT NULL UNIQUE,
 amount BIGINT NOT NULL,
 state VARCHAR(24) NOT NULL DEFAULT 'QUEUED',
 refund_id VARCHAR(64) NULL UNIQUE,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
