CREATE TABLE IF NOT EXISTS shop_distribution_rule(id BIGINT PRIMARY KEY AUTO_INCREMENT,channel CHAR(1) NOT NULL,product_id BIGINT NOT NULL DEFAULT 0,tier INT NOT NULL DEFAULT -1,depth INT NOT NULL,kind VARCHAR(20) NOT NULL,basis VARCHAR(20) NOT NULL DEFAULT 'net',value BIGINT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE KEY rule_match(channel,product_id,tier,depth));
CREATE TABLE IF NOT EXISTS shop_distribution_profile(member_id BIGINT PRIMARY KEY,tier INT NOT NULL DEFAULT 0,frozen BOOLEAN NOT NULL DEFAULT FALSE,reason VARCHAR(500) NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS shop_company_referral(company_id BIGINT PRIMARY KEY,referrer_id BIGINT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS shop_distribution_order(order_id BIGINT PRIMARY KEY,snapshot_json MEDIUMTEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shop_reward(id BIGINT PRIMARY KEY AUTO_INCREMENT,order_id BIGINT NOT NULL,item_id BIGINT NOT NULL,member_id BIGINT NOT NULL,depth INT NOT NULL,original_amount BIGINT NOT NULL,amount BIGINT NOT NULL,available_amount BIGINT NOT NULL DEFAULT 0,wait_days INT NOT NULL,ready_at DATETIME NULL,reason VARCHAR(100) NOT NULL DEFAULT '等待实际收货',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY reward_line(item_id,depth),INDEX reward_owner(member_id,order_id));
CREATE TABLE IF NOT EXISTS shop_reward_event(id BIGINT PRIMARY KEY AUTO_INCREMENT,reward_id BIGINT NOT NULL,member_id BIGINT NOT NULL,order_id BIGINT NOT NULL,delta BIGINT NOT NULL,available_delta BIGINT NOT NULL,note VARCHAR(200) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT IGNORE INTO shop_config(config_key,content) VALUES('distribution','{"secondEnabled":false,"tiers":["基础","银卡","金卡"],"autoTier":false,"silver":500000,"gold":2000000}');

CREATE TABLE IF NOT EXISTS shop_distribution_attribution(order_id BIGINT NOT NULL,member_id BIGINT NOT NULL,depth INT NOT NULL,PRIMARY KEY(order_id,depth),INDEX attribution_owner(member_id));
